### ISSUE TITLE
Latest release still on 0.13.2

### ISSUE THREAD

**Issue by hevy-CC4477** [NVIDIA/caffe#106]
Hi,

Any reason why the latest release flag is still on 0.13.2 ?

Thanks,

**Comment by lukeyeager** [comment]
We still don't have a public, packaged, final release of v0.14 yet. Once we do, I'll write up some release notes for the final tag and merge https://github.com/NVIDIA/caffe/pull/96, promoting the `caffe-0.14` branch to `master`.
