### ISSUE TITLE
Add batch normalization layer

### ISSUE THREAD

**Issue by 201power** [NVIDIA/caffe#107]
It seems the NVcaffe does not have batch normalization layer yet, which is already exist in caffe master branch. Can we add this update to NVcaffe? 
A general question: can digits use Caffe master branch directly?

**Comment by lukeyeager** [comment]
We have batch normalization in the `caffe-0.14` branch. It should be promoted to the `master` branch soon (see https://github.com/NVIDIA/caffe/issues/106#issuecomment-174594771).

You could use a deb package to install a prebuilt version of `v0.14.0-rc.3`, which includes batch normalization. Instructions here: https://github.com/NVIDIA/DIGITS/blob/digits-3.0/docs/UbuntuInstall.md

And no, you can't use DIGITS with BVLC/caffe yet. DIGITS needs to know how to interface with Caffe, and without a version number there's no way to tell which interface to use. https://github.com/BVLC/caffe/pull/3311 helps, but it remains to be seen what sort of versioning strategy BVLC is going to employ.
