### ISSUE TITLE
got an error when compile caffe-experimental-fp16 on TX1.

### ISSUE THREAD

**Issue by leejiajun** [NVIDIA/caffe#115]
What is cub/cub/cub.cuh?

> /home/lijiajun/caffe-experimental-fp16/src/caffe/layers/softmax_loss_layer.cu:9:27: fatal error: cub/cub/cub.cuh: No such file or directory
 #include "cub/cub/cub.cuh"
                           ^
compilation terminated.
CMake Error at cuda_compile_generated_softmax_loss_layer.cu.o.cmake:206 (message):
  Error generating
  /home/lijiajun/caffe-experimental-fp16/build/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_softmax_loss_layer.cu.o
make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_softmax_loss_layer.cu.o] Error 1
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2

**Comment by lukeyeager** [comment]
The build system should download [CUB](https://github.com/NVlabs/cub) for you automatically now.
