### ISSUE TITLE
"For Python, for now, we'll just always use float as the type", _caffe.cpp

### ISSUE THREAD

**Issue by leejiajun** [NVIDIA/caffe#117]
How to support float16?

**Comment by drnikolaev** [comment]
You may try https://github.com/drnikolaev/caffe/tree/caffe-0.14-fp16 with appropriate changes (float --> float16) made in _caffe.cpp

**Comment by leejiajun** [comment]
@drnikolaev 
if I change 
`typedef float Dtype;` to `typedef float16 Dtype;`
`typedef float Mtype;` to `typedef float16 Mtype;`, 
I will get an error 
> Traceback (most recent call last):
  File "./tools/demo.py", line 18, in <module>
    from fast_rcnn.test import im_detect
  File "/home/lijiajun/faster-rcnn-fp16/tools/../lib/fast_rcnn/test.py", line 16, in <module>
    import caffe
  File "/home/lijiajun/faster-rcnn-fp16/tools/../caffe-fast-rcnn/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/home/lijiajun/faster-rcnn-fp16/tools/../caffe-fast-rcnn/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: /home/lijiajun/faster-rcnn-fp16/tools/../caffe-fast-rcnn/python/caffe/_caffe.so: undefined symbol: _ZN5caffe6SolverIN10half_float4halfES2_E5SolveEPKc

**Comment by drnikolaev** [comment]
Did you set NATIVE_FP16=1 in Makefile.config when you built caffe library?

**Comment by leejiajun** [comment]
@drnikolaev 
Yes, I did. And I even try to #include <numpy/halffloat.h>.

**Comment by leejiajun** [comment]
@drnikolaev

**Comment by jagmohan-nd** [comment]
@drnikolaev 
caffe_fp16 the C executable is showing the speedup but python is not showing the expected speedup. I have changed float to float16 and other changes which @leejiajun has done.

**Comment by drnikolaev** [comment]
@leejiajun @jagmohan-nd you may try 0.16 release, it supports fp16

**Comment by shuyu0815** [comment]
@drnikolaev 
Is the 0.15 supports fp16 for python ?
Because the TX1 haven't supported the cuDNNv6, I can't try to us the 0.16.

Thanks !

**Comment by jagmohan-nd** [comment]
thanks @drnikolaev
