### ISSUE TITLE
Request - integrate code for all-in-one nets

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/caffe#118]
https://github.com/BVLC/caffe/issues/1245 is nearing completion.
- https://github.com/BVLC/caffe/pull/3211 adds support for `Input` layers
- https://github.com/BVLC/caffe/pull/3736 adds better support for stages

Once all-in-one nets are fully supported, the DIGITS team would like to make use of these new features in order to specify networks all in a single file instead of having separate `train_val` and `deploy` networks.

**Comment by lukeyeager** [comment]
Updates:
- https://github.com/BVLC/caffe/pull/3211 is included in the `caffe-0.15` branch
- https://github.com/BVLC/caffe/issues/3863 will be included in the `caffe-0.16` branch

**Comment by drnikolaev** [comment]
@lukeyeager may I close it?

**Comment by lukeyeager** [comment]
Actually, it doesn't look like we've pulled in https://github.com/BVLC/caffe/pull/3863 after all. You can close this as will-not-fix if you like, but without those changes we still can't really do all-in-one nets.

Of course, based on the lack of progress in https://github.com/BVLC/caffe/issues/3864, it doesn't seem like there's much of a desire for this feature anyway.

**Comment by KeithWM** [comment]
I'm new to caffe, but I don't understand why there isn't more enthusiasm about this feature. To me it seems unnecessarily convoluted and error prone to require maintaining two nigh identical prototxt files. Or am I missing some alternative way of keeping my train and deploy (or test) networks properly aligned?

**Comment by drnikolaev** [comment]
Keeping this in TODO list..

**Comment by drnikolaev** [comment]
Done in v0.17.0
