### ISSUE TITLE
Error on build from source- error: identifier "cudnnBatchNormMode_t" is undefined

### ISSUE THREAD

**Issue by igorbb** [NVIDIA/caffe#119]
I want to do a custom build over the NVCAFFE, and for now I am building from the original source... 

 cloned from:  --branch caffe-0.14 https://github.com/NVIDIA/caffe.git 

This is the CMAKE configuration summary 

```
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   0.14.2
--   Git               :   v0.14.2
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   ON
--   USE_LEVELDB       :   ON
--   USE_LMDB          :   ON
--   ALLOW_LMDB_NOLOCK :   OFF
-- 
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.54)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 2.5.0)
--   lmdb              :   Yes (ver. 0.9.10)
--   LevelDB           :   Yes (ver. 1.15)
--   Snappy            :   Yes (ver. 1.1.0)
--   OpenCV            :   Yes (ver. 2.4.8)
--   CUDA              :   Yes (ver. 7.0)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_52
--   cuDNN             :   Yes
-- 
-- Python:
--   Interpreter       :   /home/igorbb/anaconda/envs/digits/bin/python2.7 (ver. 2.7.11)
--   Libraries         :   /usr/lib/x86_64-linux-gnu/libpython2.7.so (ver 2.7.6)
--   NumPy             :   /home/igorbb/anaconda/envs/digits/lib/python2.7/site-packages/numpy/core/include (ver 1.10.4)
-- 
-- Documentaion:
--   Doxygen           :   No
--   config_file       :   
-- 
-- Install:
--   Install path      :   /home/igorbb/DIGITS/caffe/build/install
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/igorbb/DIGITS/caffe/build
```

Whenever I start compiling I am getting this error:

```
(digits)igorbb@TOR:~/DIGITS/caffe/build$ make
[  0%] Running C++/Python protocol buffer compiler on /home/igorbb/DIGITS/caffe/src/caffe/proto/caffe.proto
Scanning dependencies of target proto
[  1%] Building CXX object src/caffe/CMakeFiles/proto.dir/__/__/include/caffe/proto/caffe.pb.cc.o
Linking CXX static library ../../lib/libproto.a
[  1%] Built target proto
[  1%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_math_functions.cu.o
[  1%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_exp_layer.cu.o
/home/igorbb/DIGITS/caffe/include/caffe/common_layers.hpp(169): error: identifier "cudnnBatchNormMode_t" is undefined

1 error detected in the compilation of "/tmp/tmpxft_00002635_00000000-7_exp_layer.cpp1.ii".
CMake Error at cuda_compile_generated_exp_layer.cu.o.cmake:264 (message):
  Error generating file
  /home/igorbb/DIGITS/caffe/build/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_exp_layer.cu.o


make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_exp_layer.cu.o] Error 1
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2

```

I could not find much on this compiling error ? Any Idea or suggestions ? Anything I am doing wrong ?

**Comment by gheinrich** [comment]
Hi @igorbb, do you have CuDNN*v4* (libraries + headers)?

If not this version can be installed by following these [instructions](https://github.com/NVIDIA/DIGITS/blob/digits-3.0/docs/BuildCaffe.md#cudnn)

**Comment by igorbb** [comment]
I do. I installed with sudo apt-get install libcudnn4-dev
But as my cmake config points out, my CUDA  is 7.0 ( Cannot update right now)
I will wait until the machine finish a job to see if it is a matter of rebooting..


If the error ensues I will re-open this issue.

**Comment by igorbb** [comment]
Hey @gheinrich . Thanks for the fast feedback.
I do. I have installed  it with` sudo apt-get install libcudnn4-dev`
But as my cmake config points out, my CUDA  is 7.0 ( Cannot update right now)
I will wait until the machine finish a job to see if it is a matter of rebooting..


If the error ensues I will let you guys know.

**Comment by igorbb** [comment]
After reboot I still have the problem. And libcudnn4-dev is up to date ...

Does the current version conflict with previous CUDNN versionsor they can co-exist ?

If only one should be installed, is cudnn4 backward compatible with cudnn3?

**Comment by gheinrich** [comment]
Support for batch normalization in CUDNN is new in v4. Your `cudnn.h` header should point to the v4 and have `#define CUDNN_MAJOR 4`. Your build system might still be pointing to the v3 if you installed it previously.

**Comment by tommy87** [comment]
Same problem for me, but i had an old header from cudnn 3 (i had install it manual).
I will remove the old dependency and tell you if it works

**Comment by tommy87** [comment]
Deleting the old dependency manualy und reinstalling the new cudnn4 has worked for me.

**Comment by igorbb** [comment]
But is cudnn4 backwards compatible for you?

**Comment by tommy87** [comment]
What do you mean by this? I used Cudnn only for  building caffe, i have no other dependency's to it

**Comment by igorbb** [comment]
Could you build non nvidia versions of caffe? I am waiting for a big job to
finish to be able to try...

**Comment by tommy87** [comment]
i have only tried the nvida version of caffe...
