### ISSUE TITLE
Benchmarking of interference performance on titan X

### ISSUE THREAD

**Issue by charlyng** [NVIDIA/caffe#121]
I have tried to benchmark the inference performance for my titan X to ensure that I am on track. 
Below is the Nvidia publish result VS my result 
According to Table 2 of the Nvidia whitepapers (link as attached below), I'm supposed to get the following results: 

Network: Alexnet (Batch 1) 
- Inference Performance: **405 img/sec** VS **379 img/sec** <----- 7% drop 

Network: Alexnet (Batch 128) 
- Inference Performance: **3216 img/sec** VS **3095 img/sec**  <-----  4% drop 

Is there anywhere that I could have done wrongly? 

Below is my environment setting 
cuda7.5, cudnn4, TitanX 

Thank you.

**Comment by flx42** [comment]
Hello,

Try to apply the following patch:
https://github.com/flx42/caffe/commit/fc876e02739a80afd1fbc7b3045cca559ce83b31

You should also set your CPU governor to "performance" before running the benchmark. To avoid dynamic frequency scaling at the beginning.

**Comment by weishengchong** [comment]
Hi @flx42 

Thank you for your reply.

Actually I already disable codes for

1. layers[i]->Backward() and
2. layer's timing 

I attached my tools\caffe.cpp for your reference.
[caffe.zip](https://github.com/NVIDIA/caffe/files/170681/caffe.zip)

It seems CPU governor controls the frequency of CPU , I will check how it affect caffe's performance.
Do I need to set GPU frequency as I did in Tx1's caffe_fp16 evaluation? If yes, does it mean set GPU to to max frequency?

Thank you very much.

**Comment by weishengchong** [comment]
Hi @flx42 

Would you please kindly share your advices issue below for branch [https://github.com/NVIDIA/caffe/tree/experimental/fp16](url)?

[https://github.com/NVIDIA/caffe/issues/120](url)


Thank you very much.

**Comment by flx42** [comment]
Yes, CPU governor affects the CPU but it might make the benchmarks results more stable, I have seen some cases where the first few iterations are 10-15% slower because of this.
For a GeForce GPU, you can list the available clocks with this command (for GPU 0):
```
nvidia-smi -q -i 0 -d SUPPORTED_CLOCKS
```
And then you can set the clock to the max Memory/Graphics pair, for instance:
```
nvidia-smi -i 0 -ac 3505,1392
```

Sorry I can't help you regarding fp16.

**Comment by weishengchong** [comment]
Hi @flx42,

>(1) sudo nvidia-smi -i 0 -ac 3505,1392
I tried above command with output below

>      Applications clocks set to "(MEM 3505, SM 1392)" for GPU 0000:05:00.0

However,  (2)nvidia-smi -q returns same SM frequency
>     Clocks
>         Graphics  : 1001 MHz
>         SM  : 1001 MHz  <---------- (3)expect 1392MHz after "sudo nvidia-smi -i 0 -ac 3505,1392"
>         Memory   : 3505 MHz
> 
 
Any ideas of why (3) returns 1001M not 1392M?

**Comment by flx42** [comment]
it could still be fine, do you see a small performance improvement when running the benchmark or is it still the same?

**Comment by charlyng** [comment]
Hi @flx42,

Yes, there is improvement of 2% to 7% with settings below are we manage to reproduce Nvidia's published results for 
Alexnet: batch1, batch128
Googlenet: batch1

However, for Googlenet batch128 results below (Nvidia VS mine), I might miss out something
Inference speed: 863 img/sec VS 976 img/sec <---- 13% faster than published result

Is there anything that I can do to make my reading for Googlenet batch 128 consistent with results as published by Nvidia?

**setting1**
Enable persistence mode: sudo nvidia-smi --persistence-mode=0
Disable auto boost policy: sudo nvidia-smi --auto-boost-default=0

**setting2**
sudo nvidia-smi -i 0 -ac 3505,1392

> Yes, CPU governor affects the CPU but it might make the benchmarks results more stable, I have seen some cases where the first few iterations are 10-15% slower because of this.

I skip above setting because 
1) I run 100 iterations that can reduce impacts of first few iterations.
2) My measurement shows timing for first few iterations are closed to iterations 10~100.

New comparison of Nvidia published result VS my result are as follow (before and after above setting)
Network: Alexnet (Batch 1)
Inference speed: 405 img/sec VS (before 379, after 408) img/sec <-- acceptable after setting

Network: Alexnet (Batch 128)
Inference speed: 3216 img/sec VS (before 3095, after 3179) img/sec <-- acceptable because only 1% lower than published result

**Comment by flx42** [comment]
@charlyng well if your results are better, that's good :). It might just be caused by other factors from your benchmark environment.

**Comment by charlyng** [comment]
Hi @flx42 

Would you please advise on the possible factors that could affect the results? 

I summarized my benchmarks in the page below
https://github.com/charlyng/Embedded-Deep-Learning/blob/master/README.md

Thank you.

**Comment by flx42** [comment]
Well, basically everything else on your machine: from hardware (CPU/memory/motherboard), hardware settings (clocks), to software (NVIDIA driver, kernel version, etc.).

**Comment by weishengchong** [comment]
Interestingly, the factor 
-only affect Googlenet batch128 <-- my speed is 13% faster 
-not affecting Googlenet batch1 and Alexnet batch1&128

**Comment by renganxu** [comment]
@charlyng How did you measure the inference performance with Nvidia Caffe? e.g. How did you get 379 img/sec for inferencing? Could you provide any user guide or detailed steps? Thanks.
