### ISSUE TITLE
Compile error   And Traing with GPU is slow just like with CPU

### ISSUE THREAD

**Issue by amirkhango** [NVIDIA/caffe#124]
When I compile with Makefile.config USE_CUDNN := 1 ,I get this error:

src/caffe/layers/cudnn_conv_layer.cu(81): error: argument of type "cudnnAddMode_t" is incompatible with parameter of type "const void *"

If I comment out USE_CUDNN := 1, compilation is OK, but training with is GPU is very slow just like with CPU.
Can you help me?

**Comment by jdemouth** [comment]
Which version of cuDNN are you using?

**Comment by amirkhango** [comment]
@jdemouth  hi, I don't know how to find the cuDNN's version, but I search file called libcudnn.so.4.0.4, is it my version(4.0.4)? However, another serious problem I proposed is that compliation with GPU's speed is as slow as with CPU in MNIST test.
