### ISSUE TITLE
Update latest release

### ISSUE THREAD

**Issue by hevy-CC4477** [NVIDIA/caffe#126]
Hi,

Any idea of when you will update the "latest release" ?

Thanks,

**Comment by futurely** [comment]
https://github.com/NVIDIA/caffe/tree/caffe-0.15

**Comment by lukeyeager** [comment]
Caffe [v0.15.9](https://github.com/NVIDIA/caffe/releases/tag/v0.15.9) is our latest release.

There are deb packages available. Installation instructions here:
https://github.com/NVIDIA/DIGITS/blob/digits-4.0/docs/UbuntuInstall.md
