### ISSUE TITLE
Why do you use two typenames in the Blob's template?

### ISSUE THREAD

**Issue by huangjunshi** [NVIDIA/caffe#130]
First of all, thanks so much for this great work. :)

I am not sure what's the advantage of using two typenames, instead of one, such as in the definition

`template <typename Dtype> class Blob {  ...  }`,

we can still declare a Blob with float16 type. What's usage of `typename Mtype` in
`template <typename Dtype, typename Mtype> class Blob {  ...  }`? I guess it's defined for the scalar variable, but why?

Thanks.

**Comment by drnikolaev** [comment]
What branch are you looking at?

**Comment by huangjunshi** [comment]
Hi, the branch "experimental/fp16" :)

**Comment by drnikolaev** [comment]
Oh, it's the old one, newer one is here: https://github.com/drnikolaev/caffe/tree/caffe-0.14-fp16
"D" stands for Data and "M" stands for Math - we try to separate computing from storage. It's very experimental though and yet to be seen whether we need this...

**Comment by huangjunshi** [comment]
I c, thanks a lot! :)

**Comment by hujie-frank** [comment]
I am porting some caffe code to fp16. I face problem with batch normalisation (BN). It seems that cudnn doesn't support BN for fp16. The caffe engine seems prone to overflow if i use fp 16. Do you have a solution?

**Comment by wangsssky** [comment]
https://github.com/drnikolaev/caffe/tree/caffe-0.14-fp16 the link doesn't work. Is experimental/fp16 the only branch that currently support fp16?

**Comment by drnikolaev** [comment]
@maybepossible please try 0.16 release
