### ISSUE TITLE
CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by alfredox10** [NVIDIA/caffe#136]
Very little information available online on this error code. I have not been able to figure out why it happens, I can say that it happens exactly when stepping over the line:
`net.forward()`

I have 2 GPUs on my system and it only occurs when I try to run it on GPU 0, this does not occur for GPU 1. I thought it may be due to memory however my batch size is small and only takes up 500MB on GPU 1 which has 3 GB (identical GPUs). The out of memory error I believe is (8 vs 0).

All parameters are identical, I am not sure why this only happens with one GPU vs the other.

System: Intel i7, Ubuntu 14.04, CUDA 7.5, nv-caffe v0.14, CuDNN v3, Python, NVIDIA 352, 2x GTX 780 Ti

I believe it may be related to this issue checked in the BLVC version: https://github.com/BVLC/caffe/issues/1700

**Comment by drnikolaev** [comment]
Please try v0.16
