### ISSUE TITLE
./include/caffe/util/cudnn.hpp:137:43: error: ‘CUDNN_PROPAGATE_NAN’ was not declared in this scope

### ISSUE THREAD

**Issue by haoyul** [NVIDIA/caffe#138]
I'm trying to "make all" this Nvidia caffe on 2 computers but both stopped by this error. The "CUDNN_PROPAGATE_NAN" in the very end part of cudnn.hpp caused this error but it doesn't exist in the BVLC/caffe downloaded through caffe official website. Anyone built this caffe successfully and know how to address this error? Please help me. 

Here's the details:
haoyu:~/Software/caffe$ make all
PROTOC src/caffe/proto/caffe.proto
CXX /home/Software/caffe/.build_release/src/caffe/proto/caffe.pb.cc
CXX src/caffe/internal_thread.cpp
In file included from ./include/caffe/util/device_alternate.hpp:40:0,
                 from ./include/caffe/common.hpp:19,
                 from ./include/caffe/internal_thread.hpp:4,
                 from src/caffe/internal_thread.cpp:4:
./include/caffe/util/cudnn.hpp: In function ‘void caffe::cudnn::createPoolingDesc(cudnnPoolingStruct*_, caffe::PoolingParameter_PoolMethod, cudnnPoolingMode_t_, int, int, int, int, int, int)’:
./include/caffe/util/cudnn.hpp:137:43: error: ‘CUDNN_PROPAGATE_NAN’ was not declared in this scope
                                           CUDNN_PROPAGATE_NAN, h, w,
                                           ^
./include/caffe/util/cudnn.hpp:15:28: note: in definition of macro ‘CUDNN_CHECK’
     cudnnStatus_t status = condition; \
                            ^
./include/caffe/util/cudnn.hpp:138:75: error: there are no arguments to ‘cudnnSetPooling2dDescriptor_v4’ that depend on a template parameter, so a declaration of ‘cudnnSetPooling2dDescriptor_v4’ must be available [-fpermissive]
                                           pad_h, pad_w, stride_h, stride_w));
                                                                           ^
./include/caffe/util/cudnn.hpp:15:28: note: in definition of macro ‘CUDNN_CHECK’
     cudnnStatus_t status = condition; \
                            ^
./include/caffe/util/cudnn.hpp:138:75: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
                                           pad_h, pad_w, stride_h, stride_w));
                                                                           ^
./include/caffe/util/cudnn.hpp:15:28: note: in definition of macro ‘CUDNN_CHECK’
     cudnnStatus_t status = condition; \
                            ^
make: **\* [/home/Software/caffe/.build_release/src/caffe/internal_thread.o] Error 1

**Comment by drnikolaev** [comment]
What cuDNN version do you use?

**Comment by haoyul** [comment]
I'm using CUDA 7.0

**Comment by haoyul** [comment]
I'm using cuDNN v4 Library for Linux.

**Comment by drnikolaev** [comment]
Please check cudnn.h file in your cuDNN distribution for this structure:

typedef enum{
    CUDNN_NOT_PROPAGATE_NAN  = 0,
    CUDNN_PROPAGATE_NAN      = 1,
} cudnnNanPropagation_t;

Is it there? If it is, then it seems like an environment issue.

**Comment by haoyul** [comment]
They are not in v4 cudnn.h. I downloaded the v5 cuDNN and yes they are there. 

Now "make all" passed that point but got tons of warnings saying:
At end of source: warning: routine is both "inline" and "noinline". 
For example: 
![screenshot - 05022016 - 02 55 57 pm](https://cloud.githubusercontent.com/assets/4164950/14964410/029a8bd2-1076-11e6-806a-966b8c1e548d.png)

And "make all" stopped again with following errors but seems they are not related to this topic. I'll fix them and see how things work. Do you have any idea what caused the above "inline..noinline.."warnings?

/usr/bin/ld: cannot find -lcblas
/usr/bin/ld: cannot find -latlas
collect2: error: ld returned 1 exit status

**Comment by drnikolaev** [comment]
As of warnings, please try CUDA 7.5. Also, you do need blas, please try 'sudo apt-get install libblas-dev'

**Comment by haoyul** [comment]
I have installed ATLAS

**Comment by haoyul** [comment]
I switched to openBlas and it didn't show that error again. I don't know the reason why ATLAS didn't work, but the files under /usr/lib/atlas-base/atlas folder are different with my another caffe working computer. Here the libblas.a and liblapack.a are in usr/lib.

**Comment by drnikolaev** [comment]
Forgot to ask: what branch are you using?

**Comment by haoyul** [comment]
I'm using the master branch.

Now it shows many google protobuf related errors like messages below, but I already installed everything listed in Caffe installation guide (http://caffe.berkeleyvision.org/install_apt.html). 

/home/Softwares/caffe/.build_release/lib/libcaffe-nv.so: undefined reference to `google::protobuf::io::CodedInputStream::BytesUntilTotalBytesLimit() const'
/home/Softwares/caffe/.build_release/lib/libcaffe-nv.so: undefined reference to `google::protobuf::io::CodedInputStream::ReadTagFallback(unsigned int)'
/home/Softwares/caffe/.build_release/lib/libcaffe-nv.so: undefined reference to `google::protobuf::internal::RepeatedPtrFieldBase::InternalExtend(int)'
/home/Softwares/caffe/.build_release/lib/libcaffe-nv.so: undefined reference to `google::protobuf::internal::ArenaStringPtr::AssignWithDefault(std::string const*, google::protobuf::internal::ArenaStringPtr)'
/home/Softwares/caffe/.build_release/lib/libcaffe-nv.so: undefined reference to `google::protobuf::io::CodedOutputStream::WriteLittleEndian64(unsigned long long)'
collect2: error: ld returned 1 exit status

**Comment by drnikolaev** [comment]
You might need to check this:
$ dpkg -s protobuf-compiler | grep -i version
Version: 2.5.0-9ubuntu1

What Ubuntu do you run?

**Comment by haoyul** [comment]
I'm running ubuntu 14.04 LTS and my version is also 
Version: 2.5.0-9ubuntu1
The problem seems refers to libcaffe-nv.so. I only have libcaffe.so in my computer.

**Comment by haoyul** [comment]
Update: 
I fixed the ATLAS errors and switched back from openBLAS to ATLAS because by using "cmake .." it stll shows couldn't find atlas .. related libraries. 

Now cmake works and all runtest also work fine. Only at the end it says " YOU HAVE 2 DISABLED TESTS". I have no idea what tests were disabled. But on my other caffe working computer, I saw this before too. 
I'll test my program to see if this Nvidia caffe is faster than the BVLC one. 

Again, thank you very much for your help!

**Comment by haoyul** [comment]
Hi Sergei,

My program was stopped by "error while loading shared libraries: libcaffe-nv.so.0.14: cannot open shared object file: No such file or directory". 
I checked my caffe/build/lib, it has libcaffe-nv.so -> libcaffe-nv.so.0.14 -> libcaffe-nv.so.14.5. So the symbolic link libcaffe-nv.so.0.14 is actually there.
I'm using Nsight and included library caffe-nv and it's path  ../caffe/build/lib in Cross G++ Linker.
I also tried creating new link like libcaffe.so -> libcaffe-nv.so.0.14 -> libcaffe-nv.so.14.5 because my working version use libcaffe.so. None of them can solve this error.

Do you have any suggestion?

**Comment by drnikolaev** [comment]
You may try to add LD_LIBRARY_PATH to Run(Debug) Configurations -> Environment 
Alternatively, you may add a file to /etc/ld.so.conf.d with /home/Software/caffe/build/lib line (just one line) and then call `sudo ldconfig`

**Comment by haoyul** [comment]
In Configurations -> Enviroment, it needs a Variable&Value pair, the values have quite a lot choices (e.g. build_files, build_project, build_type, etc). What should I set?

And in the second method, I saw there are already some .conf files in this folder. What filename should I use for my own new file?

**Comment by drnikolaev** [comment]
Hard to say. Try to build it with DEBUG=1 and debug it.

**Comment by koolkarni** [comment]
had same issues 
re did the following lines  to solve the issue

tar -zxf cudnn-7.0-linux-x64-v3.0-prod.tgz
cd cuda
sudo cp lib64/* /usr/local/cuda/lib64/
sudo cp include/cudnn.h /usr/local/cuda/include/

**Comment by koolkarni** [comment]
or you need to write these lines on top of your bashrc after that dont forget to run 
ldconfig as mentioned 

export PATH=$PATH:/usr/local/cuda-7.0/bin
export LD_LIBRARY_PATH=:/usr/local/cuda-7.0/lib64
Remember to run source ~/.bashrc after saving .bashrc and run ldconfig as root ($ sudo ldconfig)

**Comment by haoyul** [comment]
Hi koolkarni,
Which issue do you mean? 
I put the "export PATH/LD.." lines at the end of bashrc. Is there any difference?
