### ISSUE TITLE
complilation failed on Tegra X1

### ISSUE THREAD

**Issue by realentertain** [NVIDIA/caffe#139]
**nvidia@nvidia:~/caffe-nv$ cat Makefile.config | grep -v "#"**
USE_CUDNN := 1
CUDA_DIR := /usr/local/cuda
CUDA_ARCH := -gencode arch=compute_20,code=sm_20 \
                -gencode arch=compute_20,code=sm_21 \
                -gencode arch=compute_30,code=sm_30 \
                -gencode arch=compute_35,code=sm_35 \
                -gencode arch=compute_50,code=sm_50 \
                -gencode arch=compute_50,code=compute_50
BLAS := atlas
PYTHON_INCLUDE := /usr/include/python2.7 \
                /usr/lib/python2.7/dist-packages/numpy/core/include
PYTHON_LIB := /usr/lib
INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include /usr/include/hdf5/serial
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib /usr/lib/aarch64-linux-gnu/hdf5/serial
BUILD_DIR := build
DISTRIBUTE_DIR := distribute
TEST_GPUID := 0
Q ?= @
LIBRARY_NAME_SUFFIX := -nv

**nvidia@nvidia:~/caffe-nv$ make -j 4**
CXX src/caffe/util/gpu_memory.cpp
CXX src/caffe/util/blocking_queue.cpp
CXX src/caffe/util/db_lmdb.cpp
CXX src/caffe/util/cudnn.cpp
CXX src/caffe/util/io.cpp
CXX src/caffe/util/hdf5.cpp
/tmp/ccdoFisx.s: Assembler messages:
/tmp/ccdoFisx.s:1955: Error: unknown mnemonic `pause' --`pause'
/tmp/ccdoFisx.s:2395: Error: unknown mnemonic `pause' --`pause'
/tmp/ccdoFisx.s:3090: Error: unknown mnemonic `pause' --`pause'
/tmp/ccdoFisx.s:3529: Error: unknown mnemonic `pause' --`pause'
/tmp/ccdoFisx.s:3991: Error: unknown mnemonic `pause' --`pause'
/tmp/ccdoFisx.s:4380: Error: unknown mnemonic `pause' --`pause'
/tmp/ccdoFisx.s:4690: Error: unknown mnemonic `pause' --`pause'
/tmp/ccdoFisx.s:4808: Error: unknown mnemonic `pause' --`pause'
/tmp/ccdoFisx.s:5551: Error: unknown mnemonic `pause' --`pause'
/tmp/ccdoFisx.s:5934: Error: unknown mnemonic `pause' --`pause'
Makefile:579: recipe for target '/home/nvidia/caffe-nv/.build_release/src/caffe/util/gpu_memory.o' failed
make: **\* [/home/nvidia/caffe-nv/.build_release/src/caffe/util/gpu_memory.o] Error 1

**Comment by charlyng** [comment]
Hi @realentertain,

> nvidia@nvidia:~/caffe-nv$ make -j 4

Maybe you can try to make -j3 instead or refer to the following link for installation of caffe:
https://github.com/charlyng/Embedded-Deep-Learning/blob/master/Instructions%20for%20Jetson%20TX1.md
