### ISSUE TITLE
Unable to Compile NVIDIA/caffe on ppc64 on any of 0.14.* 

### ISSUE THREAD

**Issue by sathish249** [NVIDIA/caffe#140]
Unable to compile the NVIDIA caffe version. I keep getting the below error i tried moving to older version as well but the error remains same.  I git clone this github.com/NVIDIA/caffe
and compile it using Ubuntu14.04 default gcc ... but couldn't compile
Any help and what could be the issue... Is my OS version... compiler version or Platform?

```
/usr/local/cuda/bin/nvcc /home/ubuntu/sathish/caffe_nvidia/src/caffe/src/caffe/util/math_functions.cu -c -o /home/ubuntu/sathish/caffe_nvidia/src/caffe/build/src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_math_functions.cu.o -ccbin /usr/bin/cc -m64 -DCAFFE_VERSION=0.14.0-rc.3 -DUSE_LMDB -DUSE_LEVELDB -DUSE_CUDNN -DUSE_OPENCV -DGTEST_USE_OWN_TR1_TUPLE -Xcompiler ,\"-fPIC\",\"-Wall\",\"-Wno-sign-compare\",\"-Wno-uninitialized\",\"-O3\",\"-DNDEBUG\" -gencode arch=compute_37,code=sm_37 -Xcudafe --diag_suppress=cc_clobber_ignored -Xcudafe --diag_suppress=integer_sign_change -Xcudafe --diag_suppress=useless_using_declaration -Xcudafe --diag_suppress=set_but_not_used -Xcompiler -fPIC -DNVCC -I/usr/local/cuda/include -I/home/ubuntu/sathish/caffe_nvidia/src/caffe/src -I/home/ubuntu/sathish/caffe_nvidia/include -I/home/ubuntu/sathish/caffe_nvidia/src/caffe/build/include -I/usr/local/cuda/include -I/home/ubuntu/sathish/caffe_nvidia/include/opencv -I/usr/include -I/home/ubuntu/sathish/caffe_nvidia/src/caffe/include -I/home/ubuntu/sathish/caffe_nvidia/src/caffe/build -I/home/ubuntu/sathish/caffe_nvidia/src/caffe/3rdparty
/home/ubuntu/sathish/caffe_nvidia/src/caffe/src/caffe/util/math_functions.cu(393): error: caffe_gpu_hamming_distance is not a template
/home/ubuntu/sathish/caffe_nvidia/src/caffe/src/caffe/util/math_functions.cu(407): error: caffe_gpu_hamming_distance is not a template
2 errors detected in the compilation of "/tmp/tmpxft_00006a4b_00000000-7_math_functions.cpp1.ii".
-- Removing /home/ubuntu/sathish/caffe_nvidia/src/caffe/build/src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_math_functions.cu.o
/usr/bin/cmake -E remove /home/ubuntu/sathish/caffe_nvidia/src/caffe/build/src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_math_functions.cu.o
CMake Error at cuda_compile_generated_math_functions.cu.o.cmake:264 (message):
  Error generating file
  /home/ubuntu/sathish/caffe_nvidia/src/caffe/build/src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_math_functions.cu.o

make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_math_functions.cu.o] Error 1
make[2]: Leaving directory `/home/ubuntu/sathish/caffe_nvidia/src/caffe/.build_release'
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make[1]: Leaving directory `/home/ubuntu/sathish/caffe_nvidia/src/caffe/.build_release'
make: *** [all] Error 2
```

**Comment by sathish249** [comment]
i tried to compile with USE_CUDNN  cudnn version 4.0 along with CUDA-7.5

**Comment by sathish249** [comment]
gcc version 4.8.4

**Comment by drnikolaev** [comment]
Could you try cuDNN v5 please?

**Comment by tyrosathish** [comment]
i couldn't get the ppc64 cuDNN v5 version from the NVIDIA cuDNN site. Looks like its broken for ppc64.
We have tried downloading from multiple user-id for all the id. The ppc64 version of cuDNN v5 total
downloaded file size is very less compared to the x86 cuDNN v5.

**Comment by tyrosathish** [comment]
untar it-self was failing... Saying the tar is not proper.

**Comment by sathish249** [comment]
$ ls -lrt
total 97980
-rw-rw-r-- 1 deepali deepali 85877098 May 13 00:09 cudnn-7.0-linux-ppc64le-v4.0-prod.tgz
-rw-rw-r-- 1 deepali deepali 14450688 May 13 00:09 cudnn-7.5-linux-ppc64le-v5.0-rc.tgz

$ tar -xvzf cudnn-7.5-linux-ppc64le-v5.0-rc.tgz
cuda/targets/ppc64le-linux/include/cudnn.h
cuda/targets/ppc64le-linux/lib/libcudnn.so
cuda/targets/ppc64le-linux/lib/libcudnn.so.5
cuda/targets/ppc64le-linux/lib/libcudnn.so.5.0.4

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

**Comment by sathish249** [comment]
From another threads... issues section in BVLC caffe....cuDNN v5 is not yet supported on Caffe
they are waiting for fix.

**Comment by drnikolaev** [comment]
Can't reproduce this. Please check the version in your cudnn.h. Mine shows
#define CUDNN_MAJOR      4
#define CUDNN_MINOR      0
#define CUDNN_PATCHLEVEL 7

**Comment by junlizhang** [comment]
I've compile nvida caffe sucessfully on RHEL7.3 ppc64le platform. You can foud the details in https://github.com/NVIDIA/caffe/issues/233
