### ISSUE TITLE
 while running pycaffe -j8; I am getting following error 

### ISSUE THREAD

**Issue by koolkarni** [NVIDIA/caffe#142]
while running pycaffe -j8;

getting this error

^
./include/caffe/util/cudnn.hpp:15:28: note: in definition of macro ‘CUDNN_CHECK’
cudnnStatus_t status = condition; \
^
./include/caffe/util/cudnn.hpp:138:75: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
pad_h, pad_w, stride_h, stride_w));
^
./include/caffe/util/cudnn.hpp:15:28: note: in definition of macro ‘CUDNN_CHECK’
cudnnStatus_t status = condition; \
^
make: **\* [/home/ubuntu/nv-caffe/.build_release/src/caffe/net.o] Error 1

**Comment by drnikolaev** [comment]
Could you paste your Makefile.config here? And what cuDNN version are you using?
