### ISSUE TITLE
fp16 inference accuracy lower than expected

### ISSUE THREAD

**Issue by tryckfel** [NVIDIA/caffe#143]
I have trained a model using the regular Caffe branch, with 32 bit floats. Now I'm comparing the accuracy of the model on that branch, and on the experimental fp16 branch. Inference using 32 bit floats on my desktop computer gives me an accuracy of around 90%. Switching over to the experimental fp16 branch on the desktop makes the accuracy drop to 40%. The desktop computer does not support calculations with the half datatype, so I was expecting to get this kind of outcome. However, running the experimental fp16branch on my Jetson TX1 (which fully supports the half datatype) only gives 73% accuracy. 

My impression was that the accuracy was not supposed to change that dramatically when switching from 32 to 16 bit. Do you know if this is to be expected? Do you have to use 16 bit floats for training for it to be possible to keep the accuracy up? If so, are there any plans of implementing the training phase in the experimental fp16 branch?

**Comment by vesvis** [comment]
Did you find an answer to your question?

**Comment by drnikolaev** [comment]
Please try new 0.16 release
