### ISSUE TITLE
How to accelerate 3D convolution by CUDNN V5

### ISSUE THREAD

**Issue by philokey** [NVIDIA/caffe#147]
I use TITAN Black, the deep learning framework is caffe. I upgrade my CUDNN to V5, but it seem that my 3D convolution does not faster than before.

By the way, I use cudnnSetConvolutionNdDescriptor to implement the 3D convolution.

What should I do to accelerate 3D convolution by CUDNN V5?

**Comment by drnikolaev** [comment]
You may try new release with CuDNN v6
