### ISSUE TITLE
CUDNN detection at runtime

### ISSUE THREAD

**Issue by crohkohl** [NVIDIA/caffe#17]
I develop on different machines with different compute capabilities.
Would it be possible to switch to a run-time detection scheme instead of a compile-time detection which is implemented right now? Right now I always have to compile two versions which is quite cumbersome. What do you think?

**Comment by lukeyeager** [comment]
If you're using Make, you can just compile for all compute architectures.
https://github.com/NVIDIA/caffe/blob/v0.12.2/Makefile.config.example#L20-L27

If you're using CMake, it does try to get clever and compile for only the correct architectures. I guess you could walk through the CMake code to try to disable that.

**Comment by crohkohl** [comment]
okay, thanks for the tip!
