### ISSUE TITLE
cub not found in src

### ISSUE THREAD

**Issue by Greendogo** [NVIDIA/caffe#177]
By what process should cub's source be added to caffe/src?
I had to add it manually from here: https://github.com/NVlabs/cub/tree/1.5.2/cub

**Comment by drnikolaev** [comment]
Either make or cmake invoke script `3rdparty/getCUB.sh`. It gets five `.cuh` files.

**Comment by Greendogo** [comment]
Is this usually automated in the installation process?  I took a roundabout way of compiling Caffe, so maybe it didn't happen like it was supposed to...

**Comment by drnikolaev** [comment]
Yes, you should use make or cmake. If you use something else make sure you execute `3rdparty/getCUB.sh 1.5.2` to get CUB files.

**Comment by drnikolaev** [comment]
comes with 0.16
