### ISSUE TITLE
which branch  should I choose to use fp16 on TX1?

### ISSUE THREAD

**Issue by DLDarwin** [NVIDIA/caffe#187]
I want to know the latest branch of fp16, as I did not see the specific use of guidance. Can someone give a description ?

**Comment by mastrcheif** [comment]
Try this tutorial:
http://leotam.github.io/general/2016/05/05/EmbeddedVision.html

**Comment by pooyadavoodi** [comment]
If you only want Inference, you can use https://github.com/NVIDIA/caffe/tree/experimental/fp16

**Comment by VincentChong123** [comment]
As for expected fp16 performance for Alexnet and Googlenet, refer paper
below
https://www.nvidia.com/content/tegra/embedded-systems/pdf/jetson_tx1_whitepaper.pdf

**Comment by DLDarwin** [comment]
@pooyadavoodi ,    as you described, this  fp16 version is suitable for Inference. Do you have any suggestions  for training?

**Comment by pooyadavoodi** [comment]
FP16 training is still in development.

**Comment by drnikolaev** [comment]
0.16 is live
