### ISSUE TITLE
Error calling caffe.set_gpu() while gpu is used

### ISSUE THREAD

**Issue by engharat** [NVIDIA/caffe#189]
Hi all,
I just moved from cuda 7.5 to cuda 8.0. (cudnn is 5)
On cuda 7.5 I used without any problem caffe.set_gpu() python command on a GPU when this GPU is running a caffe train ( there is some GPU memory unoccupied).
With cuda 8.0 If I open a python console and I execute caffe.set_gpu() command while the GPU is training I get the cuda memory error:
`F0708 18:42:34.726313 16266 gpu_memory.cpp:146] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
**\* Check failure stack trace: ***
Could you confirm this issue?

**Comment by engharat** [comment]
Still I cannot fix the problem, and it is not about cuda 8.0: I revert to 7.5.
The only two  things that are changed are cudnn (from 4 to 5) and the Nvidia drivers (354 to 362 - the one linked with cuda 8.0).
Anyway, the problem is present even with DIGITS classify_one (while training):

`Error code -6
F0714 21:28:53.351652 15904 gpu_memory.cpp:68] Check failed: initialized_ Create GPUMemory::Scope to initialize Memory Manager`

**Comment by drnikolaev** [comment]
@engharat 0.16 release fixed that and added `set_devices` for multiGPU mode
