### ISSUE TITLE
.build_release/test/test_all.testbin: error while loading shared libraries: libhdf5.so.10: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by dbl001** [NVIDIA/caffe#19]
Hi,

I'm running on Ubuntu 14.04 LTS.

I am able to build Caffe, however, I get an error invoking 'make runtest':
```
ubuntu@ip-10-0-1-51:~/caffe$ make runtest
.build_release/tools/caffe
caffe: command line brew
usage: caffe <command> <args>

commands:
  train           train or finetune a model
  test            score a model
  device_query    show GPU diagnostic information
  time            benchmark model execution time

  Flags from /home/ubuntu/caffe/tools/caffe.cpp:
    -gpu (Run in GPU mode on given device ID.) type: int32 default: -1
    -iterations (The number of iterations to run.) type: int32 default: 50
    -model (The model definition protocol buffer text file..) type: string
      default: ""
    -snapshot (Optional; the snapshot solver state to resume training.)
      type: string default: ""
    -solver (The solver definition protocol buffer text file.) type: string
      default: ""
    -weights (Optional; the pretrained weights to initialize finetuning. Cannot
      be set simultaneously with snapshot.) type: string default: ""
.build_release/test/test_all.testbin 0 --gtest_shuffle 
.build_release/test/test_all.testbin: error while loading shared libraries: libhdf5.so.10: cannot open shared object file: No such file or directory
make: *** [runtest] Error 127
ubuntu@ip-10-0-1-51:~/caffe$ 
```
This appears to be an issue in the BVLC thread as well:

https://github.com/BVLC/caffe/issues/1463

**Comment by andrusiak** [comment]
I had the same problem with Caffe which I solved by adding ANACONDA/lib* path to LD_LIBRARY_PATH in ~.bashrc file and it fixed the issue.

export LD_LIBRARY_PATH="/usr/local/cuda/lib64"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/home/ubuntu/anaconda/lib"

**Comment by lukeyeager** [comment]
Closing. Let me know if you still can't resolve the issue after looking at @andrusiak's suggestion or https://github.com/BVLC/caffe/issues/1463.

**Comment by lucianainpa** [comment]
HI, I have a problem with:
libhdf5_fortran.so.10 cannot open shared object file: No such file or directory

Help, please...

**Comment by lijianqing317** [comment]
I solved by adding anaconda/lib path to LD_LIBRARY_PATH in ~.bashrc file and it fixed the issue.
but I didn't understand why I didn't solved by adding anaconda/lib path to LD_LIBRARY_PATH in etc/profile file .
