### ISSUE TITLE
cudnn v5 and fp16

### ISSUE THREAD

**Issue by lbin** [NVIDIA/caffe#195]
In branch fp16, I could compile caffe_fp16 but could not run it

I got this error:

F0712 18:02:11.243198 18233 cudnn_conv_layer.cpp:123] Check failed: status == CUDNN_STATUS_SUCCESS (9 vs. 0)  CUDNN_STATUS_NOT_SUPPORTED
**\* Check failure stack trace: ***
    @     0x7f4a91764daa  (unknown)
    @     0x7f4a91764ce4  (unknown)
    @     0x7f4a917646e6  (unknown)
    @     0x7f4a91767687  (unknown)
    @     0x7f4a91e71b4a  caffe::CuDNNConvolutionLayer<>::Reshape()
    @     0x7f4a91de2eca  caffe::Net<>::Init()
    @     0x7f4a91de4558  caffe::Net<>::Net()
    @           0x4075d1  time()
    @           0x404f9d  main
    @     0x7f4a904c5f45  (unknown)
    @           0x40571f  (unknown)
    @              (nil)  (unknown)
[1]    18233 abort (core dumped)  ./build/tools/caffe_fp16 time --model=models/bvlc_googlenet/deploy.prototxt 

Could anyone help me to fix this?

**Comment by thatguymike** [comment]
Did you compile for native fp16 without HW that can support it?

**Comment by lbin** [comment]
I compiled on  GTX1080

**Comment by borisfom** [comment]
@lbin : you still need to have CUDA 8.0 to generate right CUDA code for it.

**Comment by lbin** [comment]
Thanks @thatguymike  @borisfom, It's OK now.

**Comment by DLDarwin** [comment]
@lbin I met the same problem, can you explain how to solve this problem?
