### ISSUE TITLE
Check failed: initialized_ Create GPUMemory::Scope to initialize Memory Manager

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/caffe#196]
> Hi guys,
> I changed from nvcaffe 015 to nvcaffe016, cuda 7.5 to cuda 8.0, and drivers from 354 to 362 (the one linked with cuda 8.0), cudnn 4 to 5.
> I got a bunch of problems, so I reverted back to nvcaffe 015 (15.7) cuda 7.5, still keeping the 362 driver and the cudnn 5.
> The problem is that I get this strange error when doing classify_one with DIGITS:
> `Error code -6 F0714 21:28:53.351652 15904 gpu_memory.cpp:68] Check failed: initialized_ Create GPUMemory::Scope to initialize Memory Manager`
> the problem happens when I run the classify_one on a training network. It seems like it cannot allocate memory if still used by the training (but plenty of GPU RAM available)
> any idea?
> @engharat https://github.com/NVIDIA/DIGITS/issues/907

**Comment by lukeyeager** [comment]
That configuration should work.

Do you have more than 1 GPU? Are all the GPUs busy with training? Do you get the error when you try to do inference and you're **not** simultaneously training a model?

**Comment by engharat** [comment]
I have two GPUs and they are both working each on a training via DIGITS (caffenet network). Both of them have more than 2 GB free.  I will retry to do the inference when I will finish the training, I'm not 100% sure.

**Comment by engharat** [comment]
Okey if one GPU is not running any training then the inference goes successfully.  The problem happens when the GPUs are both working.

**Comment by lukeyeager** [comment]
When all GPUs are in use, DIGITS kicks the workload to the CPU. So it's possible we have a bug when running on the CPU for a GPU build. @NVIDIA/caffe team - can you verify?

**Comment by flx42** [comment]
AFAIK, even if the training is set to CPU mode, some GPU memory will still be used. See:
https://github.com/BVLC/caffe/issues/4472

I don't think we have that fixed in our fork, correct me if I'm wrong.

**Comment by engharat** [comment]
but still the problem is not related simply to the available GPU memory: I've done the test with 2gb of free GPU memory, and the single image inference does not consume more than 100mb of gpu ram.

**Comment by pooyadavoodi** [comment]
It's true that we use some amount of GPU memory even when solver mode is CPU. This amount increases with the batch size. 

I don't understand why 2GB of free memory is not enough.
Could you check when training is off, how much GPU memory does the inference use?

**Comment by engharat** [comment]
I checked some days ago and it was in the order of 100mb more or less, it is a simple 227x227 image.
I think it is not a matter of GPU memory available, it seems more of "initializing-something-failed" sort of stuff to me.

**Comment by lukeyeager** [comment]
Try this:

``` py
import caffe
caffe.set_mode_cpu()
caffe.Net(
    'models/bvlc_reference_caffenet/deploy.prototxt',
    'models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel',
    caffe.TEST)
```

You'll get this error:

``` sh
F0727 12:56:05.614255 16620 gpu_memory.cpp:68] Check failed: initialized_ Create GPUMemory::Scope to initialize Memory Manager
*** Check failure stack trace: ***
Aborted (core dumped)
```

**Comment by lukeyeager** [comment]
Closed by https://github.com/NVIDIA/caffe/pull/200.
