### ISSUE TITLE
using detectnet_transform_layer purely for data augmentation 

### ISSUE THREAD

**Issue by amarshah** [NVIDIA/caffe#197]
I am trying to use this layer purely to data augment my images in a more sophisticated way than the Transform layer offers (e.g. hue, saturation, arbitrary rotation).

I do not want to use the DetectNet architecture of gridding up the image and classifying each patch. Is there a simple way to use this layer for my goal? It is unclear how the detectnet_groundtruth_param set should be set.

**Comment by gheinrich** [comment]
Hello @amarshah this layer currently serves two purposes: that of doing data augmentation and that of transforming DetectNet labels. For the time being it is difficult to extract just the data augmentation part so you will need to provide a DetectNet-formatted label tensor (and redirect the coverage output to a `Silence` layer if you don't need it). A closer look at the code might help you understand if this isn't clear enough. Thanks!
