### ISSUE TITLE
run fp16 version on tesla M40

### ISSUE THREAD

**Issue by DLDarwin** [NVIDIA/caffe#198]
recently,  I tried to  run caffe  fp16 version on tesla M40, the following error occurred:

*_I0722 12:35:00.432457  3947 layer_factory.hpp:76] Creating layer data
I0722 12:35:00.432528  3947 net.cpp:110] Creating Layer data
I0722 12:35:00.432549  3947 net.cpp:433] data -> data
I0722 12:35:00.432585  3947 net.cpp:433] data -> label
I0722 12:35:00.432626  3947 image_data_layer.cpp:37] Opening file /ssd/imagenet/val.txt
I0722 12:35:00.456975  3947 image_data_layer.cpp:52] A total of 50000 images.
I0722 12:35:00.458665  3947 image_data_layer.cpp:79] output data size: 50,3,227,227
I0722 12:35:00.487819  3947 net.cpp:155] Setting up data
I0722 12:35:00.487895  3947 net.cpp:163] Top shape: 50 3 227 227 (7729350)
I0722 12:35:00.487911  3947 net.cpp:163] Top shape: 50 (50)
I0722 12:35:00.487929  3947 layer_factory.hpp:76] Creating layer label_data_1_split
I0722 12:35:00.487962  3947 net.cpp:110] Creating Layer label_data_1_split
I0722 12:35:00.487982  3947 net.cpp:477] label_data_1_split <- label
I0722 12:35:00.488005  3947 net.cpp:433] label_data_1_split -> label_data_1_split_0
I0722 12:35:00.488029  3947 net.cpp:433] label_data_1_split -> label_data_1_split_1
I0722 12:35:00.488229  3947 net.cpp:155] Setting up label_data_1_split
I0722 12:35:00.488252  3947 net.cpp:163] Top shape: 50 (50)
I0722 12:35:00.488265  3947 net.cpp:163] Top shape: 50 (50)
I0722 12:35:00.488276  3947 layer_factory.hpp:76] Creating layer conv1
I0722 12:35:00.488301  3947 net.cpp:110] Creating Layer conv1
I0722 12:35:00.488315  3947 net.cpp:477] conv1 <- data
I0722 12:35:00.488330  3947 net.cpp:433] conv1 -> conv1
F0722 12:35:00.492346  3947 cudnn_conv_layer.cpp:138] Check failed: status == CUDNN_STATUS_SUCCESS (9 vs. 0)  CUDNN_STATUS_NOT_SUPPORTED
*_\* Check failure stack trace: ***
    @     0x7f23710bfdaa  (unknown)
    @     0x7f23710bfce4  (unknown)
    @     0x7f23710bf6e6  (unknown)
    @     0x7f23710c2687  (unknown)
    @     0x7f23717b32a2  caffe::CuDNNConvolutionLayer<>::Reshape()
    @     0x7f237184baaa  caffe::Net<>::Init()
    @     0x7f237184d138  caffe::Net<>::Net()
    @           0x406295  test()
    @           0x404cca  main
    @     0x7f23705d1f45  (unknown)
    @           0x4053b3  (unknown)
    @              (nil)  (unknown)
./test.sh: line 1:  3947 Aborted   **

However, the fp32 version runs normally  on tesla M40.  In addition, caffe fp16 version that  on TX1  works as well.  I want to clearly know the support of the graphics model?  It makes me a little confused.

**Comment by DLDarwin** [comment]
Can someone help??

**Comment by DLDarwin** [comment]
@lukeyeager  I want to confirm that this fp16 version only  supports  arm and pascal architecture？？

**Comment by thatguymike** [comment]
Native fp16 is only supported on Pascal and Tegra X1.  M40 should work in pseudo fp16 mode (fp16 IO and fp32 compute).  However, note that the experimental fp16 branch is currently for inference only.

**Comment by DLDarwin** [comment]
@thatguymike   Thank you for  your reply
