### ISSUE TITLE
Any plan to sync fp16 with latest Caffe?

### ISSUE THREAD

**Issue by jamesrxian** [NVIDIA/caffe#202]
Hi,

Is there any plan to sync experiment/fp16 branch with the latest Caffe? I'm trying to run inference on [FCN](https://github.com/shelhamer/fcn.berkeleyvision.org) but the layer architecture is not compatible.

```
Error parsing text-format caffe.NetParameter: 5:15: Message type "caffe.LayerParameter" has no field named "input_param".
WARNING: Logging before InitGoogleLogging() is written to STDERR
```

https://github.com/NVIDIA/caffe/issues/128

**Comment by bcaine** [comment]
Bump. Would also like to test FP16 on the TX1, but need the latest caffe version.

**Comment by drnikolaev** [comment]
@ranxian @bcaine please have a look at 0.16 release
