### ISSUE TITLE
GTX970 accuracy grows during training, GTX1070 accuracy stay constant.

### ISSUE THREAD

**Issue by Smorodov** [NVIDIA/caffe#203]
I've installed gtx1070 GPU, additionally to gtx970 card.

digits 4.1 dev, caffe 0.16, CUDA 8.0, CUDNN v5, nvidia driver 367.35, ubuntu 14.04 LTS.

Makefile.config :
[Makefile.config.tar.gz](https://github.com/NVIDIA/caffe/files/394776/Makefile.config.tar.gz)

And tested them both with MNIST DS, and LeNET network configuration.

For GTX 970 training goes ok, and accuracy increases, loss reducing.
![gtx970_training](https://cloud.githubusercontent.com/assets/1816461/17308861/b3d3fe9a-5844-11e6-972f-f876195fcc1a.png)

For GTX 1070 loss and accuracy remains the same during all 30 epochs.
![gtx 1070 training](https://cloud.githubusercontent.com/assets/1816461/17308873/b99b0ea4-5844-11e6-9fd5-9299f764fd7c.png)

UPD: looks like with NCCL turned on it works.

I have 2 GPU installed in system, I tryed single GPU training first, and without NCCL , gtx1070 GPU (primary in my system) did wrong training, while gtx 970 (secondary) worked fine.

With NCCL turned on, both cards works fine, in single- and in multi-GPU modes.

Moved from here: https://github.com/NVIDIA/DIGITS/issues/943

**Comment by thatguymike** [comment]
Does Caffe 0.15 exhibit the same issue?  0.16 is preproduction and hasn't had the same level of testing and development is not complete.

**Comment by Smorodov** [comment]
Just tested it, in 0.15 it works fine.
