### ISSUE TITLE
Error on Centos with caffe 0.15 install --> "error: ‘UINT8_MAX’ was not declared in this scope" 

### ISSUE THREAD

**Issue by GeorgeStorm** [NVIDIA/caffe#207]
Hi,
As above, trying to install caffe 0.15 in order to go through the kitti detection tutorial and getting this error with the caffe/src/caffe/layers/detectnet_transform_layer.cpp file.

Was following this guide:
https://gist.github.com/lukeyeager/ba948f1d56e4ab407874

Which worked for the default branch of caffe but not this one.
Any ideas?

Thanks

**Comment by fpertl** [comment]
I wish I remembered were I saw this, fix so I could give credit, but what worked for me on CentOS 7 with gcc 4.8 was editing the CMakeLists.txt file.  Somewhere around line 61 add the limits macros:

```
if(UNIX OR APPLE)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC -Wall")
    add_definitions(-D__STDC_LIMIT_MACROS)
endif()
```

**Comment by GeorgeStorm** [comment]
Thanks that solved the problem!

**Comment by IamMegatron2025** [comment]
@GeorgeStorm @fpertl  This method does not work for me. Do you have any else solutions?

**Comment by drnikolaev** [comment]
@IvyGongoogle Have you tried
#include <stdint.h>
?
