### ISSUE TITLE
Erro, can not find the file or directory. "cub/util_allocator.cuh"

### ISSUE THREAD

**Issue by m5061125** [NVIDIA/caffe#208]
Hello, I have a issue when make the NV caffe, it seems that can't find a file.
So is there anyone can kindly tell me how to solve it, thanks a lot.

~/caffe$ sudo make pycaffe
CXX src/caffe/util/gpu_memory.cpp
src/caffe/util/gpu_memory.cpp:7:34: Error, can not find the file or directory.
 #include "cub/util_allocator.cuh".

**Comment by lukeyeager** [comment]
First of all, never use `sudo make` unless it's for `sudo make install`.

It looks like you're using the raw Makefile build - why? I suggest using these instructions to build with CMake:
https://github.com/NVIDIA/DIGITS/blob/digits-4.0/docs/BuildCaffe.md#build

**Comment by m5061125** [comment]
Thanks, lukeyeager. I successfully build it using cmake according to your suggest.
But I have another problem regarding the version of NV caffe for Digits4.0.
I upgrade the Digits from 3.0 to 4.0, but the NV caffe is still 0.14.5, while the object-detection example
of Digits 4.0 need caffe 0.15.1 or later. So could pls let me know how upgrade NV caffe, thanks.

**Comment by lukeyeager** [comment]
Are you building from source or using deb packages? Sounds like you're trying both?

The latest released Caffe packages are 0.15.9, as you can see here:
http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64

To upgrade all packages:

``` sh
sudo apt-get update
sudo apt-get upgrade
```

That should update all the Caffe packages, and also the DIGITS package, if you haven't done it already. You might also need to restart your DIGITS server if only Caffe got updated and not DIGITS:

``` sh
# https://github.com/NVIDIA/DIGITS/blob/digits-4.0/docs/UbuntuInstall.md#troubleshooting
sudo stop nvidia-digits-server
sudo start nvidia-digits-server
```

**Comment by m5061125** [comment]
Thanks a lot, Luk. BTW, where can I download the release version of latest Digits package, thanks.

**Comment by m5061125** [comment]
Sorry to bother, it under the same page, thank Luk, I already can successfully run the object-detection example now.
