### ISSUE TITLE
Cannot do multiple gpu train

### ISSUE THREAD

**Issue by xuanzhaopeng** [NVIDIA/caffe#212]
I have 4 GPU K520, in EC2 g2.x8large, (installed nccl, test pass)

 ./tools/caffe train --solver vgg/vgg_solver.prototxt -gpu=1,3 

When I train it , it show :
test_iter: 10
test_interval: 100
base_lr: 0.001
display: 10
max_iter: 160000
lr_policy: "step"
gamma: 0.1
momentum: 0.9
weight_decay: 0.0005
stepsize: 80000
snapshot: 50000
snapshot_prefix: "vgg/output/"
solver_mode: GPU
**device_id: 1**
test_initialization: true

But I never define this "device_id" in solver ... so finally it only train on 1 GPU...

Thanks

**Comment by lukeyeager** [comment]
Can you just remove the `device_id: 1` in your solver? The command-line flag is supposed to override whatever you specified in your solver anyway.
