### ISSUE TITLE
Can't make all

### ISSUE THREAD

**Issue by cfsantos** [NVIDIA/caffe#218]
I am trying to install NVIDIA version of caffe but it's not making. The orginal caffe version compiles ok.

This is the problem:

PROTOC src/caffe/proto/caffe.proto
CXX .build_release/src/caffe/proto/caffe.pb.cc
CXX src/caffe/blob.cpp
CXX src/caffe/net.cpp
CXX src/caffe/syncedmem.cpp
CXX src/caffe/layer_factory.cpp
CXX src/caffe/util/blocking_queue.cpp
CXX src/caffe/util/signal_handler.cpp
CXX src/caffe/util/insert_splits.cpp
CXX src/caffe/util/gpu_memory.cpp
src/caffe/util/gpu_memory.cpp:7:34: fatal error: cub/util_allocator.cuh: no such file or directory
 #include "cub/util_allocator.cuh"
                                  ^
compilation terminated.
make: **\* [.build_release/src/caffe/util/gpu_memory.o] Error 1

**Comment by gheinrich** [comment]
Hello, are you using `cmake` as recommended [there](https://github.com/NVIDIA/DIGITS/blob/v4.0.0/docs/BuildCaffe.md)?

**Comment by cfsantos** [comment]
Still having an error:

[  0%] Running C++/Python protocol buffer compiler on /home/claudio/nvidia/caffe/src/caffe/proto/caffe.proto
Scanning dependencies of target proto
[  1%] Building CXX object src/caffe/CMakeFiles/proto.dir/**/**/include/caffe/proto/caffe.pb.cc.o
Linking CXX static library ../../lib/libproto.a
[  1%] Built target proto
[  1%] [  1%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/solvers/./cuda_compile_generated_nesterov_solver.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_im2col.cu.o
[  2%] [  2%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_absval_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_math_functions.cu.o
/home/claudio/nvidia/caffe/src/caffe/util/math_functions.cu(178): error: kernel launches from templates are not allowed in system files

1 error detected in the compilation of "/tmp/tmpxft_00000df1_00000000-4_math_functions.cpp4.ii".
CMake Error at cuda_compile_generated_math_functions.cu.o.cmake:264 (message):
  Error generating file
  /home/claudio/nvidia/caffe/build/src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_math_functions.cu.o

make[2]: **\* [src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_math_functions.cu.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
make[1]: **\* [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: **\* [all] Error 2

**Comment by lukeyeager** [comment]
What version of CUDA do you have?

**Comment by cfsantos** [comment]
7.5

**Comment by lukeyeager** [comment]
A little googling led me here:
https://github.com/BVLC/caffe/issues/337

Are you using a weird compiler?

**Comment by cfsantos** [comment]
I am using g++ 4.8.
As in the link you said, I tried to use version 4.6 but it didn't work too
