### ISSUE TITLE
this fork's data read is very slow

### ISSUE THREAD

**Issue by erogol** [NVIDIA/caffe#22]
I was comparing this fork versus the original one with " caffe time " on CIFAR example. It seems this fork is faster in CuDNNv3. However, when it comes to use normal data, it takes minutes to to see any output on the log whereas original caffe goes wildly fast.

**Comment by lukeyeager** [comment]
This should be much faster in the `caffe-0.15` branch because of https://github.com/NVIDIA/caffe/pull/162.
