### ISSUE TITLE
MAX_BOXES in clustering.py

### ISSUE THREAD

**Issue by sherifshehata** [NVIDIA/caffe#228]
The clustering layer for object detection assumes that the number of detected box doesn't exceed MAX_BOXES  (which is 50). This causes an error for me while training because i got more boxes.

**Comment by sherifshehata** [comment]
I think that getting many boxes is something weird, so maybe this limit (50) is not wrong

**Comment by gheinrich** [comment]
Thanks for the feedback. I think we should be able to specify the limit from .prototxt with the current default at `50` and let users decide what the reasonable limit is. Would that address your comment?

**Comment by sherifshehata** [comment]
I think yes. I just changed the number in the python file and it works for me.

**Comment by sherifshehata** [comment]
I think at least it should handle the case when the number of boxes if bigger, maybe by taking random boxes. Because now it fails
