### ISSUE TITLE
No GPU selected without -gpu flag

### ISSUE THREAD

**Issue by danst18** [NVIDIA/caffe#23]
The CPU is selected when the -gpu flag is not used in the command line. I solved the issue by adding [this line](https://github.com/BVLC/caffe/blob/master/tools/caffe.cpp#L170), as in caffe's original code.

**Comment by lukeyeager** [comment]
The fix for this is included in v0.14.

https://github.com/NVIDIA/caffe/blob/v0.14.2/tools/caffe.cpp#L177-L180
