### ISSUE TITLE
[EDIT] Is consecutive in-place layers not supported?

### ISSUE THREAD

**Issue by Namnamseo** [NVIDIA/caffe#230]
UPDATE: I thought that in-place Pooling layers don't work. But it's not; it works well. Now I suspect consecutive in-place layers don't work.

---

I posted [this](https://groups.google.com/forum/#!topic/caffe-users/0_rIeUUkPPY) into `caffe-users` group.
For TL;DRs, I tried to train a network with in-place TanH and Pooling layer after each Convolution layers.
For example,
conv1 reads from blob `data` and outputs to blob `conv1`
act1 reads from blob `conv1` and outputs **in-place** to blob `conv1`
pool1 reads from blob `conv1` and outputs **in-place** to blob `conv1`

Caffe showed errors like:

```
Check failed: K_ == new_K (36864 vs. 9216) Input size incompatible with inner product parameters.
```

But I couldn't find anything wrong with the inner product layer or even the whole network.
After a long happy debugging, I found out that consecutive in-place layers (like described above) don't work.

Is this intended? If so, then it would be much better if Caffe warns about unsupported consecutive in-place layers.

Caffe version is 0.15.13 (clone of master branch in September 2, 2016).
Thank you.

**Comment by drnikolaev** [comment]
@Namnamseo can you check v0.16 please?
