### ISSUE TITLE
caffe 0.15 install "error: ‘UINT8_MAX’ was not declared in this scope"

### ISSUE THREAD

**Issue by xxw345** [NVIDIA/caffe#233]
Red Hat Enterprise Linux Server release 6.8 (Santiago), cluster environment.

COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/gcc/4.9.3/libexec/gcc/x86_64-unknown-linux-gnu/4.9.3/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ../configure --disable-multilib --enable-shared --prefix=/usr/local/gcc/4.9.3
Thread model: posix
gcc version 4.9.3 (GCC)

src/caffe/layers/detectnet_transform_layer.cpp: In member function ‘void caffe::DetectNetTransformationLayer<Dtype>::retrieveMeanImage(cv::Size)’:  
src/caffe/layers/detectnet_transform_layer.cpp:87:23: error: ‘UINT8_MAX’ was not declared in this scope  
   data_mean_ /= Dtype(UINT8_MAX);  
                       ^  
src/caffe/layers/detectnet_transform_layer.cpp: In member function ‘void caffe::DetectNetTransformationLayer<Dtype>::retrieveMeanChannels()’:  
src/caffe/layers/detectnet_transform_layer.cpp:95:56: error: ‘UINT8_MAX’ was not declared in this scope  
       mean_values_.fill(t_param_.mean_value(0) / Dtype(UINT8_MAX));  
                                                        ^  
src/caffe/layers/detectnet_transform_layer.cpp: In member function ‘void caffe::DetectNetTransformationLayer<Dtype>::transform(const Mat3v&, const std::vectorcaffe::BboxLabel_<Dtype >&, caffe::DetectNetTransformationLayer<Dtype>::Mat3v_, Dt
ype_)’:  
src/caffe/layers/detectnet_transform_layer.cpp:347:21: error: ‘UINT8_MAX’ was not declared in this scope  
   img_temp /= Dtype(UINT8_MAX);  
                     ^  
src/caffe/layers/detectnet_transform_layer.cpp: In member function ‘float caffe::DetectNetTransformationLayer<Dtype>::augmentation_desaturation(const Mat3v&, caffe::DetectNetTransformationLayer<Dtype>::Mat3v_)’:  
src/caffe/layers/detectnet_transform_layer.cpp:761:47: error: ‘UINT8_MAX’ was not declared in this scope  
   if (doDesaturate && (saturation < 1.0 - 1.0/UINT8_MAX)) {  
                                               ^  
make: *_\* [.build_release/src/caffe/layers/detectnet_transform_layer.o] Error 1  
make: **\* Waiting for unfinished jobs....

**Comment by xxw345** [comment]
I did something to skip this error and let 'make all' finish.

I first add #include<cstdint> in math_fuctions.hpp. Since I saw somewhere said cstdint.h is c header and cstint is c++ header.

$ head include/caffe/util/math_functions.hpp  
#ifndef CAFFE_UTIL_MATH_FUNCTIONS_H_  
#define CAFFE_UTIL_MATH_FUNCTIONS_H_                                                                                  

#include <cstdint>  
#include <stdint.h>  
#include <cmath>  // for std::fabs and std::signbit 

Then I add the flag "-std=c++11" in MakeFilefile

$ cat Makefile|grep std=c++11  
CXXFLAGS += -MMD -MP -std=c++11  
NVCCFLAGS += -ccbin=$(CXX) -Xcompiler -fPIC $(COMMON_FLAGS) -std=c++11  
        $(Q)$(CXX) -std=c++11 -shared -o $@ $(PY$(PROJECT)_SRC) \ 

This help the make all finish without error. But I knew some people can compile these without any change of the source codes. Maybe obviating this way will cause some unexpected run-time error?

**Comment by dimaslv** [comment]
Same problem here.
CentOS 7.2.1511
caffe-0.15

**Comment by junlizhang** [comment]
I met the same problem when compiling on RHEL7.3 ppc64le platform using version 0.15.14. And also YieldProcessor function implemented at 3rdparty/cub/host/mutex.cuh only consider arm and x86 platform which cause link failure at the end for lacking of pause instruction on powerpc. 

After patching 3rdparty/cub/host/mutex.cuh, CMakeLists.txt and src/caffe/parallel.cpp files, now I can generate caffe binary on RHEL7.3 ppc64le platform. Patch file can be found at [patch-nvcaffe.txt](https://github.com/NVIDIA/caffe/files/678421/patch-nvcaffe.txt)

I use cmake to build the caffe, detail steps listed as below:
mkdir build
cd build
cmake .. \
  -DCMAKE_C_COMPILER=gcc \
  -DCMAKE_CXX_COMPILER=g++ \
  -DCMAKE_C_FLAGS="-O3" \
  -DCMAKE_CXX_FLAGS="-O3" \
  -DBLAS=open \
  -DUSE_CUDNN=on \
  -DUSE_NCCL=ON \
  -DNCCL_INCLUDE_DIR=/usr/local/cuda/include \
  -DNCCL_LIBRARY=/usr/local/cuda/lib64/libnccl.so \
  -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda \
  -DCMAKE_VERBOSE_MAKEFILE=on \
  -DCMAKE_INSTALL_PREFIX=/opt/caffe/caffe-nv
make -j32

[root@gp100 build]# lsb_release -a
LSB Version:	:core-4.1-noarch:core-4.1-ppc64le
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 7.3 (Maipo)
Release:	7.3
Codename:	Maipo

[root@gp100 build]# file tools/caffe
tools/caffe: ELF 64-bit LSB executable, 64-bit PowerPC or cisco 7500, version 1 (GNU/Linux), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=1bd81b55fce0d2df66a9e47bd338276bcffc9292, not stripped

[root@gp100 build]# ldd tools/caffe
	linux-vdso64.so.1 =>  (0x00003fff8bf70000)
	libcaffe-nv.so.0.15 => /root/tmp/caffe-0.15.14/build/lib/libcaffe-nv.so.0.15 (0x00003fff8b930000)
	libboost_system-mt.so.1.53.0 => /lib64/libboost_system-mt.so.1.53.0 (0x00003fff8b8e0000)
	libboost_thread-mt.so.1.53.0 => /lib64/libboost_thread-mt.so.1.53.0 (0x00003fff8b8a0000)
	libboost_filesystem-mt.so.1.53.0 => /lib64/libboost_filesystem-mt.so.1.53.0 (0x00003fff8b860000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00003fff8b820000)
	libglog.so.0 => /lib64/libglog.so.0 (0x00003fff8b7c0000)
	libgflags.so.2.1 => /lib64/libgflags.so.2.1 (0x00003fff8b770000)
	libprotobuf.so.8 => /lib64/libprotobuf.so.8 (0x00003fff8b610000)
	libhdf5_hl.so.8 => /lib64/libhdf5_hl.so.8 (0x00003fff8b5b0000)
	libhdf5.so.8 => /lib64/libhdf5.so.8 (0x00003fff8b100000)
	liblmdb.so.0.0.0 => /lib64/liblmdb.so.0.0.0 (0x00003fff8b0c0000)
	libleveldb.so.1 => /lib64/libleveldb.so.1 (0x00003fff8b030000)
	libsnappy.so.1 => /lib64/libsnappy.so.1 (0x00003fff8b000000)
	libcudart.so.8.0 => /usr/local/cuda/lib64/libcudart.so.8.0 (0x00003fff8af70000)
	libcurand.so.8.0 => /usr/local/cuda/lib64/libcurand.so.8.0 (0x00003fff871e0000)
	libcublas.so.8.0 => /usr/local/cuda/lib64/libcublas.so.8.0 (0x00003fff84950000)
	libcudnn.so.5 => /usr/local/cuda/lib64/libcudnn.so.5 (0x00003fff7fd60000)
	libopencv_imgproc.so.2.4 => /lib64/libopencv_imgproc.so.2.4 (0x00003fff7fad0000)
	libopencv_highgui.so.2.4 => /lib64/libopencv_highgui.so.2.4 (0x00003fff7fa50000)
	libopencv_core.so.2.4 => /lib64/libopencv_core.so.2.4 (0x00003fff7f7c0000)
	libopenblas.so.0 => /opt/openblas/lib/libopenblas.so.0 (0x00003fff7ec10000)
	libpython2.7.so.1.0 => /lib64/libpython2.7.so.1.0 (0x00003fff7e970000)
	libboost_python-mt.so.1.53.0 => /lib64/libboost_python-mt.so.1.53.0 (0x00003fff7e8f0000)
	libnccl.so.1 => /usr/local/cuda/lib64/libnccl.so.1 (0x00003fff7d280000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00003fff7d0f0000)
	libm.so.6 => /lib64/libm.so.6 (0x00003fff7d010000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00003fff7cfd0000)
	libc.so.6 => /lib64/libc.so.6 (0x00003fff7cdf0000)
	librt.so.1 => /lib64/librt.so.1 (0x00003fff7cdc0000)
	/lib64/ld64.so.2 (0x000000002f6f0000)
	libz.so.1 => /lib64/libz.so.1 (0x00003fff7cd80000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00003fff7cd50000)
	libjpeg.so.62 => /lib64/libjpeg.so.62 (0x00003fff7ccd0000)
	libpng15.so.15 => /lib64/libpng15.so.15 (0x00003fff7cc70000)
	libtiff.so.5 => /lib64/libtiff.so.5 (0x00003fff7cbd0000)
	libjasper.so.1 => /lib64/libjasper.so.1 (0x00003fff7cb50000)
	libImath.so.6 => /lib64/libImath.so.6 (0x00003fff7cb20000)
	libIlmImf.so.7 => /lib64/libIlmImf.so.7 (0x00003fff7ca10000)
	libIex.so.6 => /lib64/libIex.so.6 (0x00003fff7c9d0000)
	libHalf.so.6 => /lib64/libHalf.so.6 (0x00003fff7c960000)
	libIlmThread.so.6 => /lib64/libIlmThread.so.6 (0x00003fff7c930000)
	libgtk-x11-2.0.so.0 => /lib64/libgtk-x11-2.0.so.0 (0x00003fff7c360000)
	libgdk-x11-2.0.so.0 => /lib64/libgdk-x11-2.0.so.0 (0x00003fff7c240000)
	libatk-1.0.so.0 => /lib64/libatk-1.0.so.0 (0x00003fff7c1f0000)
	libgio-2.0.so.0 => /lib64/libgio-2.0.so.0 (0x00003fff7bfd0000)
	libpangoft2-1.0.so.0 => /lib64/libpangoft2-1.0.so.0 (0x00003fff7bf90000)
	libpangocairo-1.0.so.0 => /lib64/libpangocairo-1.0.so.0 (0x00003fff7bf60000)
	libgdk_pixbuf-2.0.so.0 => /lib64/libgdk_pixbuf-2.0.so.0 (0x00003fff7bf10000)
	libcairo.so.2 => /lib64/libcairo.so.2 (0x00003fff7bd90000)
	libpango-1.0.so.0 => /lib64/libpango-1.0.so.0 (0x00003fff7bd10000)
	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00003fff7bca0000)
	libgobject-2.0.so.0 => /lib64/libgobject-2.0.so.0 (0x00003fff7bc10000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00003fff7ba80000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00003fff7b9a0000)
	libgthread-2.0.so.0 => /lib64/libgthread-2.0.so.0 (0x00003fff7b970000)
	libgstbase-0.10.so.0 => /lib64/libgstbase-0.10.so.0 (0x00003fff7b8e0000)
	libgstreamer-0.10.so.0 => /lib64/libgstreamer-0.10.so.0 (0x00003fff7b7a0000)
	libgmodule-2.0.so.0 => /lib64/libgmodule-2.0.so.0 (0x00003fff7b770000)
	libxml2.so.2 => /lib64/libxml2.so.2 (0x00003fff7b530000)
	libgstapp-0.10.so.0 => /lib64/libgstapp-0.10.so.0 (0x00003fff7b500000)
	libgstvideo-0.10.so.0 => /lib64/libgstvideo-0.10.so.0 (0x00003fff7b4c0000)
	libv4l1.so.0 => /lib64/libv4l1.so.0 (0x00003fff7b490000)
	libgfortran.so.3 => /lib64/libgfortran.so.3 (0x00003fff7b240000)
	libgomp.so.1 => /lib64/libgomp.so.1 (0x00003fff7b1e0000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00003fff7b1b0000)
	libjbig.so.2.0 => /lib64/libjbig.so.2.0 (0x00003fff7b180000)
	libIexMath.so.6 => /lib64/libIexMath.so.6 (0x00003fff7b150000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00003fff7afc0000)
	libXfixes.so.3 => /lib64/libXfixes.so.3 (0x00003fff7af90000)
	libXrender.so.1 => /lib64/libXrender.so.1 (0x00003fff7af60000)
	libXinerama.so.1 => /lib64/libXinerama.so.1 (0x00003fff7af30000)
	libXi.so.6 => /lib64/libXi.so.6 (0x00003fff7aef0000)
	libXrandr.so.2 => /lib64/libXrandr.so.2 (0x00003fff7aec0000)
	libXcursor.so.1 => /lib64/libXcursor.so.1 (0x00003fff7ae90000)
	libXcomposite.so.1 => /lib64/libXcomposite.so.1 (0x00003fff7ae60000)
	libXdamage.so.1 => /lib64/libXdamage.so.1 (0x00003fff7ae30000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00003fff7adf0000)
	libffi.so.6 => /lib64/libffi.so.6 (0x00003fff7adc0000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00003fff7ad70000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00003fff7ad30000)
	libharfbuzz.so.0 => /lib64/libharfbuzz.so.0 (0x00003fff7acb0000)
	libpixman-1.so.0 => /lib64/libpixman-1.so.0 (0x00003fff7ac00000)
	libEGL.so.1 => /lib64/libEGL.so.1 (0x00003fff7aba0000)
	libxcb-shm.so.0 => /lib64/libxcb-shm.so.0 (0x00003fff7ab70000)
	libxcb-render.so.0 => /lib64/libxcb-render.so.0 (0x00003fff7ab40000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00003fff7aaf0000)
	libGL.so.1 => /lib64/libGL.so.1 (0x00003fff7aa20000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00003fff7a9d0000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00003fff7a970000)
	liborc-0.4.so.0 => /lib64/liborc-0.4.so.0 (0x00003fff7a8b0000)
	libv4l2.so.0 => /lib64/libv4l2.so.0 (0x00003fff7a870000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00003fff7a800000)
	libgraphite2.so.3 => /lib64/libgraphite2.so.3 (0x00003fff7a7b0000)
	libX11-xcb.so.1 => /lib64/libX11-xcb.so.1 (0x00003fff7a780000)
	libxcb-dri2.so.0 => /lib64/libxcb-dri2.so.0 (0x00003fff7a750000)
	libxcb-dri3.so.0 => /lib64/libxcb-dri3.so.0 (0x00003fff7a720000)
	libxcb-present.so.0 => /lib64/libxcb-present.so.0 (0x00003fff7a6f0000)
	libxcb-randr.so.0 => /lib64/libxcb-randr.so.0 (0x00003fff7a6c0000)
	libxcb-xfixes.so.0 => /lib64/libxcb-xfixes.so.0 (0x00003fff7a690000)
	libxcb-shape.so.0 => /lib64/libxcb-shape.so.0 (0x00003fff7a660000)
	libxcb-sync.so.1 => /lib64/libxcb-sync.so.1 (0x00003fff7a630000)
	libxshmfence.so.1 => /lib64/libxshmfence.so.1 (0x00003fff7a600000)
	libgbm.so.1 => /lib64/libgbm.so.1 (0x00003fff7a5d0000)
	libdrm.so.2 => /lib64/libdrm.so.2 (0x00003fff7a590000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00003fff7a560000)
	libglapi.so.0 => /lib64/libglapi.so.0 (0x00003fff7a4d0000)
	libxcb-glx.so.0 => /lib64/libxcb-glx.so.0 (0x00003fff7a490000)
	libXxf86vm.so.1 => /lib64/libXxf86vm.so.1 (0x00003fff7a460000)
	libv4lconvert.so.0 => /lib64/libv4lconvert.so.0 (0x00003fff7a3c0000)

**Comment by drnikolaev** [comment]
Please try v0.16
