### ISSUE TITLE
The name "mAP" is not correct for the calculated measure

### ISSUE THREAD

**Issue by sherifshehata** [NVIDIA/caffe#234]
Hello,
I just noticed in your blog post and in the code that mAP is calculated as precision*recall. This measure is not similar to the standard mAP. It is actually more similar to the Fowlkes–Mallows index. It gives the user an impression that it have the same properties as the standard mAP, which is not correct.

Additionally, what is the reasons behind using this measure instead of the standard mAP measure?

**Comment by lukeyeager** [comment]
Here's the relevant part of the blog post:

> DetectNet also uses the “Python Layers” interface to calculate and output a simplified mean Average Precision (mAP) score for the final set of output bounding boxes. ... The simplified mAP score output by DetectNet is the product of precision (ratio of true positives to true positives plus false positives) and recall (ratio of true positives to true positives plus true negatives). It’s a good combined measure for how sensitive DetectNet is to objects of interest, how well it avoids false alarms and how precise it’s bounding box estimates are. 
> https://devblogs.nvidia.com/parallelforall/detectnet-deep-neural-network-object-detection-digits/

Is that helpful?

**Comment by sherifshehata** [comment]
Yes, i read that in the blog post, and i understand how it is calculated. My concern is that the term mAP is well known in the computer vision community, and it much different than the measure that you calculate.

I think using the name mAP for this measure is not right. And if there is no special reason for using this measure, i think implementing standard measures such as F-measure or standard mAP would be more convenient.

**Comment by sherifshehata** [comment]
Additionally the measure you calculate doesn't give the right indication of the detector's performance.

As example if the precision is 50 and recall is also 50. The F-measure will be 50, the Fowlkes–Mallows index (sometimes called G-measure) would be 50,  the standard mAP would be something around 50, while your measure would be 25. Which undermines the performance of the detector.

**Comment by gheinrich** [comment]
Thanks @sherifshehata what you're saying makes a lot of sense!

**Comment by sherifshehata** [comment]
Great to be of help. Thank you all for your continuous support.

**Comment by sherifshehata** [comment]
I think a simple fix would be taking the root, this will make it the same as Fowlkes–Mallows index (G-measure).

**Comment by moustaphakaraki** [comment]
@gheinrich If i understood the code correctly, recall is being calculated wrong as well. The blog and the code say:

> The simplified mAP score output by DetectNet is the product of precision (ratio of true positives to true positives plus false positives) and recall (ratio of true positives to true positives plus **_true_** negatives).

But recall is ratio of true positives to true positives plus **_false_** negatives.

**Comment by xuyuan** [comment]
unfortunately this issue is still open

@mkaraki48 seems the **false negative** is calculated despite of the name in code and doc

> tn = np.asarray([np.append(j, 3) for j in cur_gt_bbox[np.where(gt_matched == 0)]])
from https://github.com/NVIDIA/caffe/blob/caffe-0.15/python/caffe/layers/detectnet/mean_ap.py#L147

**Comment by drnikolaev** [comment]
Please check v0.16.5 and reopen the issue if the problem still exists.
