### ISSUE TITLE
Minor comment typo in detectnet_coverage_rectangular.cpp

### ISSUE THREAD

**Issue by sherifshehata** [NVIDIA/caffe#235]
In line 114 in detectnet_coverage_rectangular.cpp there is a typo in the comment. (https://github.com/NVIDIA/caffe/blob/caffe-0.15/src/caffe/util/detectnet_coverage_rectangular.cpp#L114)

croppedBbox is the intersection between the bounding box and the screen rectangle. But the comment states it is the union.

**Comment by drnikolaev** [comment]
Fixed.
