### ISSUE TITLE
What is the intuition behind using "scale_cvg" in object detection?

### ISSUE THREAD

**Issue by sherifshehata** [NVIDIA/caffe#236]
Hello,
I noticed that the coverage box is scaled using scale_cvg, which is set to 0.4 in the given example. My guess is that this is done to avoid using the bounding box borders' cells since they are usually noisy. Is this the reason? or is there another intuition behind it?

**Comment by yifangx** [comment]
Yes, it is the reason. 
Depending on the situation, this 0.4 number can be adjusted.
Nice question!
