### ISSUE TITLE
Bogus NCCL detection with cmake

### ISSUE THREAD

**Issue by flx42** [NVIDIA/caffe#239]
The NCCL detection code in cmake shouldn't hardcode a test against string `"ON"`:
https://github.com/NVIDIA/caffe/blob/caffe-0.15/cmake/Dependencies.cmake#L176

Instead, you should just rely on how `if` works in cmake:
https://cmake.org/cmake/help/v3.0/command/if.html

> True if the constant is 1, ON, YES, TRUE, Y, or a non-zero number. False if the constant is 0, OFF, NO, FALSE, N, IGNORE, NOTFOUND,

I was using using `USE_NCCL=1` like I usually do with cmake, and NCCL was actually disabled.

cc: @lukeyeager @slayton58

**Comment by lukeyeager** [comment]
Agreed

**Comment by drnikolaev** [comment]
fixed in 0.16
