### ISSUE TITLE
[Object detection] Double detection not penalized in ScoreDetections layer

### ISSUE THREAD

**Issue by sherifshehata** [NVIDIA/caffe#243]
In ScoreDetections layer, double detection for one gt box is not penalized in the for loop: 
https://github.com/NVIDIA/caffe/blob/caffe-0.15/python/caffe/layers/detectnet/mean_ap.py#L138

this will result in higher tp, which will affect all the calculated metrics

**Comment by yifangx** [comment]
Are you worried about the nearby detection boxes are counted only once in the matching game?

The nearby detection boxes are clustered into one box at the clustering stage. 
If it is not the case, it is due to the quality of the neural network and the clustering algorithm.

**Comment by williamzhangecp** [comment]
I believe the `break` statement in the loop ensures we don't ever assign more than one proposed detection to the same ground truth.

**Comment by sherifshehata** [comment]
The problem is that maybe the detector resulted in two boxes with small intersection to each other, so the clustering keep them both, But both of them has enough intersection with the ground truth, so we have double detections on the same ground truth box. 

As an example, you can see in the mAP calculation code here how this case is handled:
https://github.com/rbgirshick/py-faster-rcnn/blob/master/lib/datasets/voc_eval.py#L186
This is the same way it is handled in pascal VOC devkit

**Comment by williamzhangecp** [comment]
Yes, but since the outer loop is over ground truth, and the inner loop over proposals, the break should ensure that at most one proposal gets assigned to one ground truth.
So if there are strictly more than one proposal that satisfy the IOU criterion with a given ground truth, the first one (in order of indexing) will be assigned as TP, all the others should be FPs.

**Comment by sherifshehata** [comment]
You are right. Thank you
