### ISSUE TITLE
Check failed: initialized_ Create GPUMemory::Scope to initialize Memory Manager

### ISSUE THREAD

**Issue by rtrahms** [NVIDIA/caffe#245]
Hi all -
Up until recently, I had been running BVLC Caffe 1.0.0rc3 with DIGITS 4.0.0.rc-3.  DIGITS training and testing worked great, and I even built standalone CPP classifiers (based on the $CAFFE_HOME/examples/cpp_classification/classification.cpp code) to use the generated models in classifying images.  Great!  I wanted to move to object detection networks, so decided to replace my BVLC caffe installation with the NVCaffe 0.15.13 installation.  

Followed the instructions on the NVIDIA caffe build page on github - Installed it, built it and reran DIGITS - no problem.  When I built and ran my standalone classifier, CRASH dump with a failure in gpu_memory.cpp.  My hardware has never changed (GTX 980 ti), and the classifier code hasn't changed either (building caffe with cuDNN := 1 in the Makefile.config file.

Why does NVCaffe crash when the BVLC version of Caffe does not?

Thanks,
Rob

**Comment by rtrahms** [comment]
FYI, the classification.bin application (the one in $CAFFE_HOME/build/examples/cpp_classification) also fails with the same gpu_memory.cpp error.

Another clue - I have tried using the CPU_ONLY:=1 build configuration, and do not get this error.  The plot thickens!  So something related to CUDA, cuDNN with this fork of Caffe.
Rob

**Comment by rtrahms** [comment]
I was using CUDA 7.5 with CUDNN 4.0, and decided to install CUDA 8.0 and CUDNN 5.0 to see if anything was different.  Crashed with same error above.

**Comment by rtrahms** [comment]
Related issues:
#196
#213

**Comment by szm-R** [comment]
Hi, I'm getting the same error with my cpp code, before I've been using python and it works just fine but for some reasons I am migrating to cpp, and there I get this same error. 
I have attached my code, which is a simple modification of caffe classification example. and by the way the code works in cpu mode and the functionality is OK.
[Detection.txt](https://github.com/NVIDIA/caffe/files/505140/Detection.txt)

**Comment by rtrahms** [comment]
One more datapoint:  we have an NVidia GeForce 980 ti, and have NVidia driver package 352.   Not sure where to go from here, short of going back to the BVLC version of Caffe.

**Comment by drnikolaev** [comment]
@rtrahms thanks for the report. Do you observe "Scope to initialize Memory Manager" error while running your standalone classifier only? No error while training?

**Comment by lukeyeager** [comment]
Probably need to initialize the memory manager, right? See https://github.com/NVIDIA/caffe/pull/200#issuecomment-251175865.

Is there a way to do this automatically and/or lazily?

**Comment by drnikolaev** [comment]
Yes, like we do in python/caffe/_caffe.cpp
I'm working on it...

**Comment by szm-R** [comment]
@drnikolaev, In my case, I can train and test without any problems via the web app, also I have tested inference with python, and again it's OK. the problem only occurs when I use cpp codes (I have also tested extract_feature exe available in build/tools and it results in the same error so the problem is not with my code)
I'm using caffe 0.15.13 (the gpu I'm currently working on is a GTX 1080, and I wasn't able to install digits on it via sudo apt-get install digits, so instead I have built caffe and digits from source, with cuda 8.0 and cudnn 5, as I said the web app and python works fine)

I have another system with a 850M gpu on it, with the same issue (the same version of caffe and digits is also used here)

the main reason I'm using version 15.13 is that I'm training multi-class models
I'm really at a loss as to how I can get over this problem and I appreciate any help greatly...

**Comment by drnikolaev** [comment]
@szm2015 @rtrahms You may try this simple fix: #249 (while it's pending approval).

**Comment by szm-R** [comment]
Thank you!!! it works! but I would be grateful if you also explain the cause of this error. thanks again!

**Comment by rtrahms** [comment]
@drnikolaev - yes, similar answer to @szm2015, no problems training, only running standalone.
I am also interested in the cause of the error.
Rob

**Comment by drnikolaev** [comment]
Thanks for the confirmations folks! Cause of error: we now use caching GPU Memory Manager. It makes allocation of small arrays really fast. However, the manager instance must be properly initialized like [this](https://github.com/NVIDIA/caffe/blob/caffe-0.15/tools/caffe.cpp#L186). If some application doesn't do that it can't use the manager. However, there are many apps out there and I can't fix them all, so I fixed the manager and added self-initializing code. Note: this code works on single GPU only. For multiple GPUs you still need to do it right.

**Comment by rtrahms** [comment]
Hi all -
Your fix worked!  Thanks for the help.  This issue can be closed from my perspective.
Rob
