### ISSUE TITLE
cuDNN 3 + Caffe = Error??

### ISSUE THREAD

**Issue by AntreasAntoniou** [NVIDIA/caffe#25]
I was compiling a new version of 0.12 caffe with cuDNN 3 + CUDA 7.5 and I got the following error.

make: *** [.build_release/tools/upgrade_net_proto_binary.bin] Error 1
.build_release/lib/libcaffe-nv.so: undefined reference to `cudnnSetLRNDescriptor'
.build_release/lib/libcaffe-nv.so: undefined reference to `cudnnGetConvolutionBackwardDataWorkspaceSize'
.build_release/lib/libcaffe-nv.so: undefined reference to `cudnnConvolutionBackwardData_v3'
.build_release/lib/libcaffe-nv.so: undefined reference to `cudnnGetConvolutionBackwardFilterWorkspaceSize'
.build_release/lib/libcaffe-nv.so: undefined reference to `cudnnLRNCrossChannelBackward'
.build_release/lib/libcaffe-nv.so: undefined reference to `cudnnCreateLRNDescriptor'
.build_release/lib/libcaffe-nv.so: undefined reference to `cudnnGetConvolutionBackwardFilterAlgorithm'
.build_release/lib/libcaffe-nv.so: undefined reference to `cudnnLRNCrossChannelForward'
.build_release/lib/libcaffe-nv.so: undefined reference to `cudnnDestroyLRNDescriptor'
.build_release/lib/libcaffe-nv.so: undefined reference to `cudnnConvolutionBackwardFilter_v3'
.build_release/lib/libcaffe-nv.so: undefined reference to `cudnnGetConvolutionBackwardDataAlgorithm'
.build_release/lib/libcaffe-nv.so: undefined reference to `cudnnDivisiveNormalizationBackward'
.build_release/lib/libcaffe-nv.so: undefined reference to `cudnnDivisiveNormalizationForward'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/convert_imageset.bin] Error 1

Is there a way to fix this or should I simply roll back to cuDNN 2 and CUDA 7.0 for now?

**Comment by lukeyeager** [comment]
cuDNN v3 support came in with [`v0.13.0`](https://github.com/NVIDIA/caffe/releases/tag/v0.13.0). `v0.12.*` uses cuDNN v2. This wiki page may be helpful: https://github.com/NVIDIA/caffe/wiki/Versions.

If you want to use cuDNN v3, [CNMeM](https://github.com/NVIDIA/cnmem) is highly recommended for efficient memory use. Grab `v0.13.1`, build CNMeM, and follow these build steps: https://github.com/NVIDIA/caffe/pull/12#issuecomment-135579735

Cuda 7.0 and 7.5 should both be fine.

**Comment by AntreasAntoniou** [comment]
I tried what lukeyeager said but it seems that I am getting the same error? This is the procedure I did.
1. Download Cuda 7.5 , install , restart
2. Test cuda
3. Install cuDNN 3
4. Download Nvidia Caffe 0.13
5. Download CNMeM
6. Build CNMeM
7.Build caffe using CMake as explained here https://github.com/NVIDIA/caffe/pull/12#issuecomment-135579735
8. Make still can't find the same things as before.

Error:
[ 89%] [ 89%] [ 91%] Building CXX object tools/CMakeFiles/device_query.dir/device_query.cpp.o
Building CXX object tools/CMakeFiles/caffe.bin.dir/caffe.cpp.o
Building CXX object tools/CMakeFiles/convert_imageset.dir/convert_imageset.cpp.o
Linking CXX executable caffe-nv
[ 91%] Built target device_query
Scanning dependencies of target extract_features
[ 92%] Building CXX object tools/CMakeFiles/extract_features.dir/extract_features.cpp.o
Linking CXX executable caffe-nv
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnSetLRNDescriptor'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnGetConvolutionBackwardDataWorkspaceSize'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnConvolutionBackwardData_v3'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnGetConvolutionBackwardFilterWorkspaceSize'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnLRNCrossChannelBackward'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnCreateLRNDescriptor'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnGetConvolutionBackwardFilterAlgorithm'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnLRNCrossChannelForward'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnDestroyLRNDescriptor'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnConvolutionBackwardFilter_v3'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnGetConvolutionBackwardDataAlgorithm'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnDivisiveNormalizationBackward'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnDivisiveNormalizationForward'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/caffe-nv] Error 1
make[1]: *** [tools/CMakeFiles/compute_image_mean.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking CXX executable caffe-nv
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnSetLRNDescriptor'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnGetConvolutionBackwardDataWorkspaceSize'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnConvolutionBackwardData_v3'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnGetConvolutionBackwardFilterWorkspaceSize'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnLRNCrossChannelBackward'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnCreateLRNDescriptor'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnGetConvolutionBackwardFilterAlgorithm'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnLRNCrossChannelForward'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnDestroyLRNDescriptor'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnConvolutionBackwardFilter_v3'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnGetConvolutionBackwardDataAlgorithm'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnDivisiveNormalizationBackward'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnDivisiveNormalizationForward'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/caffe-nv] Error 1
make[1]: *** [tools/CMakeFiles/convert_imageset.dir/all] Error 2
Linking CXX executable caffe-nv
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnSetLRNDescriptor'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnGetConvolutionBackwardDataWorkspaceSize'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnConvolutionBackwardData_v3'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnGetConvolutionBackwardFilterWorkspaceSize'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnLRNCrossChannelBackward'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnCreateLRNDescriptor'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnGetConvolutionBackwardFilterAlgorithm'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnLRNCrossChannelForward'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnDestroyLRNDescriptor'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnConvolutionBackwardFilter_v3'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnGetConvolutionBackwardDataAlgorithm'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnDivisiveNormalizationBackward'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnDivisiveNormalizationForward'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/caffe-nv] Error 1
make[1]: *** [tools/CMakeFiles/extract_features.dir/all] Error 2
Linking CXX executable caffe
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnSetLRNDescriptor'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnGetConvolutionBackwardDataWorkspaceSize'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnConvolutionBackwardData_v3'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnGetConvolutionBackwardFilterWorkspaceSize'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnLRNCrossChannelBackward'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnCreateLRNDescriptor'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnGetConvolutionBackwardFilterAlgorithm'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnLRNCrossChannelForward'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnDestroyLRNDescriptor'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnConvolutionBackwardFilter_v3'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnGetConvolutionBackwardDataAlgorithm'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnDivisiveNormalizationBackward'
../lib/libcaffe-nv.so.0.13.1: undefined reference to `cudnnDivisiveNormalizationForward'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/caffe] Error 1

I know I am missing something here. Anybody have any clues?

**Comment by lukeyeager** [comment]
Depending on how you have your paths set up, you may need to tell CMake how to find cuDNN as well. Something like this:

```
cmake \
    -DUSE_CNMEM=True -DCNMEM_INCLUDE=/path/to/cnmem/include -DCNMEM_LIBRARY=/path/to/cnmem/build/libcnmem.so \
    -DUSE_CUDNN=True -DCUDNN_INCLUDE=/path/to/cudnn/include -DCUDNN_LIBRARY=/path/to/cudnn/lib64/libcudnn.so \
    ..
```

**Comment by AntreasAntoniou** [comment]
Thanks that fixed it. I can now see performance improvements.

**Comment by RiweiChen** [comment]
hi @AntreasAntoniou, I have the same problem, can you share how to fixed that ?

**Comment by AntreasAntoniou** [comment]
You have to do what lukeyeager said in his post right above mine.

cmake \
    -DUSE_CNMEM=True -DCNMEM_INCLUDE=/path/to/cnmem/include -DCNMEM_LIBRARY=/path/to/cnmem/build/libcnmem.so \
    -DUSE_CUDNN=True -DCUDNN_INCLUDE=/path/to/cudnn/include -DCUDNN_LIBRARY=/path/to/cudnn/lib64/libcudnn.so \
    ..

**Comment by liao1995** [comment]
@lukeyeager It works! thank you very much !
