### ISSUE TITLE
deadlock when train on multiple GPU and restore the state from previous training

### ISSUE THREAD

**Issue by CFAndy** [NVIDIA/caffe#255]
Nvidia-smi -l show
Root solver enter into 0% utilization 
while the slaver solver are keep 100% utilization.
BVLC caffe has no such issue. 
fixed by #254

**Comment by CFAndy** [comment]
Bug is still there. I use the 0.16 to train mobilenet with 4 titanx-pascal, caffe entered into deadlock state randomly after a test run.  Have to disable the test.

**Comment by drnikolaev** [comment]
Thanks, I'm looking to it...

**Comment by drnikolaev** [comment]
Fixed in 0.16.2
