### ISSUE TITLE
"caffe.DataParameter" has no field named "image_data_param"

### ISSUE THREAD

**Issue by CXZ116** [NVIDIA/caffe#256]
Hi;
I am using Nvidia/caffe to train GoogleNet_Inception_v3 using my own dataset. Instead of using lmdb files, I am reading images from disc:

```
name: "GoogleNet_Inception_v3"
layer {
  name: "data"
  type: "ImageData"
  top: "data"
  top: "label"
  include {
    phase: TRAIN
  }
  transform_param {
    mirror: true
    crop_size: 224
    mean_file: "~/NVIDIA/caffe/data/ilsvrc12/imagenet_mean.binaryproto"
  }
  image_data_param {
    source: "~/patch/train.txt"
    batch_size: 39
    new_height: 256
    new_width: 256
  }
}
```

When I run caffe with the prototxt file, I got the following message:

```
net: "~/model/inception/inception_v3_train_val.prototxt"
test_initialization: false
average_loss: 40
I1019 16:20:34.183389 25705 solver.cpp:91] Creating training net from net file: ~/model/inception/inception_v3_train_val.prototxt

[libprotobuf ERROR google/protobuf/text_format.cc:298] Error parsing text-format caffe.NetParameter: 42:20: Message type "caffe.DataParameter" has no field named "image_data_param".
F1019 16:20:34.183706 25705 upgrade_proto.cpp:79] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: ~/model/inception/inception_v3_train_val.prototxt
```

Is there any typo in my prototxt file, or the NVIDIA/caffe does not support reading images files from hard drive?

Thanks,

David

**Comment by lukeyeager** [comment]
Check line 42 of your network. I don't think you included it in the OP.

**Comment by CXZ116** [comment]
Luke:

Thanks, yes, it is a typo on that line when I tried to change from data_param to image_data_param. I fixed that and the network started to run.
A side question: is there any trained inception v3 caffemodel I can download? I am training from scratch and think it is better to save time by fine tuning the network.
Thanks again,

David

**Comment by lukeyeager** [comment]
We're working on a model "store" that DIGITS can connect to and download trained models (https://github.com/NVIDIA/DIGITS/pull/1077), but it's not ready yet.
