### ISSUE TITLE
Compile failed on POWER 8

### ISSUE THREAD

**Issue by DJmimi35** [NVIDIA/caffe#260]
Hi, 

I'm trying to install caffe on my P8 server, but it's always failed at this step.
Do you have any suggestion?

Scanning dependencies of target caffe
[ 29%] Building CXX object src/caffe/CMakeFiles/caffe.dir/blob.cpp.o
[ 29%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/insert_splits.cpp.o
[ 29%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layer.cpp.o
[ 31%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/db_leveldb.cpp.o
[ 31%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/blocking_queue.cpp.o
[ 32%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/upgrade_proto.cpp.o
[ 32%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/signal_handler.cpp.o
[ 33%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/hdf5.cpp.o
[ 33%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/detectnet_coverage_rectangular.cpp.o
[ 33%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/db.cpp.o
[ 35%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/gpu_memory.cpp.o
[ 35%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/math_functions.cpp.o
[ 35%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/db_lmdb.cpp.o
[ 36%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/im2col.cpp.o
/tmp/cc2Og6IF.s: Assembler messages:
/tmp/cc2Og6IF.s:1789: Error: unrecognized opcode: `pause'
/tmp/cc2Og6IF.s:2177: Error: unrecognized opcode:`pause'
/tmp/cc2Og6IF.s:2596: Error: unrecognized opcode: `pause'
/tmp/cc2Og6IF.s:3159: Error: unrecognized opcode:`pause'
/tmp/cc2Og6IF.s:5045: Error: unrecognized opcode: `pause'
/tmp/cc2Og6IF.s:6073: Error: unrecognized opcode:`pause'
/tmp/cc2Og6IF.s:6178: Error: unrecognized opcode: `pause'
/tmp/cc2Og6IF.s:6481: Error: unrecognized opcode:`pause'
src/caffe/CMakeFiles/caffe.dir/build.make:28091: recipe for target 'src/caffe/CMakeFiles/caffe.dir/util/gpu_memory.cpp.o' failed
make[2]: **\* [src/caffe/CMakeFiles/caffe.dir/util/gpu_memory.cpp.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
CMakeFiles/Makefile2:272: recipe for target 'src/caffe/CMakeFiles/caffe.dir/all' failed
make[1]: **\* [src/caffe/CMakeFiles/caffe.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2
root@P40:~/caffe/build#

**Comment by flx42** [comment]
See #247

**Comment by DJmimi35** [comment]
Yes, it pass. thanks for your help.

**Comment by hit1001** [comment]
I couldnt compile on aarch64 too..

**Comment by DJmimi35** [comment]
forget to close last post
