### ISSUE TITLE
cpp classification example using float16

### ISSUE THREAD

**Issue by kaatish** [NVIDIA/caffe#262]
Hi

I want to rewrite the cpp classification using float16 by using the experimental/fp16 branch. Would I need to convert the caffemodel or deploy.prototxt files using the binaries in the tools directory? In general how should I go about it?

I understand that the guidelines specified that I direct usage questions to caffe-users list but given that experimental-fp16 branch is nvidia specific I decided to post the question here. Let me know if the google group is a better place to post this.

**Comment by drnikolaev** [comment]
@kaatish It's now supported by new 0.16 release
