### ISSUE TITLE
Check failed: status == CUDNN_STATUS_SUCCESS (9 vs. 0)  CUDNN_STATUS_NOT_SUPPORTED

### ISSUE THREAD

**Issue by medhani** [NVIDIA/caffe#266]
I got the below error  when running ipython notebook with video-caffe. It worked well without back-propagation.

F1114 14:11:09.641414 23776 cudnn_ndconv_layer.cu:184] Check failed: status == CUDNN_STATUS_SUCCESS (9 vs. 0)  CUDNN_STATUS_NOT_SUPPORTED
*** Check failure stack trace: ***

**Comment by shuzhenzhang** [comment]
Hi,
You can try to chang the LMDB_MAP_SIZE in the file of caffe_fp16/caffe/include/caffe/util/db_lmdb.hpp.

**Comment by shuzhenzhang** [comment]
Hi,
Have you solved it ?
When I run "make runtest", I got the below error:
F0301 10:34:42.863984 31629 cudnn_conv_layer.cpp:157] Check failed: status == CUDNN_STATUS_SUCCESS (9 vs. 0)  CUDNN_STATUS_NOT_SUPPORTED
*** Check failure stack trace: ***
    @       0x7f864b9718  google::LogMessage::Fail()
    @       0x7f864bb614  google::LogMessage::SendToLog()
    @       0x7f864b9290  google::LogMessage::Flush()
    @       0x7f864bbeb4  google::LogMessageFatal::~LogMessageFatal()
    @       0x7f84de5e94  caffe::CuDNNConvolutionLayer<>::Reshape()
    @           0x588488  caffe::Layer<>::SetUp()
    @           0x9c694c  caffe::CuDNNConvolutionLayerTest_TestSimpleConvolutionCuDNN_Test<>::TestBody()
    @           0xa74774  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0xa6da7c  testing::Test::Run()
    @           0xa6dbb8  testing::TestInfo::Run()
    @           0xa6dc78  testing::TestCase::Run()
    @           0xa6edd8  testing::internal::UnitTestImpl::RunAllTests()
    @           0xa6f0ec  testing::UnitTest::Run()
    @           0x56c0b8  main
    @       0x7f849908a0  __libc_start_main
Makefile:552: recipe for target 'runtest' failed
make: *** [runtest] Aborted

**Comment by drnikolaev** [comment]
Please try v0.16
