### ISSUE TITLE
ERROR: Check failed: error == cudaSuccess (33 vs. 0) invalid resource handle

### ISSUE THREAD

**Issue by DJmimi35** [NVIDIA/caffe#271]
Hi all,

I'm trying to create models on DIGITS, and my system has 4 GPU on it. However, when I use multiple GPU(more than one) in one job, it always shows "ERROR: Check failed: error == cudaSuccess (33 vs. 0) invalid resource handle". This won't happen with BVLC caffe, but I need NVcaffe to demo object detection with kitti dataset. I've tried some different NVcaffe version.
0.15.1: no error
0.15.2: no error
0.15.3: invalid resource handle
0.15.4: invalid resource handle
The former versions were OK but it took long time on training and the accuracy rate is only about 5%.
Thanks 

Mimi

**Comment by thatguymike** [comment]
Does top of tree 0.15 work?  Can you tell us more about your GPU configuration?  Are they identical GPUs or at least the same generation?

**Comment by DJmimi35** [comment]
I'm not sure what do you mean about "the top of tree", is it the latest build of 0.15.X? or the 1st build.
The 1st build is OK, but the latest has error.
And My GPU is Tesla P100 \* 4
CUDA: 8.0.44-1
NVIDIA Driver: 361.93.01

Please refer to attachment for details
[nvidia-smi.txt](https://github.com/NVIDIA/caffe/files/601850/nvidia-smi.txt)
[nvidia-smi-q.txt](https://github.com/NVIDIA/caffe/files/601851/nvidia-smi-q.txt)

Thanks

**Comment by cliffwoolley** [comment]
He means the latest (top/HEAD) of the 0.15 branch.

Thanks for the additional info.  Does this happen with every model, or just
some particular model?

Which cuDNN version?  (5.0 or 5.1, most likely?)

Thanks,
Cliff

**Comment by DJmimi35** [comment]
cuDNN is 5.1.5

I have not tried another model. I will tell you later after I have any result.

the caffe config is as below
[caffe-config.txt](https://github.com/NVIDIA/caffe/files/601852/caffe-config.txt)

**Comment by DJmimi35** [comment]
Yes it happen in creating every model, such as classification with mnist dataset.

**Comment by cliffwoolley** [comment]
Thanks for the update.  I see you're on a P8+ machine.  We'll try to
reproduce the issue.

One more question: which version of NCCL are you using?  One of the changes
in v0.15.3 was to fix the way that NCCL is located by cmake; it's possible
that's the first build where you picked up the NCCL integration.

-Cliff

**Comment by DJmimi35** [comment]
nccl version should be 1.2.3-1

**Comment by cliffwoolley** [comment]
I did a bit of digging, and it appears that a very similar-looking issue
was found and fixed in 0.15.5 as part of
https://github.com/NVIDIA/caffe/pull/179 .  Can you please reconfirm that
you see this issue with the latest 0.15.13 build (
https://github.com/NVIDIA/caffe/releases/tag/v0.15.13), and if so please
send us the full error backtrace so that we know which file/line triggered
the error?

Thanks again,
Cliff

**Comment by DJmimi35** [comment]
Hi Cliff,

It looks great to use NVcaffe-0.15.13, all the GPU are running for creating model now.

Actually, I should find this build earlier to save time for all of us. What I thought was the latest version means the package git clone from "https://github.com/NVIDIA/caffe". It doesn't point to the latest build, does it?

And my last question is the accuracy of kitti model keeps low after 30 epochs training, what should I do to improve it? I guess it might be my next issue if I didn't find a former submitting.

Thanks for your help

![p100x4_create_kitti_model](https://cloud.githubusercontent.com/assets/23118096/20468201/0e0233e6-afcf-11e6-9395-1d2d5ccb3d1a.png)

**Comment by cliffwoolley** [comment]
Thanks for the tip on "git clone" not pointing to the correct latest
build.  We'll check on it.  Glad things are looking better now!

Do let us know in another issue if your kitti training convergence issues
persist.

Thanks,
Cliff

**Comment by DJmimi35** [comment]
Hi Cliff,

I just submit another issue for the low accuracy rate of kitti model.
https://github.com/NVIDIA/caffe/issues/272

And I checked again the version of NVcaffe via git clone, it's 0.15.14. Sorry for confusing you.

**Comment by cliffwoolley** [comment]
Thanks again.
