### ISSUE TITLE
centos7.2 x64 make error ：“ ‘UINT8_MAX’ was not declared in this scop ”

### ISSUE THREAD

**Issue by ghost** [NVIDIA/caffe#274]
系统：centos7.2 x64

使用make 编译时报错，信息如下：
CXX src/caffe/layers/detectnet_transform_layer.cpp
In file included from src/caffe/layers/detectnet_transform_layer.cpp:3:0:
./include/caffe/layers/detectnet_transform_layer.hpp: In member function ‘bool caffe::AugmentSelection::doDesaturation() const’:
./include/caffe/layers/detectnet_transform_layer.hpp:38:64: error: ‘UINT8_MAX’ was not declared in this scope
   bool doDesaturation() const { return saturation < (1.0 - 1.0/UINT8_MAX); }
                                                                ^
src/caffe/layers/detectnet_transform_layer.cpp: In member function ‘void caffe::DetectNetTransformationLayer<Dtype>::retrieveMeanImage(cv::Size)’:
src/caffe/layers/detectnet_transform_layer.cpp:86:23: error: ‘UINT8_MAX’ was not declared in this scope
   data_mean_ /= Dtype(UINT8_MAX);
                       ^
src/caffe/layers/detectnet_transform_layer.cpp: In member function ‘void caffe::DetectNetTransformationLayer<Dtype>::retrieveMeanChannels()’:
src/caffe/layers/detectnet_transform_layer.cpp:94:56: error: ‘UINT8_MAX’ was not declared in this scope
       mean_values_.fill(t_param_.mean_value(0) / Dtype(UINT8_MAX));
                                                        ^
src/caffe/layers/detectnet_transform_layer.cpp: In member function ‘caffe::DetectNetTransformationLayer<Dtype>::Mat3v caffe::DetectNetTransformationLayer<Dtype>::transform_image_cpu(const Mat3v&, const caffe::AugmentSelection&)’:
src/caffe/layers/detectnet_transform_layer.cpp:420:33: error: ‘UINT8_MAX’ was not declared in this scope
   Mat3v img = src_img.clone() / UINT8_MAX;
                                 ^
In file included from src/caffe/layers/detectnet_transform_layer.cpp:3:0:
./include/caffe/layers/detectnet_transform_layer.hpp: In member function ‘bool caffe::AugmentSelection::doDesaturation() const’:
./include/caffe/layers/detectnet_transform_layer.hpp:38:76: warning: control reaches end of non-void function [-Wreturn-type]
   bool doDesaturation() const { return saturation < (1.0 - 1.0/UINT8_MAX); }
                                                                            ^
make: *** [.build_release/src/caffe/layers/detectnet_transform_layer.o] Error 1

我曾尝试使用 cmake 进行编译，但是对cmake的用法不熟，之后又遇到了其他很多问题。我明白，在用cmake编译时，这个问题可以通过 issues207 中 fpertl大神提到的办法解决：
CMakeLists.txt file 61行
if(UNIX OR APPLE)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC -Wall")
    add_definitions(-D__STDC_LIMIT_MACROS) //新加
endif()

现在的问题是：在用make编译时，要如何解决这个问题？实话实说，今天从早上9点到现在，我一直在折腾，网上的资料看了老多，但依旧无解。
我知道用中文将这个问题叙述出来不是很妥当，毕竟github  for world（也不知道对不对）。但是如果用英文写我担心更表达不清楚我的意思。看到issues233还在那儿挂着无解，我真不知道我提交这个有没有希望被解决。希望高手给个解决办法，将不胜感激。nickzp@qq.com 苏

**Comment by dimaslv** [comment]
Same problem here.
CentOS 7.2.1511
caffe-0.15

**Comment by shrutiramesh88** [comment]
facing the same issue on RedHat 7.2.
Its not getting resolved even after adding the line: add_definitions(-D__STDC_LIMIT_MACROS) in CMakeLists.txt

**Comment by shrutiramesh88** [comment]
Edit Makefile:
CXXFLAGS += -MMD -MP -std=c++11
 This fixed the issue

**Comment by kilmarnock** [comment]
If it happens during make **pycaffe**:

Edit Makefile:
**NVCCFLAGS** += -ccbin=$(CXX) -Xcompiler -fPIC $(COMMON_FLAGS) -std=c++11
This fixed the issue
