### ISSUE TITLE
error == cudaSuccess (3 vs. 0)  initialization error

### ISSUE THREAD

**Issue by nirajpatel** [NVIDIA/caffe#275]
Hi guys! I am running a project that is using Gunicorn and Falcon. I am initializing my net on each worker so I don't believe this is a threading issue. I am using **nvidia/caffe:0.15** to run my application. I am running on a **p2.xlarge** EC2 instance in AWS. 

For some reason my stack trace is empty. Any ideas as to what could be wrong here?

This is what my output looks like (the stack trace is empty): 
<img width="811" alt="screen shot 2016-11-22 at 11 06 59 pm" src="https://cloud.githubusercontent.com/assets/3387076/20551680/6df432ba-b108-11e6-94cc-b84c45ec7d09.png">

Thanks in advance!

**Comment by drnikolaev** [comment]
@nirajpatel Please update to v0.16
