### ISSUE TITLE
Bug in cudnn_batch_norm_layer.cu

### ISSUE THREAD

**Issue by argman** [NVIDIA/caffe#279]
In the implemention line 25
```
if (this->phase_ == TRAIN) {
```
I find during testing, this will always be true, and there is another issue with this implemention,
when during fine-tuning, we may fix the bn layer, so this wont work, I think its better use global_stats instead.

**Comment by argman** [comment]
And i find in cudnn.h
```
/* MUST use factor=1 in the very first call of a complete training cycle.
Use a factor=1/(1+n) at N-th call to the function to get
Cumulative Moving Average (CMA) behavior
CMA[n] = (x[1]+...+x[n])/n
 Since CMA[n+1] = (n*CMA[n]+x[n+1])/(n+1) =
 ((n+1)*CMA[n]-CMA[n])/(n+1) + x[n+1]/(n+1) =
CMA[n]*(1-1/(n+1)) + x[n+1]*1/(n+1) */
 double                              exponentialAverageFactor,
```
but in this implemention, it just use 
```
1 - this->moving_average_fraction_
```

**Comment by argman** [comment]
I am wondering why no one can answer this, hmm..

**Comment by drnikolaev** [comment]
@argman is this still an issue in 0.16?
