### ISSUE TITLE
Clarification needed: Prefetching for multi-GPU training

### ISSUE THREAD

**Issue by vaisaxen** [NVIDIA/caffe#280]
I am using multiple GPUs to train my model and want to measure file I/O time when reading imagenet LMDB file.  I am really confused as to how the prefetching of batches work in case of multiple GPUs and wanted some info for the same.  The documentation is also very little for the same. 

As per my understanding and some testing, there is an independent prefetch thread per GPU which fetches next batch from LMDB file to host memory in the background while the computation for current batch is going on in the GPU.  Couple of questions:
1. is the above understanding correct ? Can we change the number of prefetching threads or is it fixed for a given number of GPUs ? One prefetching thread per GPU may not be able to provide enough data throughput to feed the GPU for computation. 
2. The variable PREFETCH_COUNT seems to specify the number of batches to prefetch to host memory by each prefetch thread. Are these multiple PREFETCH_COUNT batches prefetched in parallel or one after another inside a prefetch thread.

**Comment by slayton58** [comment]
1. Yes, your understanding is correct. Currently this is fixed at one thread per GPU
2. Serially. You can have up PREFETCH_COUNT batches prefetched + ready for use, but they don't get filled in parallel.

**Comment by vaisaxen** [comment]
Thanks Simon for the response. Couple of follow up questions: 
1. Which portion of the code should be timed in order to measure the time for reading a single batch from LMDB file to host memory. 
2. Is there a documentation for threading mechanism in NVCaffe ? There are just too many different kind of threads and it is hard to get an understanding of the same by looking at the code, for example - threads launching GPU kernels, prefetch threads calling DataLayer:load_batch, threads in DataReader class for actual reading of data from the file system, data processing threads performing transformation on the data that has been loaded.

**Comment by slayton58** [comment]
1. That's tricky -- there's no good place to time just the LMDB read time (perhaps timing around these calls is the easiest way ([data_reader.cpp](https://github.com/NVIDIA/caffe/blob/caffe-0.15/src/caffe/data_reader.cpp#L86)). We generally don't time just LMDB read time, but read + decode + transform, which can be done by timing this method: [data_layer.cpp](https://github.com/NVIDIA/caffe/blob/caffe-0.15/src/caffe/layers/data_layer.cpp#L103)
2. I'm not sure about documentation, but I can answer any specific questions you have.

**Comment by vaisaxen** [comment]
Thanks for the response. 
1. It is okay for me to get the timing for read + decode + transform for a batch and I had a look at load_batch initially ([data_layer.cpp](https://github.com/NVIDIA/caffe/blob/caffe-0.15/src/caffe/layers/data_layer.cpp#L103)). However, the statement at [data_layer.cpp](https://github.com/NVIDIA/caffe/blob/caffe-0.15/src/caffe/layers/data_layer.cpp#L144) only seems to pop the data from a queue rather than reading it from the LMDB file. Therefore, timing this statement will not give me the actual reading of the data from LMDB file. If that is not the case, please let me know. In case my understanding is right, kindly let me know how can we get the actual read + decode + transform time. 

2. To be specific, for a node with 40 CPU cores and 4 GPUs, how many independent threads in total will be created when training using all 4 GPUs using default options ?  As per my current understanding, these should include threads for launching GPU kernels, prefetching threads, threads for data transformation and any other threads ? For example, one option can be to use just one host thread to launch GPU kernels for all the 4 GPUs; other (better) option is to use 4 independent host threads with one host thread dedicated to a single GPU.

**Comment by slayton58** [comment]
1. There is no real way to get exactly what you want in a single place - you could measure the average read time from LMDB in data_reader.cpp and the average time per image from data_layer.cpp for pop + decode + transform and add them all together. You could also use something like iotop to look at disk access to see how the LMDB reader is performing.

2. From memory, 1 (reader) + nGPUs * (1 (prefetch) + (nCPU/nGPU)*1 (decode) + 1 (control) ) threads are created, so for your system: 1 + 4 * (1 + 10 + 1) = 49 threads.

**Comment by vaisaxen** [comment]
Thanks Simon for the response. 
On 2. Why is there only single reader thread doing file I/O from the LMDB file ? Won't it become a bottleneck when increasing the number of GPUs ? Having multiple reading threads should provide better data throughput than a single thread.

**Comment by slayton58** [comment]
Deterministic I/O is a reason for the single thread.

Funnily enough, a single thread seems to work fine in all of our experiments -- we had to move everything else out of that thread (BVLC caffe does read, parse datum, read, parse datum, etc. while we purely red), but that thread is reading contiguous data in a consistent pattern from the disk, so it's an ideal access pattern.

Given this, I'm not convinced multiple reader threads would actually improve throughput, unless it could be shown that the single thread is unable to saturate the disk I/O.

**Comment by vaisaxen** [comment]
Thanks Simon for your responses and sorry for my long silence. 

I agree that a single thread reading data sequentially from a file is an ideal pattern and currently I have no data points to argue that a single thread will be unable to saturate the disk I/O. I will probably create a micro-benchmark to test the same. I will let you know in case I find something interesting to share. 

For now, this issue stands resolved and I am closing it. Thanks again.
