### ISSUE TITLE
On the confusion of the cudnn_conv_layer.cu

### ISSUE THREAD

**Issue by DLDarwin** [NVIDIA/caffe#281]
Hi,

 In caffe/src/caffe/layers/cudnn_conv_layer.cu, line 139, you have the following code to synchronize the streams running cuDNN computations:

```
    // Synchronize the work across groups, each of which went into its own
    // stream, by launching an empty kernel into the default (null) stream.
    // NOLINT_NEXT_LINE(whitespace/operators)
    CUDA_CHECK(cudaStreamSynchronize(cudaStreamLegacy));
```

 In BVLC/caffe,  the code is as follows:
```
// Synchronize the work across groups, each of which went into its own
// stream, by launching an empty kernel into the default (null) stream.
// NOLINT_NEXT_LINE(whitespace/operators)
sync_conv_groups<<<1, 1>>>();
```

I know that these two methods  can synchronize the streams used for cuDNN computations. However, when I try to test the training speed of  these two methods in Bvlc/caffe, the first method that use cudaStreamSynchronize is much faster then sync_conv_groups. 
### I dont understand quitely, can someone explain?

**Comment by DLDarwin** [comment]
@Gnurou   can you watch this problem?  thank you !

**Comment by Gnurou** [comment]
@zzqiang04053080 sorry, I am not qualified to answer this question (not at all a CUDA expert), not sure what makes you belive I can help here?

**Comment by DLDarwin** [comment]
@Gnurou   I'm sorry, I made a mistake.

**Comment by DLDarwin** [comment]
@lukeyeager   Can you  give some advice?

**Comment by lukeyeager** [comment]
No idea, sorry.

/cc @drnikolaev

**Comment by drnikolaev** [comment]
Well, it's really hard to say. This is one of the reasons why we consider the option to get rid of "legacy" or "default" streams. Meanwhile, could you try CUDA 7.5? Do you observe the same pattern out there?

**Comment by zzqiang04053080** [comment]
@drnikolaev   I did test on CUDA 7.5.  This is very strange, the speed of the two methods are very close!   I am getting more and more confused.

**Comment by drnikolaev** [comment]
@DLDarwin - 0.16 does this right, please check it out.
