### ISSUE TITLE
Performance Issues for the Titan X

### ISSUE THREAD

**Issue by Anonom** [NVIDIA/caffe#283]
Hello, I've recently ran into an issue with my system where I was unable to boot. After reinstalling a new kernel I fixed the issue, but have found that performance for caffe has fallen sharply. Running an alexnet benchmark I had gotten 99ms before and am now getting 189ms. The old kernel was linux-image-4.4.0-45-generic and the one that I have now is linux-image-4.4.0-47-generic. Is the issue this new kernel?

**Comment by Anonom** [comment]
After some searching, I found that the kernel is fine. I am actually getting better performance on the older version of Nvidia Caffe. caffe-caffe-0.14 performs at the level that I was getting before, while caffe-caffe-0.15 is actually infact slower then even bvlc caffe.

**Comment by enoonIT** [comment]
I also have this problem - with the most recent nvidia caffe training is 10x slower.
Reverting to 0.15.13 fixes this for me

**Comment by pedropgusmao** [comment]
This is also happening for the gtx 1080. Reverting to 0.15.13 also fixed for me.

**Comment by drnikolaev** [comment]
Thanks for reporting this. Question: _Reverting to 0.15.13 also fixed for me_  -- reverting from what? From the top of 0.15?

**Comment by pedropgusmao** [comment]
Yes. By cloning from 0.15 followed by a checkout to tag v0.15.13 does the trick.

**Comment by drnikolaev** [comment]
Please update to v0.16
