### ISSUE TITLE
Different inference results on windows compared to Linux

### ISSUE THREAD

**Issue by dtmoodie** [NVIDIA/caffe#284]
Hello,

I have a branch of nvcaffe that incorporates [SSD](https://github.com/weiliu89/caffe/tree/ssd).  I also have a branch from bvlc/caffe that incorporates SSD.  There is minimal difference between these two branches other than being based off of either nvcaffe or bvlc/caffe.

In my version that is based off of nvcaffe, there is a significant difference in results at inference.
Linux:
![qtimagedisplay0_screenshot_04 12 2016](https://cloud.githubusercontent.com/assets/7254941/20868208/e762167a-ba23-11e6-95d6-074fd9a3a639.png)

Windows:
![qtimagedisplay0_screenshot_04 12 2016](https://cloud.githubusercontent.com/assets/7254941/20868231/551a9e94-ba24-11e6-841b-3cab7ff38cc1.png)

All preprocessing has been verified to be correct and the same between both images.
Both images are using the same trained network with the same network description prototxt.
If I use the branch based off of bvlc/caffe, there is no issue.
Both images were inferred from approximately the same commit of my branch, (minor non related cmake file changes).

The cmake config for Linux is as follows:
******************* Caffe Configuration Summary *******************
General:
  Version           :   0.15.14
  Git               :   rc-2178-g3a7ac79
  System            :   Linux
  C++ compiler      :   /usr/bin/c++
  Release CXX flags :   -fno-omit-frame-pointer -O3 -DNDEBUG -g -std=c++11 -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
  Debug CXX flags   :   -g -std=c++11 -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
  Build type        :   Release

  BUILD_SHARED_LIBS :   ON
  BUILD_python      :   ON
  BUILD_matlab      :   OFF
  BUILD_docs        :   ON
  CPU_ONLY          :   OFF
  USE_OPENCV        :   ON
  USE_LEVELDB       :   ON
  USE_LMDB          :   ON
  ALLOW_LMDB_NOLOCK :   OFF

Dependencies:
  BLAS              :   Yes (Atlas)
  Boost             :   Yes (ver. 1.58)
  glog              :   Yes
  gflags            :   Yes
  protobuf          :   Yes (ver. 3.1.0)
  lmdb              :   Yes (ver. 0.9.17)
  LevelDB           :   Yes (ver. 1.18)
  Snappy            :   Yes (ver. 1.1.3)
  OpenCV            :   Yes (ver. 3.1.0)
  CUDA              :   Yes (ver. 8.0)

NVIDIA CUDA:
  Target GPU(s)     :   Manual
  GPU arch(s)       :   sm_30 sm_35 sm_50 sm_60 sm_61 compute_30 compute_35 compute_50 compute_60
  cuDNN             :   Yes (ver. 5.1.5)
  NCCL              :   Yes

Python:
  Interpreter       :   /usr/bin/python2.7 (ver. 2.7.12)
  Libraries         :   /usr/lib/x86_64-linux-gnu/libpython2.7.so (ver 2.7.12)
  NumPy             :   /usr/lib/python2.7/dist-packages/numpy/core/include (ver 1.11.0)

Documentaion:
  Doxygen           :   No
  config_file       :   

Install:
  Install path      :   /code/caffe/build_blog_release/install

The cmake config for windows is as follows:

******************* Caffe Configuration Summary *******************
General:
  Version           :   0.15.14
  Git               :   v0.15.14-331-g3a7ac79-dirty
  System            :   Windows
  C++ compiler      :   C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
  Release CXX flags :   /MD /O2 /Ob2 /DNDEBUG /Zo /Oy- /DWIN32 /D_WINDOWS /W3 /GR /EHsc -std=c++11
  Debug CXX flags   :   /D_DEBUG /MDd /Zi /Ob0 /Od /RTC1 /DWIN32 /D_WINDOWS /W3 /GR /EHsc -std=c++11
  Build type        :   Release

  BUILD_SHARED_LIBS :   ON
  BUILD_python      :   ON
  BUILD_matlab      :   
  BUILD_docs        :   
  CPU_ONLY          :   OFF
  USE_OPENCV        :   ON
  USE_LEVELDB       :   ON
  USE_LMDB          :   ON
  ALLOW_LMDB_NOLOCK :   OFF

Dependencies:
  BLAS              :   Yes (Open)
  Boost             :   Yes (ver. 1.61)
  glog              :   Yes
  gflags            :   Yes
  protobuf          :   Yes (ver. 2.6.1)
  lmdb              :   Yes (ver. 0.9.14)
  LevelDB           :   Yes (ver. 1.2)
  Snappy            :   Yes (ver. 1.1.1)
  OpenCV            :   Yes (ver. 3.1.0)
  CUDA              :   Yes (ver. 8.0)

NVIDIA CUDA:
  Target GPU(s)     :   Manual
  GPU arch(s)       :   sm_30 sm_35 sm_50 sm_52 sm_60 sm_61 compute_30 compute_35 compute_50 compute_60
  cuDNN             :   Yes (ver. 5.1.5)
  NCCL              :   Not found

Python:
  Interpreter       :   C:/Python35/python.exe (ver. 3.5.2)
  Libraries         :   optimized C:/Python35/libs/python35.lib debug C:/Python35/libs/python35_d.lib (ver 3.5.2)
  NumPy             :   C:/Python35/lib/site-packages/numpy/core/include (ver 1.11.2rc1)

Install:
  Install path      :   G:/libs/caffe_eval

Thus the primary difference between these two versions is the inclusion of NCCL on Linux.  I will be recompiling and testing Linux without NCCL in a moment, but I'd like feedback regarding what else could cause such a problem.

**Comment by drnikolaev** [comment]
Hard to say, we don't support windows. You might try 0.16 release
