### ISSUE TITLE
caffe_fp16 inference error

### ISSUE THREAD

**Issue by suhyung** [NVIDIA/caffe#287]
Hi 
I have successfully built your code and got two binary(caffe, caffe_fp16). However, caffe has successfully tested as follows, but caffe_fp16 will generate an error when inference.

./build/tools/caffe time --model=models/bvlc_alexnet/deploy.prototxt -gpu 0 -iterations 100

The error from caffe_fp16 is below.
F1222 19:37:11.971782  4516 cudnn_conv_layer.cpp:138] Check failed: status == CUDNN_STATUS_SUCCESS (9 vs. 0)  CUDNN_STATUS_NOT_SUPPORTED

test script is same with upper
./build/tools/caffe_fp16 time --model=models/bvlc_alexnet/deploy.prototxt -gpu 0 -iterations 100

Currently I am using CUDA 7.5 version. Could you give me any advice to solve this issue?
Thank you!

**Comment by lukeyeager** [comment]
FP16 support is still experimental (thus, the branch is named `experimental/fp16`).

I'd try running with the latest cuDNN and CUDA.

**Comment by suhyung** [comment]
@lukeyeager thank you!
