### ISSUE TITLE
profiling failed

### ISSUE THREAD

**Issue by renganxu** [NVIDIA/caffe#289]
When I used nvprof to profile NVIDIA Caffe in googlenet, the training cannot exceed 600 iterations. But it runs fine without nvprof. I am using NV-Caffe 0.15.13 and nccl 1.2.3. The following output is the error message when profiling:

I0118 14:37:29.375756 26263 sgd_solver.cpp:106] Iteration 600, lr = 0.01
*** Aborted at 1484771849 (unix time) try "date -d @1484771849" if you are using GNU date ***
PC: @     0x2aaac7f33c78 (unknown)
*** SIGSEGV (@0x0) received by PID 26263 (TID 0x2aaaaaaf51c0) from PID 0; stack trace: ***
    @     0x2aaabd03f100 (unknown)
    @     0x2aaac7f33c78 (unknown)
    @     0x2aaac7f03523 (unknown)
    @     0x2aaac7f05e7b (unknown)
    @     0x2aaac734634f (unknown)
    @     0x2aaac73b4b78 (unknown)
    @     0x2aaac73b5018 (unknown)
    @     0x2aaac73f5aac (unknown)
    @     0x2aaac734bb98 (unknown)
    @     0x2aaac734c03e (unknown)
    @     0x2aaac726f9ba (unknown)
    @     0x2aaac726fdba (unknown)
    @     0x2aaac73aed14 (unknown)
    @     0x2aaaab43aa72 (unknown)
    @     0x2aaaab416c51 (unknown)
    @     0x2aaaab440c52 (unknown)
    @     0x2aaaab0429ae caffe::caffe_gpu_memcpy()
    @     0x2aaaab036764 caffe::SoftmaxWithLossLayer<>::Backward_gpu()
    @     0x2aaaaaf9b020 caffe::Net<>::BackwardFromTo()
    @     0x2aaaaaf9b411 caffe::Net<>::Backward()
    @     0x2aaaaafb6a5e caffe::Solver<>::Step()
    @     0x2aaaaafb731e caffe::Solver<>::Solve()
    @     0x2aaaaafae8d7 caffe::P2PSync<>::Run()
    @           0x409d31 train()
    @           0x40764c main
    @     0x2aaabd26db15 __libc_start_main
    @           0x407d81 (unknown)
==26263== Warning: Some profiling data are not recorded. Make sure cudaProfilerStop() or cuProfilerStop() is called before application exit to flush profile data.

Does anyone have the same issue and provide solutions? Thanks.

Regards,
Rengan

**Comment by drnikolaev** [comment]
Can't reproduce this with latest CUDA and 0.16 release
