### ISSUE TITLE
detectnet_transform_layer.hpp(38): error: identifier "UINT8_MAX" is undefined

### ISSUE THREAD

**Issue by IamMegatron2025** [NVIDIA/caffe#290]
Hello, i try to make NVcaffe ,but it shows error
`/home/xxx/NVcaffe/include/caffe/layers/detectnet_transform_layer.hpp(38): error: identifier "UINT8_MAX" is undefined

/home/xxx/NVcaffe/src/caffe/layers/detectnet_transform_layer.cu(407): error: identifier "UINT8_MAX" is undefined

/home/xxx/NVcaffe/src/caffe/layers/detectnet_transform_layer.cu(132): error: identifier "UINT8_MAX" is undefined
          detected during instantiation of "void caffe::DetectNetTransformationLayer<Dtype>::Forward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=float]"
(431): here

/home/xxx/NVcaffe/src/caffe/layers/detectnet_transform_layer.cu(405): error: no instance of function template "caffe::channel_mean_subtraction" matches the argument list
            argument types are: (float *, const uint4, <error-type>, <error-type>, <error-type>)
          detected during instantiation of "void caffe::DetectNetTransformationLayer<Dtype>::Forward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=float]"
(431): here

/home/xxx/NVcaffe/src/caffe/layers/detectnet_transform_layer.cu(405): error: no instance of function template "caffe::channel_mean_subtraction" matches the argument list
            argument types are: (double *, const uint4, <error-type>, <error-type>, <error-type>)
          detected during instantiation of "void caffe::DetectNetTransformationLayer<Dtype>::Forward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=double]"
(431): here

5 errors detected in the compilation of "/tmp/tmpxft_00007c04_00000000-6_detectnet_transform_layer.cpp1.ii".
CMake Error at cuda_compile_generated_detectnet_transform_layer.cu.o.cmake:256 (message):
  Error generating file
  /home/xxx/NVcaffe/build/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_detectnet_transform_layer.cu.o

make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_detectnet_transform_layer.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2
`
How to sovle this error?
Thankyou very much!

**Comment by IamMegatron2025** [comment]
In #207, the method does not work for me. @

**Comment by IamMegatron2025** [comment]
my system is ubuntu12.04

**Comment by drnikolaev** [comment]
@IvyGongoogle can you try 0.16 please?
