### ISSUE TITLE
make runtest error

### ISSUE THREAD

**Issue by shuzhenzhang** [NVIDIA/caffe#293]
The branch I maked is experimental/fp16.

F0224 16:36:33.990233 11623 cudnn_conv_layer.cpp:157] Check failed: status == CUDNN_STATUS_SUCCESS (9 vs. 0)  CUDNN_STATUS_NOT_SUPPORTED
*** Check failure stack trace: ***
    @       0x7fa70f5718  google::LogMessage::Fail()
    @       0x7fa70f7614  google::LogMessage::SendToLog()
    @       0x7fa70f5290  google::LogMessage::Flush()
    @       0x7fa70f7eb4  google::LogMessageFatal::~LogMessageFatal()
    @       0x7fa5a21e94  caffe::CuDNNConvolutionLayer<>::Reshape()
    @           0x588488  caffe::Layer<>::SetUp()
    @           0x9c57a0  caffe::CuDNNConvolutionLayerTest_TestSetupCuDNN_Test<>::TestBody()
    @           0xa74774  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0xa6da7c  testing::Test::Run()
    @           0xa6dbb8  testing::TestInfo::Run()
    @           0xa6dc78  testing::TestCase::Run()
    @           0xa6edd8  testing::internal::UnitTestImpl::RunAllTests()
    @           0xa6f0ec  testing::UnitTest::Run()
    @           0x56c0b8  main
    @       0x7fa55cc8a0  __libc_start_main
Makefile:552: recipe for target 'runtest' failed
make: *** [runtest] Aborted
How to fix this?

**Comment by drnikolaev** [comment]
@shuzhenzhang  Please use 0.16 release with full fp16 support
