### ISSUE TITLE
How to build a 3D CNN net to do image classification?

### ISSUE THREAD

**Issue by m5061125** [NVIDIA/caffe#297]
Hi, I am trying to us 3D CNN to do image classification, does anyone know how build up the networks? I heard CUDNN already support 3D even N-dimensional conv and pool, I really need a guide or example to following, thanks a lot.

**Comment by gheinrich** [comment]
Why don't you try [V-Net](https://github.com/faustomilletari/VNet) and [3D-Caffe](https://github.com/faustomilletari/3D-Caffe). 3D CNN models are memory hungry. 16GB of GPU is recommended there.

**Comment by m5061125** [comment]
Thanks, Gheinrich, it is really help.
