### ISSUE TITLE
"AttributeError" while drawing model

### ISSUE THREAD

**Issue by icyblade** [NVIDIA/caffe#303]
Such error will be raised when trying to draw model with protobuf>2.6.1 (for instance protobuf 3.2.0):

> AttributeError: 'google.protobuf.pyext._message.RepeatedScalarConta' object has no attribute '_values'

There's an issue from original caffe which shows how to solve this problem: https://github.com/BVLC/caffe/issues/3698

**Comment by lukeyeager** [comment]
Could be fixed by locking the protobuf version like so:
https://github.com/NVIDIA/DIGITS/blob/v5.0.0/requirements.txt#L4

Instead of the current open requirement:
https://github.com/NVIDIA/caffe/blob/v0.15.14/python/requirements.txt#L13

**Comment by icyblade** [comment]
I do think that supporting newer version of protobuf is necessary, as we can't stick on older version forever, right?

**Comment by lukeyeager** [comment]
I think that's debatable. Fixing dependencies to versions supported by the Ubuntu LTS versions gives nice stability. 

However, at least DIGITS is clear in it's expectations. This repo should probably be either updated to allow the newer version or the restriction should be marked clearly in `requirements.txt`.

**Comment by icyblade** [comment]
Well, you're a persuasive guy. I didn't consider system support before.
