### ISSUE TITLE
cuDNN 6 support

### ISSUE THREAD

**Issue by MyVanitar** [NVIDIA/caffe#306]
Hi,

Have you considered adding the cuDNN 6 support for the repository?

**Comment by lukeyeager** [comment]
Looks like @drnikolaev already did some of the work in `caffe-0.15`: https://github.com/NVIDIA/caffe/commit/e1c5420d4bc71a5d2c76f6951c104248bde10804

But @flx42 did a little more to enable v6 in upstream: https://github.com/BVLC/caffe/commit/0096fe3d270a4833479076e18492de8b28564c80

**Comment by drnikolaev** [comment]
It's here: https://github.com/NVIDIA/caffe/tree/caffe-0.16

**Comment by MyVanitar** [comment]
@drnikolaev 

Bingo!
