### ISSUE TITLE
caffe 0.16 multi-gpu cant save snapshot

### ISSUE THREAD

**Issue by RSly** [NVIDIA/caffe#309]
hi 
just testing caffe0.16 and using digits to train a model with 2 gpus leads to this error at 1st snapshot saving:
[with 1 gpu, there is no problem]

I0426 20:35:34.797068 10668 sgd_solver.cpp:108] Iteration 1336, lr = 0.000983103
I0426 20:35:36.443382 10668 solver.cpp:572] Snapshotting to binary proto file snapshot_iter_1341.caffemodel
F0426 20:35:38.413489 10668 io.cpp:69] Check failed: proto.SerializeToOstream(&output)
*** Check failure stack trace: ***
@     0x7fcfbccaadaa  (unknown)
@     0x7fcfbccaace4  (unknown)
@     0x7fcfbccaa6e6  (unknown)
@     0x7fcfbccad687  (unknown)
@     0x7fcfbd4a0217  caffe::WriteProtoToBinaryFile()
@     0x7fcfbd4dbefd  caffe::Solver::SnapshotToBinaryProto()
@     0x7fcfbd4dbfc0  caffe::Solver::Snapshot()
@     0x7fcfbd4dd8de  caffe::Solver::Step()
@     0x7fcfbd4ddda0  caffe::Solver::Solve()
@     0x7fcfbd433a16  caffe::P2PSync::InternalThreadEntry()
@     0x7fcfbd43f22e  caffe::InternalThread::entry()
@     0x7fcfbd43fe44  boost::detail::thread_data<>::run()
@     0x7fcfbb27fa4a  (unknown)
@     0x7fcfbb05e184  start_thread
@     0x7fcfbb58437d  (unknown)
@              (nil)  (unknown)

**Comment by lukeyeager** [comment]
See https://github.com/NVIDIA/caffe/issues/9 and https://github.com/NVIDIA/DIGITS/issues/84. Either you're running out of disk space, or you're hitting the same intermittent issue that several others have hit. I've never been able to reproduce it.

**Comment by drnikolaev** [comment]
Please also check https://github.com/BVLC/caffe/issues/1394

**Comment by RSly** [comment]
Thanks, I will check the above and will give a feedback

**Comment by RSly** [comment]
I could confirm that the problem came from the lack of disk space.
in summery the causes can be:
*no disk space
*no write permissions
*the destination folder doesn't exist

I suggest a better message for error handling can be very helpful in this case.

if not, we can close this issue.
thanks a lot

**Comment by drnikolaev** [comment]
Added diagnostics to the next version. Thanks for reporting.
