### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by fslzj** [NVIDIA/caffe#311]
AR -o .build_release/lib/libcaffe-nv.a
LD -o .build_release/lib/libcaffe-nv.so.0.16.0
/usr/bin/ld: cannot find -lnvidia-ml
/usr/bin/ld: cannot find -lopenblas
collect2: error: ld returned 1 exit status
Makefile:590: recipe for target '.build_release/lib/libcaffe-nv.so.0.16.0' failed

I can compile 0.15-version successfully, but 0.16-version.

**Comment by drnikolaev** [comment]
@fslzj You either need to install libnvidia-ml.so (it comes with a driver) or disable it by setting NO_NVML := 1 (you'd loose CPU affinity feature in this case though).

**Comment by thatguymike** [comment]
Note, CPU affinity is really only helpful in NUMA systems.

**Comment by fslzj** [comment]
Thank you, I add NO_NVML:=1 and set BLAS:= atlas in makefile.config
