### ISSUE TITLE
Python: caffe has no attribute 'NCCL'

### ISSUE THREAD

**Issue by VasLem** [NVIDIA/caffe#318]
I guess this is a matter of different versions, but since January (https://github.com/BVLC/caffe/pull/4563) caffe from BVLC has a NCCL module inside _caffe.py . I dived inside Python wrappers but I did not find any such wrapper for NCCL inside nv-caffe. Are there any plans to implement this module ? I ask, because CUDA users face a problem using NCCL module from original caffe, whereas NCCL in nv-caffe is tailored for CUDA (as expected for a NVIDIA library).  Furthermore, by using such module, one could do multiGPU training using Python code.

**Comment by drnikolaev** [comment]
We support multiGPU training in pyCaffe starting from 0.16. Please give it a try.
