### ISSUE TITLE
How to use fp16 + cudnn6.0 with tx1 on branch caffe-0.16 

### ISSUE THREAD

**Issue by lbin** [NVIDIA/caffe#321]
So exciting to see some updates for fp16. For now tx1 only support cudnn5.1. If I want to use fp16+cudnn, where I can find a guideline?

**Comment by borisgin** [comment]
You can switch your model to float16 by adding a few lines to model.prototxt. 
For example
 name "MyNet"
 default_forward_type:  FLOAT16
 default_backward_type: FLOAT16
 default_forward_math:  FLOAT
 default_backward_math: FLOAT
One can overwrite defualt type and math for particular layer. 
For example:
 layer {
   name: "conv1"
   type: "Convolution"
   forward_type:  FLOAT16
   backward_type: FLOAT16
   forward_math:  FLOAT16
   backward_math: FLOAT
   ...
There are a lot of examples under models/....

**Comment by lbin** [comment]
@borisgin  Yes, I know how to use fp16. But cudnn6.0 does not support TX1 yet. When I built caffe-0.16 with use_cudnn=1, I got some errors like #error "NVCaffe 0.16 and higher requires CuDNN version 6.0.0 or higher"

**Comment by drnikolaev** [comment]
@lbin Unfortunately, NVCaffe 0.16 requires CuDNN 6 due to limitations of previous version.

**Comment by lbin** [comment]
@drnikolaev  Thanks for your reply. After I comment some codes relate with cudnn in caffe/util/cudnn.h, caffe-0.16 with cudnn5.1 can be complied on Tx1, but the speed is a problem. I am waiting good news from Tegra team to support cudnn6
