### ISSUE TITLE
bug in cudnn_batch_norm_layer.cu

### ISSUE THREAD

**Issue by fslzj** [NVIDIA/caffe#322]
I use nvidia-caffe to train my model and always get strange result. I find a possible reason that some bugs may be in cudnn_batch_norm_layer.cu,  In cudnnBatchNormalizationForwardTraining(), cudnnBatchNormalizationForwardInference() and cudnnBatchNormalizationBackward(), some parameters are always “bottom_desc_”. Should some of them be "top_desc_"s?

**Comment by drnikolaev** [comment]
@fslzj please have a look at the last comment (BN sample) of #307 (I hope it's useful).
