### ISSUE TITLE
error code -11 when using python layer

### ISSUE THREAD

**Issue by WilliamJuel** [NVIDIA/caffe#323]
I noticed  that since I pulled the latest nvidia caffe-0.16 code I cannot use my python layer that I have used in 0.15. I get this error from digits: ERROR: error code -11

and on the box it says:

Network initialization done.
Solver scaffolding done.
Starting Optimization
Solving
Learning Rate Policy: fixed
Iteration 0, Testing net (#0)
Ignoring source layer train-data
NVML initialized on thread 140484002506496
NVML succeeded to set CPU affinity on device 0

[caffe_output.txt](https://github.com/NVIDIA/caffe/files/972795/caffe_output.txt)

[python_layer.txt](https://github.com/NVIDIA/caffe/files/972798/python_layer.txt)

This has worked for me in nvidia caffe-0.15 and digits 5.

I use:
Digits 5.0
CUDA 8
Cudnn 6.0

**Comment by WilliamJuel** [comment]
@drnikolaev I just saw you labeled this as a bug. Have you tried to reproduce the error or is it a well known problem?

**Comment by drnikolaev** [comment]
@WilliamJuel There was very similar crash which is now fixed. Please pull the latest code and retry. If crash is still reproducible on your side please tell me what OpenCV version you link Caffe with.

**Comment by WilliamJuel** [comment]
@drnikolaev Okay, so I did the testing. I can confirm that with opencv 3.2.0-dev I get the above error and with opencv 2.4.9.1 the python layer works like always. 

 I am pretty sure that when I was on the 0.15 branch I used opencv 3.2.0-dev and my python layer worked.

**Comment by drnikolaev** [comment]
@WilliamJuel thank you. I'll check 3.2.0

**Comment by WilliamJuel** [comment]
@drnikolaev Thank you very much. I will close this since the issue for me is fixed. I only use 3.2.0 for some specific functions and it is no hurdle for me to swap around for which OpenCV version I link to python.
