### ISSUE TITLE
Change Stride in Detectnet

### ISSUE THREAD

**Issue by user7077** [NVIDIA/caffe#324]
Hi all,

I am trying to detect objects using detectnet. I was already successfull with certain objects but now I'm trying to detect objects that are smaller than 50x50 pixels. I tried to scale my original images in order to make the objects bigger but then they won't fit into memory anymore. 
I thought the Crop Size in Data Transformations would help me to process large images by cropping them but I guess I got that wrong since they did still not fit into memory.

I have read that in order to detect small objects one would need to change the stride of the network.
My first problem is: which stride must I change? There is a stride in the 'Data transformation layers' that is 16 by default.  There are also strides in the convolutional part. They are either 1 or 2. 
When I simply set the stride from 16 to 8 I get an error. 

Is there a systematic approach on where and how to change the stride instead of trial and error until I do no longer get errors?

Thanks for your help

**Comment by drnikolaev** [comment]
Look at ALexNet for example. It sets stride:=4 in the very first Convolution layer. Worth trying.
