### ISSUE TITLE
 GPUMemory::Manager GPU initialization

### ISSUE THREAD

**Issue by RSly** [NVIDIA/caffe#326]
Hi,
on caffe 0.16 the GPUMemory::Manager doesnt care about caffe.set_device(3), and it initializes ALL the GPUs. 

This is problematic when other gpus are already in use and  we dont want to use them for any new task.
It seems like a bug, or we need a way to tell the GPUMemory::Manager to only initialize gpu 3 in this example.

**Comment by drnikolaev** [comment]
#332 - `set_device` call now initializes one device. To initialize multiple devices please use new function `set_devices`
