### ISSUE TITLE
Check failed: error == cudaSuccess (3 vs. 0) initialization error

### ISSUE THREAD

**Issue by zhangfang615** [NVIDIA/caffe#336]
Hi,

I just updated caffe to version 0.16. When I ran a multi-process job with GPU mode, it gave the error: Check failed: error == cudaSuccess (3 vs. 0) initialization error

Before the update, the job could ran successfully.

What should I do in this situation?

Thanks!

Fang

**Comment by drnikolaev** [comment]
Hi @zhangfang615 please paste the log and tell us what CUDA and CuDNN version you have.
