### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by shuzhenzhang** [NVIDIA/caffe#338]
Hi,
When I  make caffe-0.16 on tx1, i get this error(The cuda version: cuda8.0, and cudnn version: cudnn6.0.):
AR -o .build_release/lib/libcaffe-nv.a
LD -o .build_release/lib/libcaffe-nv.so.0.16.0
/usr/bin/ld: cannot find -lnvidia-ml
/usr/bin/ld: skipping incompatible /usr/local/cuda/lib64/libcudnn.so when searching for -lcudnn
collect2: error: ld returned 1 exit status
Makefile:590: recipe for target '.build_release/lib/libcaffe-nv.so.0.16.0' failed
make: *** [.build_release/lib/libcaffe-nv.so.0.16.0] Error 1

**Comment by drnikolaev** [comment]
Hi @shuzhenzhang seems you are trying to link amd64 arch library which is not compatible to TX1. We are still working on v6 support for it. So far, you can try JetPack 3.0.

**Comment by shuzhenzhang** [comment]
Thanks for your reply @drnikolaev .I will try JetPack3.0.
