### ISSUE TITLE
May be some bugs of cuda8

### ISSUE THREAD

**Issue by westlife35** [NVIDIA/caffe#340]
Recently, I just update my demo in windows.
 I try caffe-ms and use caffe.binding.lib to do some demo. I do detection and recongnition in win10. And I find some problems with cuda8.
    First, I use MTCNN in win10(cuda8,GTX 980). The speed on CPU is stable(280 ms for 640*480 image), but the speed on GPU is unstable(20ms,2000ms or even 4000ms per image, and the slow part is not stable,meaning 12net,24net or 48net, all are possilble slow). What's more, same things happen on win10(cuda8,GTX1080Ti).
    Second, I do feature extraction using caffe.binding.lib. The speed on CPU is stable, but the speed on GPU is unstable(it is 0.5s,40s,0.1s,0.1s,0.1s... on win10,cuda8,GTX980 and 0.5s,20s,0.1s,0.1s,0.1s... on win10,cuda8,GTX1080Ti).
   
     And I using cuda6.5 and the old kind caffe of happenear in github,meaning on caffe.binding.lib. It is a old version of your in 2015. The speed is stable on GPU(just like 0.5s,0.1s,0.1s for feature extraction and I do not do MTCNN on it). 

     In addition, I do the comparision of (cuda8+vs2015(result is that:0.5s,10s,0.2s,0.2s,...) vs cuda7.5+vs2012(result is that: 0.5s, 0.2s,0.2s,...) in the same machine with GTX1080Ti. And the result is obvious: may be there are some bugs in cuda8).

**Comment by drnikolaev** [comment]
Hi @westlife35 , seems like wrong thread, NVCaffe doesn't support Windows
