### ISSUE TITLE
Slow training with docker

### ISSUE THREAD

**Issue by sergey-serebryakov** [NVIDIA/caffe#346]
Hi!
I've been observing pretty low numbers training several nets with latest version (0.16.1) inside docker containers.  The machine is an 8 PCIe-based P100s, topology 8:1. Host OS RedHat Enterprise 7.3, driver version 367.48. I am using docker ce 17.03.1, nvidia docker version 1.0.1-1. This is how Dockerfile looks like:
```
FROM nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04

RUN apt-get update && apt-get install -y --no-install-recommends \
        numactl \
        build-essential \
        cmake \
        git \
        wget \
        libatlas-base-dev \
        libboost-all-dev \
        libgflags-dev \
        libgoogle-glog-dev \
        libhdf5-serial-dev \
        libleveldb-dev \
        liblmdb-dev \
        libopencv-dev \
        libprotobuf-dev \
        libsnappy-dev \
        protobuf-compiler \
        python-dev \
        python-numpy \
        python-pip \
        python-scipy && \
    rm -rf /var/lib/apt/lists/*

ENV CAFFE_ROOT=/opt/caffe
WORKDIR $CAFFE_ROOT


ENV CLONE_TAG=v0.16.1

RUN git clone -b ${CLONE_TAG} --depth 1 https://github.com/NVIDIA/caffe . && \
    pip install --upgrade pip && \
    cd python && for req in $(cat requirements.txt) pydot; do pip install $req; done && pip install scikit-image && cd .. && \
    git clone https://github.com/NVIDIA/nccl.git && cd nccl && make -j install && cd .. && rm -rf nccl && \
    mkdir build && cd build && \
    cmake -DUSE_CUDNN=1 -DUSE_NCCL=1 -DNDEBUG=1 -DNVML_FOUND=1 -DNVML_LIBRARY=/usr/local/cuda/lib64/stubs/libnvidia-ml.so -DNVML_INCLUDE_DIR=/usr/local/cuda/include .. && \
    make -j"$(nproc)"

ENV PYCAFFE_ROOT $CAFFE_ROOT/python
ENV PYTHONPATH $PYCAFFE_ROOT:$PYTHONPATH
ENV PATH $CAFFE_ROOT/build/tools:$PYCAFFE_ROOT:$PATH
RUN echo "$CAFFE_ROOT/build/lib" >> /etc/ld.so.conf.d/caffe.conf && ldconfig

WORKDIR /workspace
```
With GoogleNet and batch size 128 I get 207 img/s with one GPU which seems to be really slow. Caffe2 (0.6.0) can train at 417 img/sec rate and BVLC Caffe at 419 img/sec. TF 1.1 trains at 510 img/secs. Every framework runs inside docker containers. Synthetic data is used. 

There is something obviously wrong with my set up. I will investigate this in the next couple days. Meanwhile, I would like to ask if, maybe, there is something I need to pay attention to? Thanks.

PS I have not experimented with previous versions and it's a little bit complicated to run frameworks outside docker, so I cannot provide these numbers.

**Comment by drnikolaev** [comment]
Hi @sergey-serebryakov , I suggest to upgrade to 17.05 release, it has quite visible multi-GPU performance improvements.
Besides that, if possible, could you clarify how your P100 boards are connected? Do you use NVLink? If not, this might be the issue. After each iteration we have to perform gradients reduction by exchanging data between all GPUs. This is expensive for PCIe connection. Two ways to check it:
1. Run 100-200 iterations under `nvprof` and see how much is taken by `AllReduce` kernel. 
2. Run the same training on 4 GPUs. Does it scale?

**Comment by sergey-serebryakov** [comment]
@drnikolaev Thanks, I will try. I've got PCIe cards. Two processor system configured as 8:1 (8 GPUs connected to one CPU). 
However, the problem is that I get strange results with just one GPU. This is my problem. Friend of mine on same system, configured though as 4:1 get expected performance (on one GPU) running in a non-docker environment. 
This makes me think now that I do need to try to run NVIDIA caffe in a non docker environment as well. If I'll get expected performance, then there is something wrong with caffe + docker setup.

**Comment by sergey-serebryakov** [comment]
Ok, there was a problem with one layer, my bad. Nothing to do with Caffe or Docker.
