### ISSUE TITLE
matcaffe doesn't compile 

### ISSUE THREAD

**Issue by choosehappy** [NVIDIA/caffe#351]
when running "make matcaffe" i get the following error:

`/opt/caffe-nv-new/matlab/+caffe/private/caffe_.cpp: In function âvoid get_solver(int, mxArray**, int, const mxArray**)â:
/opt/caffe-nv-new/matlab/+caffe/private/caffe_.cpp:192:63: error: too many arguments to function âcaffe::SolverParameter caffe::ReadSolverParamsFromTextFileOrDie(const string&)â
   ReadSolverParamsFromTextFileOrDie(solver_file, &solver_param);
                                                               ^
In file included from ./include/caffe/caffe.hpp:19:0,
                 from /opt/caffe-nv-new/matlab/+caffe/private/caffe_.cpp:18:
./include/caffe/util/upgrade_proto.hpp:77:17: note: declared here
 SolverParameter ReadSolverParamsFromTextFileOrDie(const string& param_file);
`

which makes sense as the upgrade_proto.hpp from the official repo now has 2 parameters, while this fork only has 1:

https://github.com/BVLC/caffe/blob/f40cf46a7131f8e43564e11a650d45a5e4b466a6/include/caffe/util/upgrade_proto.hpp#L83

versus:

https://github.com/NVIDIA/caffe/blob/caffe-0.16/include/caffe/util/upgrade_proto.hpp#L77

**Comment by choosehappy** [comment]
by the way, I did try simply using the 2 parameter version by copying over the needed files from the official repo's version, but one thing lead to another and things started getting a bit out of hand :)  

I'm hoping that you have a more elegant way of catching up with the commits?

**Comment by drnikolaev** [comment]
@choosehappy thank you. We are working on the fix.

**Comment by drnikolaev** [comment]
@choosehappy Fixed, you may try it here: https://github.com/drnikolaev/caffe/tree/caffe-0.16
FInal release is coming soon.

**Comment by drnikolaev** [comment]
Fixed in 0.16.4
