### ISSUE TITLE
How do I use the gpu fp16 mode to run the model trained by previous caffe?

### ISSUE THREAD

**Issue by fengshikun** [NVIDIA/caffe#352]
Is there any tutorial or sample code to show how to run fp16 mode? Thanks!

**Comment by fengshikun** [comment]
In previous version: I can test the model this way:
```
Caffe::set_mode(Caffe::GPU);
/* Load the network. */
net_.reset(new Net<float>(model_file, TEST));
net_->CopyTrainedLayersFrom(trained_file);
/*fill the data */
std::vector<Blob<float> *> outputs = net_->Forward();
```

How to use fp16 model in similar way? thanks!

**Comment by drnikolaev** [comment]
Hi @fengshikun did you try to replace `float` by `float16`?

**Comment by shuyu0815** [comment]
@drnikolaev  
If using the branch master version(experimental/fp16),how to use fp16 mode in classification.cpp ?

Thanks !

**Comment by drnikolaev** [comment]
@shuyu0815 please use https://github.com/NVIDIA/caffe/tree/caffe-0.16
