### ISSUE TITLE
where to get cudnn v6 for TX1

### ISSUE THREAD

**Issue by gangm** [NVIDIA/caffe#354]
hello,

Is caffe v0.16 only support cudnn v6?
I want to compile caffe v0.16 in my TX1 board, but i do not know where to get cudnn v6 for TX1, can you help for this?
thanks very much~

**Comment by drnikolaev** [comment]
Hi @gangm so far it supports v6 only, we are working on back support...

**Comment by bfreskura** [comment]
Hi @drnikolaev, can you give a rough estimate when will the back support be implemented?

**Comment by drnikolaev** [comment]
Hi @gangm , please try JetPak 3.1 https://developer.nvidia.com/embedded/jetpack
