### ISSUE TITLE
make runtest error

### ISSUE THREAD

**Issue by tanjie860110** [NVIDIA/caffe#355]
I make and make test all ok when i compile caffe 0.16,but make runtest error happened :
3 tests from ThresholdLayerTest/4 (1 ms total)

[----------] 8 tests from RMSPropSolverTest/1, where TypeParam = caffe::CPUDevice<double>
[ RUN      ] RMSPropSolverTest/1.TestRMSPropLeastSquaresUpdateWithWeightDecay
F0616 11:54:58.936892 26537 benchmark.cpp:18] Check failed: error == cudaSuccess (33 vs. 0)  invalid resource handle
*** Check failure stack trace: ***
    @     0x7fc37d7185cd  google::LogMessage::Fail()
    @     0x7fc37d71a433  google::LogMessage::SendToLog()
    @     0x7fc37d71815b  google::LogMessage::Flush()
    @     0x7fc37d71ae1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fc37ab6b0f8  caffe::Timer::~Timer()
    @     0x7fc37a837a79  caffe::Solver::~Solver()
    @           0x643082  caffe::RMSPropSolver<>::~RMSPropSolver()
    @           0x6207da  boost::detail::sp_counted_base::release()
    @           0x664fcd  caffe::RMSPropSolverTest<>::InitSolver()
    @           0x66b36c  caffe::GradientBasedSolverTest<>::TestLeastSquaresUpdate()
    @           0xa6bfa3  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0xa6591a  testing::Test::Run()
    @           0xa65a68  testing::TestInfo::Run()
    @           0xa65b45  testing::TestCase::Run()
    @           0xa65dff  testing::internal::UnitTestImpl::RunAllTests()
    @           0xa66133  testing::UnitTest::Run()
    @           0x49a629  main
    @     0x7fc37996b830  __libc_start_main
    @           0x4a5659  _start
    @              (nil)  (unknown)
Makefile:550: recipe for target 'runtest' failed
make: *** [runtest] Aborted (core dumped)

what is wrong?

**Comment by drnikolaev** [comment]
Could you execute `export CUDA_VISIBLE_DEVICES=0` and re-run the tests please?

**Comment by tanjie860110** [comment]
@drnikolaev i do it,but the result is all the same.
8 tests from RMSPropSolverTest/1, where TypeParam = caffe::CPUDevice<double>
[ RUN      ] RMSPropSolverTest/1.TestSnapshotShare
F0619 10:04:14.876730 26547 benchmark.cpp:30] Check failed: error == cudaSuccess (33 vs. 0)  invalid resource handle
*** Check failure stack trace: ***
    @     0x7f172edc35cd  google::LogMessage::Fail()
    @     0x7f172edc5433  google::LogMessage::SendToLog()
    @     0x7f172edc315b  google::LogMessage::Flush()
    @     0x7f172edc5e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f172c216d21  caffe::Timer::Start()
    @     0x7f172bee6cbf  caffe::Solver::Step()
    @     0x7f172bee815b  caffe::Solver::Solve()
    @           0x64d90b  caffe::GradientBasedSolverTest<>::RunLeastSquaresSolver()
    @           0x64dad3  caffe::GradientBasedSolverTest<>::TestSnapshot()
    @           0x64f9f3  caffe::RMSPropSolverTest_TestSnapshotShare_Test<>::TestBody()
    @           0xa6bfa3  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0xa6591a  testing::Test::Run()
    @           0xa65a68  testing::TestInfo::Run()
    @           0xa65b45  testing::TestCase::Run()
    @           0xa65dff  testing::internal::UnitTestImpl::RunAllTests()
    @           0xa66133  testing::UnitTest::Run()
    @           0x49a629  main
    @     0x7f172b016830  __libc_start_main
    @           0x4a5659  _start
    @              (nil)  (unknown)
Makefile:550: recipe for target 'runtest' failed
make: *** [runtest] Aborted (core dumped)

**Comment by drnikolaev** [comment]
@tanjie860110 does v0.16.3 fail in the same way?
