### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by tanjie860110** [NVIDIA/caffe#356]
when i train with caffe 0.16,use the batch_size 5,10,50,100 and so on.All train have the same error:(my GPU is GTX 1080Ti)
09:03:19.315853 11806 net.cpp:106] Using FLOAT16 as default forward math type
I0617 09:03:19.315860 11806 net.cpp:112] Using FLOAT16 as default backward math type
I0617 09:03:19.315865 11806 layer_factory.hpp:136] Creating layer 'input' of type 'Input'
I0617 09:03:19.315867 11806 layer_factory.hpp:148] Layer's types are Ftype:FLOAT16 Btype:FLOAT16 Fmath:FLOAT16 Bmath:FLOAT16
I0617 09:03:19.315877 11806 net.cpp:175] Created Layer input (0)
I0617 09:03:19.315886 11806 net.cpp:521] input -> target
I0617 09:03:19.315903 11806 net.cpp:521] input -> image
I0617 09:03:19.315910 11806 net.cpp:521] input -> bbox
I0617 09:03:19.316540 11806 net.cpp:236] Setting up input
I0617 09:03:19.316561 11806 net.cpp:243] TRAIN Top shape for layer 0 'input' 1 3 227 227 (154587)
I0617 09:03:19.316570 11806 net.cpp:243] TRAIN Top shape for layer 0 'input' 1 3 227 227 (154587)
I0617 09:03:19.316573 11806 net.cpp:243] TRAIN Top shape for layer 0 'input' 1 4 1 1 (4)
I0617 09:03:19.316577 11806 layer_factory.hpp:136] Creating layer 'conv1' of type 'Convolution'
I0617 09:03:19.316581 11806 layer_factory.hpp:148] Layer's types are Ftype:FLOAT16 Btype:FLOAT16 Fmath:FLOAT16 Bmath:FLOAT16
.
.
.
.
.
I0617 13:06:40.406309 11806 solver.cpp:322]     Train net output #0: loss = nan (* 1 = nan loss)
I0617 13:06:41.896098 22750 device_alternate.hpp:116] NVML initialized on thread 139965375694592
I0617 13:06:42.241075 11806 solver.cpp:300] Iteration 7719 (0.545042 iter/s, 1.83472s/20 iter), loss = nan
I0617 13:06:42.241133 11806 solver.cpp:322]     Train net output #0: loss = nan (* 1 = nan loss)
I0617 13:06:43.751000 22751 device_alternate.hpp:116] NVML initialized on thread 139965375694592
I0617 13:06:44.089124 11806 solver.cpp:300] Iteration 7720 (0.54114 iter/s, 1.84795s/20 iter), loss = nan
I0617 13:06:44.089179 11806 solver.cpp:322]     Train net output #0: loss = nan (* 1 = nan loss)
I0617 13:06:44.089185 11806 sgd_solver.cpp:108] Iteration 7720, lr = 1e-06
I0617 13:06:45.644193 22752 device_alternate.hpp:116] NVML initialized on thread 139965375694592
I0617 13:06:45.989641 11806 solver.cpp:300] Iteration 7721 (0.5262 iter/s, 1.90042s/20 iter), loss = nan
I0617 13:06:45.989696 11806 solver.cpp:322]     Train net output #0: loss = nan (* 1 = nan loss)
I0617 13:06:47.402498 22753 device_alternate.hpp:116] NVML initialized on thread 139965375694592
F0617 13:06:47.403848 22753 common.cpp:165] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
    @     0x7f4c866775cd  google::LogMessage::Fail()
    @     0x7f4c86679433  google::LogMessage::SendToLog()
    @     0x7f4c8667715b  google::LogMessage::Flush()
    @     0x7f4c86679e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f4c8736ce3e  caffe::CudaStream::CudaStream()
    @     0x7f4c8736e83f  caffe::Caffe::device_pstream()
    @     0x7f4c8736eaf4  caffe::Caffe::device_curand_generator()
    @     0x7f4c87371e07  caffe::Caffe::set_random_seed()
    @     0x7f4c873a6722  caffe::Solver::Reduce()
    @     0x7f4c78da25d5  (unknown)
    @     0x7f4c852b86ba  start_thread
    @     0x7f4c855d482d  clone
    @              (nil)  (unknown)

**Comment by tanjie860110** [comment]
my GPU is GTX 1080Ti

**Comment by drnikolaev** [comment]
Hi @tanjie860110 thanks for reporting. To reproduce this we need to know what model you train and on what dataset. The best way is to attach your prototxt files to this issue.

**Comment by tanjie860110** [comment]
@drnikolaev the prototxt i use is 
[solver.txt](https://github.com/NVIDIA/caffe/files/1083622/solver.txt)
[tracker.txt](https://github.com/NVIDIA/caffe/files/1083623/tracker.txt)

and dataset is ILSVRC2014 image data and alov300, thank you.

**Comment by borisgin** [comment]
@tanjie860110, I looked at the log, and noticed that 1) you got nan as loss, and out-of-memory. The first can be related to the fact that GTX 1080Ti has no real float16 support, Can you please rerun with FLOAT default math? To get rif of out-of memory I would suggest to reduce batch size.

**Comment by tanjie860110** [comment]
@borisgin, I modify float16 to float and reduce batch size,loss is correct but out of memory still exist.

**Comment by borisgin** [comment]
Can you attach your train_val.prototxt and complete log please?

**Comment by drnikolaev** [comment]
@tanjie860110 could you also try 0.16.2 release?
