### ISSUE TITLE
How to convert caffemodel fp32 to fp16?

### ISSUE THREAD

**Issue by Timo-hab** [NVIDIA/caffe#358]
Hi Sergei,

thanks for your work here. It is really helpful.
I just want to ask, if it is possible to convert a caffemodel fp32 to fp16? 
I have a caffemodel (fp32) and I want to speed it up by using NVIDIA/caffe with the fp16 support.
I am looking forward to your answer. 

Thanks
Timo-hab

**Comment by RSly** [comment]
hi @TimZaman take a look at here
https://github.com/NVIDIA/caffe/issues/344
it says
> You can set NVCaffe-0.16 to fp16 mode and feed your 0.15's fp32 model to it

However I am not sure how exactly to set the flag 'nvcaffe f16 mode'

**Comment by TimoSaemann** [comment]
Thanks @RSly

**Comment by Timo-hab** [comment]
Thanks @RSly
