### ISSUE TITLE
caffe train hangs when I set max_ter to 0 in solver params

### ISSUE THREAD

**Issue by mathmanu** [NVIDIA/caffe#360]
caffe train 
hangs when I set max_ter to 0 in solver params

I am using caffe-0.16.

Thanks.

**Comment by drnikolaev** [comment]
Hi @mathmanu thank you, reproduced. What exactly do we mean when we set it to 0?

**Comment by mathmanu** [comment]
In the solver.prototxt file I set
max_iter: 0

What I was trying to do was the following:

I have a training procedure that involves multiple rounds of training. I wanted to disable a specific round of training by setting its max_iter to 0. 

This is not a critical use case. Just filed the issue, in case it helps finding some bigger issue that might be related to it. I occasionally get some random crashes - but that is not repeatable at all.

Thanks,
Manu.

**Comment by drnikolaev** [comment]
Fixed in 0.16.3
