### ISSUE TITLE
out of memory after the first epoch (caffe 0.16.2)

### ISSUE THREAD

**Issue by RSly** [NVIDIA/caffe#361]
hi,

I am trying out the latest release 0. 16.2. 
I noticed that in training after the first epoch and at Test time we get an  'out of memory error' and it crashes. FYI, exact same tests work fine on caffe 0.16.1

I0623 11:32:24.286512 19711 solver.cpp:451] Iteration 1045, Testing net (#0)
F0623 11:32:24.873178 19713 gpu_memory.hpp:38] Failed to allocate 49152000 bytes on device 2. Total memory: 12799574016, Free: 21430272, dev_info[2]: total=12799574016 free=21430272
*** Check failure stack trace: ***
    @     0x7f9cde65ddaa  (unknown)
    @     0x7f9cde65dce4  (unknown)
    @     0x7f9cde65d6e6  (unknown)
    @     0x7f9cde660687  (unknown)
    @     0x7f9cdee1af60  caffe::GPUMemory::allocate<>()
    @     0x7f9cdee19cda  caffe::SyncedMemory::to_gpu()
    @     0x7f9cdee1abc9  caffe::SyncedMemory::mutable_gpu_data()
    @     0x7f9cdef5e8bc  caffe::CuDNNConvolutionLayer<>::Reshape()
    @     0x7f9cdee89c0b  caffe::Layer<>::Forward()
    @     0x7f9cdee3aeae  caffe::Net::ForwardFromTo()
    @     0x7f9cdee3aff7  caffe::Net::Forward()
    @     0x7f9cdee9e672  caffe::Solver::Test()
    @     0x7f9cdee9f00c  caffe::Solver::TestAll()
    @     0x7f9cdee9f36c  caffe::Solver::Step()
    @     0x7f9cdeea0245  caffe::Solver::Solve()
    @     0x7f9cdedfd167  caffe::P2PSync::InternalThreadEntry()
    @     0x7f9cdee083bb  caffe::InternalThread::entry()
    @     0x7f9cdee09074  boost::detail::thread_data<>::run()
    @     0x7f9cdcc2aa4a  (unknown)
    @     0x7f9cdca09184  start_thread
    @     0x7f9cdcf2f37d  (unknown)
    @              (nil)  (unknown)

**Comment by drnikolaev** [comment]
Hi @RSly - do you read data from snapshot or start training from scratch?

**Comment by RSly** [comment]
I tried new trainings from scrach with pretrained imagenet weights.

if needed I can also try with no weight initialization

**Comment by RSly** [comment]
here are more messages, maybe it can help.
my understanding is that it continues to keep the training images in the memory and doesnt do the clean up before uploading test images.

Testing net (#0)
F0627 15:13:49.775660 14308 gpu_memory.hpp:38] Failed to allocate 4153344 bytes on device 2. Total memory: 12799574016, Free: 3342336, dev_info[2]: total=12799574016 free=3342336
*** Check failure stack trace: ***
    @     0x7f9755e23daa  (unknown)
    @     0x7f9755e23ce4  (unknown)
    @     0x7f9755e236e6  (unknown)
    @     0x7f9755e26687  (unknown)
F0627 15:13:49.795454 14309 gpu_memory.hpp:38] Failed to allocate 4153344 bytes on device 3. Total memory: 12799574016, Free: 3342336, dev_info[3]: total=12799574016 free=3342336
*** Check failure stack trace: ***
    @     0x7f9755e23daa  (unknown)
    @     0x7f97565e0f60  caffe::GPUMemory::allocate<>()
    @     0x7f9755e23ce4  (unknown)
    @     0x7f97565dfcda  caffe::SyncedMemory::to_gpu()
    @     0x7f9755e236e6  (unknown)
    @     0x7f97565e0bc9  caffe::SyncedMemory::mutable_gpu_data()
    @     0x7f9755e26687  (unknown)
    @     0x7f97567248bc  caffe::CuDNNConvolutionLayer<>::Reshape()
    @     0x7f97565e0f60  caffe::GPUMemory::allocate<>()
    @     0x7f975664fc0b  caffe::Layer<>::Forward()
    @     0x7f97565dfcda  caffe::SyncedMemory::to_gpu()
    @     0x7f9756600eae  caffe::Net::ForwardFromTo()
    @     0x7f97565e0bc9  caffe::SyncedMemory::mutable_gpu_data()
    @     0x7f9756600ff7  caffe::Net::Forward()
    @     0x7f97567248bc  caffe::CuDNNConvolutionLayer<>::Reshape()
    @     0x7f9756664672  caffe::Solver::Test()
    @     0x7f975664fc0b  caffe::Layer<>::Forward()
    @     0x7f975666500c  caffe::Solver::TestAll()
    @     0x7f9756600eae  caffe::Net::ForwardFromTo()
    @     0x7f975666536c  caffe::Solver::Step()
    @     0x7f9756600ff7  caffe::Net::Forward()
    @     0x7f9756666245  caffe::Solver::Solve()
    @     0x7f9756664672  caffe::Solver::Test()
    @     0x7f97565c3167  caffe::P2PSync::InternalThreadEntry()
    @     0x7f975666500c  caffe::Solver::TestAll()
F0627 15:13:49.795454 14309 gpu_memory.hpp:38] Failed to allocate 4153344 bytes on device 3. Total memory: 12799574016, Free: 3342336, dev_info[3]: total=12799574016 free=3342336F0627 15:13:49.822123 14306 gpu_memory.hpp:38] Failed to allocate 4153344 bytes on device 0. Total memory: 12794200064, Free: 3342336, dev_info[0]: total=12794200064 free=3342336
*** Check failure stack trace: ***
    @     0x7f97565ce3bb  caffe::InternalThread::entry()
    @     0x7f975666536c  caffe::Solver::Step()
    @     0x7f9755e23daa  (unknown)
    @     0x7f97565cf074  boost::detail::thread_data<>::run()
    @     0x7f9756666245  caffe::Solver::Solve()
    @     0x7f9755e23ce4  (unknown)
    @     0x7f97543eca4a  (unknown)
    @     0x7f97565c3167  caffe::P2PSync::InternalThreadEntry()
    @     0x7f9755e236e6  (unknown)
    @     0x7f97541cb184  start_thread
    @     0x7f9755e26687  (unknown)
    @     0x7f97546f4ffd  (unknown)
    @     0x7f97565ce3bb  caffe::InternalThread::entry()
    @     0x7f97565e0f60  caffe::GPUMemory::allocate<>()
    @              (nil)  (unknown)

**Comment by drnikolaev** [comment]
Hi @RSly thanks! Yeah, I found the issue - most probably you have different amount of available device memory because you have display connected to one of them. Is this the case? If so, fix is coming soon.

**Comment by RSly** [comment]
yes, 100-200Mb for display. why is that important on a 12Gb gpu? :)
I m curious, is it possible to not have the display connected to the gpu? 
if you have a link explaining how to, I appreciate it

**Comment by drnikolaev** [comment]
Cool, thank you. No need to change anything, fix is coming soon. The problem is not about size. it's about inequality.

**Comment by drnikolaev** [comment]
Hi @RSly please try v0.16.3
