### ISSUE TITLE
Don't see an improvement from using FP16 

### ISSUE THREAD

**Issue by benjaminklein** [NVIDIA/caffe#362]
Hello,

I'm using the extract_features tool for inference with a deploy.prototxt that has the following lines:
default_forward_type:  FLOAT16
default_forward_math:  FLOAT16

While I do see a reduction in GPU memory usage (comparing to when not using this), I don't see an improvement in throughput. Any idea why?

I'm using P100 with Resnet.

**Comment by gaqiness** [comment]
me too.
I test cifar10 in models/cifar10_nv/. add following lines:
default_forward_type:  FLOAT16
default_backward_type: FLOAT16
default_forward_math:  FLOAT
default_backward_math: FLOAT
to cifar10_nv_train_test.prototxt and train the cifar10 from scratch.
I'm using GTX1080 with caffe -test CMD to test the default dataset, but I don't see  a reduction in GPU memory usage,
and the caffe -time will not any reduction compare to bvlc caffe.

**Comment by drnikolaev** [comment]
@benjaminklein for ResNet both Forward and Backward passes should be set to 16 bit. Please try that.
@gaqiness 1080 is not designed to bring enough FP16 compute capacity, sorry.

**Comment by gaqiness** [comment]
I know 1080 is not designed to bring much improvement in fp16. But TX1 ？

**Comment by gaqiness** [comment]
Please give me more detail ……

**Comment by drnikolaev** [comment]
Hi @gaqiness I'm profiling TX1...

**Comment by drnikolaev** [comment]
#385
