### ISSUE TITLE
P40 slower than M40 with "train_adadelta_fp16.sh"

### ISSUE THREAD

**Issue by SantiGong** [NVIDIA/caffe#364]
Training with the script "train_adadelta_fp16.sh", M40 is 5 times faster than P40.
Verifying with "adagrad" and "adam"

OS: CentOS7.3
CUDA: cuda_8.0.44_linux.run or cuda_8.0.61_375.26_linux.run
HW config: Intel E5 2667v4*2, 256GB memory, M40*4 or P40*4

Attach the result.
M40:
`I0628 21:36:04.644706 175692 parallel.cpp:71] Root Solver performance on device 0: 8.086 * 128 = 1035 img/sec
I0628 21:36:04.644745 175692 parallel.cpp:76]      Solver performance on device 1: 8.086 * 128 = 1035 img/sec
I0628 21:36:04.644755 175692 parallel.cpp:76]      Solver performance on device 2: 8.086 * 128 = 1035 img/sec
I0628 21:36:04.644764 175692 parallel.cpp:76]      Solver performance on device 3: 8.086 * 128 = 1035 img/sec
I0628 21:36:04.644769 175692 parallel.cpp:79] Overall multi-GPU performance: 4139.94 img/sec
I0628 21:36:08.081059 175692 caffe.cpp:237] Optimization Done in 21m 19s`

P40 Result:
`I0703 13:47:20.501924  2865 parallel.cpp:71] Root Solver performance on device 0: 2.219 * 128 = 284.1 img/sec
I0703 13:47:20.501962  2865 parallel.cpp:76]      Solver performance on device 1: 2.219 * 128 = 284.1 img/sec
I0703 13:47:20.501969  2865 parallel.cpp:76]      Solver performance on device 2: 2.219 * 128 = 284.1 img/sec
I0703 13:47:20.501973  2865 parallel.cpp:76]      Solver performance on device 3: 2.219 * 128 = 284.1 img/sec
I0703 13:47:20.501977  2865 parallel.cpp:79] Overall multi-GPU performance: 1136.27 img/sec
I0703 13:47:24.659158  2865 caffe.cpp:237] Optimization Done in 1h 16m 5s`

**Comment by drnikolaev** [comment]
@SantiGong could you upload complete logs please?

**Comment by cliffwoolley** [comment]
Also, does this still reproduce with the latest cuBLAS patch 2 (8.0.61.2)
installed?

**Comment by SantiGong** [comment]
Folks,
Attach the log.
For the cuBLAS patch2, is it integrated in the CUDA 8.0.61 ?
Already verified with cuda 8.0.61, the behavior is same as the before.

[result_M40_adadelta_fp16_10000.txt](https://github.com/NVIDIA/caffe/files/1139336/result_M40_adadelta_fp16_10000.txt)
[result_P40_adadelta_fp16_10000.txt](https://github.com/NVIDIA/caffe/files/1139337/result_P40_adadelta_fp16_10000.txt)

**Comment by cliffwoolley** [comment]
> For the cuBLAS patch2, is it integrated in the CUDA 8.0.61 ?

No, it's separate.

Please see https://developer.nvidia.com/cuda-downloads .

**Comment by SantiGong** [comment]
Quick update, with cuBLAS patch2, the issue cannot be fixed.
Will update the detail result later on.
Sorry for the slow response due to my vocation.

**Comment by SantiGong** [comment]
The power consumption measured by nvidia-smi is not stable when running the benchmark on P40:

"_F_ri Jul 28 12:09:38 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.26                 Driver Version: 375.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P40           Off  | 0000:02:00.0     Off |                    0 |
| N/A   62C    P0    62W / 250W |   4189MiB / 22912MiB |     99%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P40           Off  | 0000:04:00.0     Off |                    0 |
| N/A   75C    P0    70W / 250W |   4171MiB / 22912MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P40           Off  | 0000:83:00.0     Off |                    0 |
| N/A   69C    P0    72W / 250W |   4383MiB / 22912MiB |     82%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P40           Off  | 0000:84:00.0     Off |                    0 |
| N/A   72C    P0    75W / 250W |   4171MiB / 22912MiB |     86%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      2840    C   ./build/tools/caffe                           4181MiB |
|    1      2840    C   ./build/tools/caffe                           4163MiB |
|    2      2840    C   ./build/tools/caffe                           4375MiB |
|    3      2840    C   ./build/tools/caffe                           4163MiB |
+-----------------------------------------------------------------------------+
Fri Jul 28 12:09:43 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.26                 Driver Version: 375.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P40           Off  | 0000:02:00.0     Off |                    0 |
| N/A   61C    P0    75W / 250W |   4189MiB / 22912MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P40           Off  | 0000:04:00.0     Off |                    0 |
| N/A   75C    P0    88W / 250W |   4171MiB / 22912MiB |     98%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P40           Off  | 0000:83:00.0     Off |                    0 |
| N/A   69C    P0    92W / 250W |   4383MiB / 22912MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P40           Off  | 0000:84:00.0     Off |                    0 |
| N/A   72C    P0    90W / 250W |   4171MiB / 22912MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      2840    C   ./build/tools/caffe                           4181MiB |
|    1      2840    C   ./build/tools/caffe                           4163MiB |
|    2      2840    C   ./build/tools/caffe                           4375MiB |
|    3      2840    C   ./build/tools/caffe                           4163MiB |
+-----------------------------------------------------------------------------+
Fri Jul 28 12:09:48 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.26                 Driver Version: 375.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P40           Off  | 0000:02:00.0     Off |                    0 |
| N/A   61C    P0   184W / 250W |   4189MiB / 22912MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P40           Off  | 0000:04:00.0     Off |                    0 |
| N/A   75C    P0   139W / 250W |   4171MiB / 22912MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P40           Off  | 0000:83:00.0     Off |                    0 |
| N/A   69C    P0   116W / 250W |   4383MiB / 22912MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P40           Off  | 0000:84:00.0     Off |                    0 |
| N/A   72C    P0   107W / 250W |   4171MiB / 22912MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      2840    C   ./build/tools/caffe                           4181MiB |
|    1      2840    C   ./build/tools/caffe                           4163MiB |
|    2      2840    C   ./build/tools/caffe                           4375MiB |
|    3      2840    C   ./build/tools/caffe                           4163MiB |
+-----------------------------------------------------------------------------+
Fri Jul 28 12:09:53 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.26                 Driver Version: 375.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P40           Off  | 0000:02:00.0     Off |                    0 |
| N/A   61C    P0    74W / 250W |   4189MiB / 22912MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P40           Off  | 0000:04:00.0     Off |                    0 |
| N/A   75C    P0    87W / 250W |   4171MiB / 22912MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P40           Off  | 0000:83:00.0     Off |                    0 |
| N/A   69C    P0    81W / 250W |   4383MiB / 22912MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P40           Off  | 0000:84:00.0     Off |                    0 |
| N/A   72C    P0    81W / 250W |   4171MiB / 22912MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      2840    C   ./build/tools/caffe                           4181MiB |
|    1      2840    C   ./build/tools/caffe                           4163MiB |
|    2      2840    C   ./build/tools/caffe                           4375MiB |
|    3      2840    C   ./build/tools/caffe                           4163MiB |
+-----------------------------------------------------------------------------+_"

Attach the detail log and power log.

[patch2_p40_power_consumption.txt](https://github.com/NVIDIA/caffe/files/1182309/patch2_p40_power_consumption.txt)
[patch2_m40_power_consumption.txt](https://github.com/NVIDIA/caffe/files/1182308/patch2_m40_power_consumption.txt)
[fp16_patched_m40.txt](https://github.com/NVIDIA/caffe/files/1182306/fp16_patched_m40.txt)
[fp16_patched_P40.txt](https://github.com/NVIDIA/caffe/files/1182307/fp16_patched_P40.txt)

**Comment by drnikolaev** [comment]
Hi @SantiGong could you try 0.16.3 please?

**Comment by SantiGong** [comment]
Tried 0.16.3, issue still exists.

**Comment by drnikolaev** [comment]
Hi @SantiGong thanks for confirming. I don't have the answer at this moment but I have a suggestion. Running pseudo fp16 on Maxwell GPUs doesn't make much sense at all. That fact that it runs faster than P40 means that there is a problem while running on P40. May I ask you to make pure fp32 run on M40 and pure fp16 run on P40? "Pure fp16" means the following:

Net:
```
default_forward_type: FLOAT16
default_backward_type: FLOAT16
default_forward_math: FLOAT16
default_backward_math: FLOAT16
global_grad_scale: 1000
```

Solver:
```
solver_data_type: FLOAT16
```
