### ISSUE TITLE
why does iteration time (seconds) depend on lr?

### ISSUE THREAD

**Issue by RSly** [NVIDIA/caffe#365]
Hi,

I have noticed that the wall clock time per iteration (in seconds) depends on the learning rate and loss weights.
I am not talking about the training time needed for getting minimum loss, I am concerned with the physical time that each iteration takes (regardless of the accuracy).

Is this a normal behavior or a bug? 
why is this happening?

**Comment by drnikolaev** [comment]
Could you try to set `engine: CAFFE` for convolution layers? Same observation?

**Comment by RSly** [comment]
hi @drnikolaev 

difficult to say regarding engine: CAFFE and timing dependency to lr, etc. (I need to do more tests)

on the other hand, using engine: CAFFE for all convs , I noticed that
1. engine: CAFFE uses ~ 35% less GPU ram compared to not using this flag, should this be the case?
(I thought cudnn convs are memory optimized?)
2. also the mini-hang problem still exists with CAFFE engine  (see https://github.com/NVIDIA/caffe/issues/349)

**Comment by drnikolaev** [comment]
hi @RSly  `engine: CAFFE` actually means "no cuDNN". It might require less memory, correct.
As of hangs - do you observe them with 0.16.3? If you do, may I have all the files and commands exactly as you run them? I'm still having hard time to reproduce this issue.

**Comment by RSly** [comment]
thanks @drnikolaev , I will try 16.03
now I am puzzled :)
=> so in my setup, if I get better wall clock speed per dataset with engine: CAFFE (or even using conv_algos_override: "1,1,1"), is there any good reason to switch to the cudnn seeker FINDEX?

**Comment by drnikolaev** [comment]
I doubt that it's going to happen, but please try.

**Comment by RSly** [comment]
slower training with group conv: https://github.com/NVIDIA/caffe/issues/386#issuecomment-323137069
