### ISSUE TITLE
cudnn algo selection on multiple gpus

### ISSUE THREAD

**Issue by RSly** [NVIDIA/caffe#369]
hi @drnikolaev,

I have a litte question: 
does the caffe 0.16 cudnn algorithm selection guarantees that, at the end, the same algorithms are selected  for all the GPUs?
in other words, can it happen that on gpu0, we run a set of algos such as 6 4 3 for convx, and on gpu1 it decides to run 1 1 3 for convx?

**Comment by drnikolaev** [comment]
hi @RSly 
There is no such guarantee.

**Comment by RSly** [comment]
In this case, I have a feeling that the difference of algo sets for each gpus can cause sync problems and extend the training time due to this.

could you please check, I think the current way can have negative side effects?

**Comment by drnikolaev** [comment]
We did test it. If we train on identical GPUs, we observe almost no difference. And we sync after each bucket and each iteration.
Insisting on the same algo set would make negative impact for those customers having different GPUs.

**Comment by RSly** [comment]
Thanks @drnikolaev , I completely agree with the 'different GPU' argument.

But, why on same GPUs the algo selection can vary? I mean, if for the same GPUs, on gpu0 we have selected the optimal set of algos, why would this set not be optimal on gpu1?

Also, do you think it makes sens to first check the GPUs and if the GPUs are the same, we set the same set of algos for all of them?

**Comment by drnikolaev** [comment]
Even in case of identical GPUs you might have different amount of memory available (for example, when one of GPUs have display connected). There are too many moving parts here. Besides that, there are things like CPU affinity...

**Comment by RSly** [comment]
Thanks @drnikolaev , If I run into a more concrete problem/crash, I will create a new issue.
