### ISSUE TITLE
Model of parallelism?

### ISSUE THREAD

**Issue by mrgloom** [NVIDIA/caffe#37]
What model of parallelism NVIDIA fork uses? Is there any documentation or paper about it? 
How much speed improvement we may to expect using "-gpus all" switch for 2 and 4 GPUs?

**Comment by lukeyeager** [comment]
We merged this pull request early - https://github.com/BVLC/caffe/pull/2114. BVLC made some modifications and merged this pull request instead - https://github.com/BVLC/caffe/pull/2903. There's a lot of info in both of those discussions which should answer your questions.

**Comment by mrgloom** [comment]
So I can use https://github.com/BVLC/caffe/tree/parallel branch also with "-gpus all" switch ?

**Comment by lukeyeager** [comment]
> So I can use https://github.com/BVLC/caffe/tree/parallel branch also with "-gpus all" switch ?

You don't need the `parallel` branch. https://github.com/BVLC/caffe/pull/2903 is merged into the `master` branch.
