### ISSUE TITLE
How to consider FP16 mode in inference ?

### ISSUE THREAD

**Issue by hit1001** [NVIDIA/caffe#370]
How exactly the flags are being set?
Earlier branch had an executable as caffe_fp16, would be better if moved like that.

Thanks.

**Comment by drnikolaev** [comment]
Hi @hit1001 please have a look to caffe.proto:
```
  // Type returned by Forward routines of a particular layer (aka 'Ftype')
  optional Type forward_type = 145 [default = FLOAT];
```
Also, check models shipped with NVCaffe - there are plenty of 16 bit ones out there.
