### ISSUE TITLE
cudnn_conv_layer.cpp internal compiler error

### ISSUE THREAD

**Issue by Agoniii** [NVIDIA/caffe#371]
NVCaffe: 0.16 
CUDA: 8.0.61
cuDNN: 6.0.21
GPU: P40

The error is below:
CXX src/caffe/layers/cudnn_conv_layer.cpp
src/caffe/layers/cudnn_conv_layer.cpp: In member function ‘size_t caffe::CuDNNConvolutionLayer<Ftype, Btype>::ComputeFindExWorkspaceSize()’:
src/caffe/layers/cudnn_conv_layer.cpp:213:7: internal compiler error: in var_defined_without_dynamic_init, at cp/decl2.c:2811
   if (was_reduced_) {
       ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
Preprocessed source stored into /tmp/ccyqaxmY.out file, please attach this to your bugreport.
make: *** [.build_release/src/caffe/layers/cudnn_conv_layer.o] Error 1

**Comment by Agoniii** [comment]
gcc version: 4.8.3
It seems a bug about gcc, perhaps I need higher gcc version?
Please help me, thanks.

**Comment by drnikolaev** [comment]
Yeah, makes sense to update your gcc. You may also try 0.16.3 release.

**Comment by Agoniii** [comment]
@drnikolaev  Sorry for Late reply, I compiled successfully when I updated my gcc to 4.8.5. Thanks very much.
