### ISSUE TITLE
Trying to convert layers developed using FP32 caffe so as to support FP16

### ISSUE THREAD

**Issue by shahromil16** [NVIDIA/caffe#372]
Hi,
There are custom layers created using FP32 caffe: 
[https://github.com/weiliu89/caffe/tree/ssd/include/caffe/layers](https://github.com/weiliu89/caffe/tree/ssd/include/caffe/layers)
[https://github.com/weiliu89/caffe/tree/ssd/include/caffe/util](https://github.com/weiliu89/caffe/tree/ssd/include/caffe/util)
example: normalize_layer.hpp, bbox_util.hpp

I am trying to use that in FP16 supporting caffe. I tried changing the layers datatypes but runs into errors. Even without changing the datatypes between Dtype and Ftype, I am getting errors saying:

> caffe::Blob may not have a template argument list

I am making the necessary datatype changes for the headers and the declarations. 
Looking forward to any help! Thank you!

**Comment by drnikolaev** [comment]
Hi @rams16592 please try 0.16.3

**Comment by shahromil16** [comment]
HI @drnikolaev , thank you for replying. Yes I have been trying 0.16.3 and facing the error in that.

**Comment by drnikolaev** [comment]
So, you code your own layers. You have to supply <Ftype, Btype> template everywhere then. F is forward, B is backward. Look how NVCaffe does that.
