### ISSUE TITLE
.caffemodel file backward compatibility with caffe/bvlc

### ISSUE THREAD

**Issue by beng0d** [NVIDIA/caffe#376]
Deployment of trained .caffemodels files is now more complex due to a breaking change introduced in caffe.proto and blob`T`::ToProto(). All blob data seems to be saved in raw_data field. Backward compatibility with bvlc/caffe is one way.

It would be nice to have a way to save blob`float` to data and blob`double` to double_data so that trained models can be deployed in other caffe platforms.

I use windows branch of bvlc/caffe in python to deploy models trained in DIGITS and get the following error parsing the caffe model.
 
F0725 13:41:21.618193 11784 blob.cpp:496] Check failed: count_ == proto.data_size() (3136 vs. 0)

**Comment by drnikolaev** [comment]
@beng0d In what direction do you want it to be compatible? Currently we support bvlc ---> NV only. We don't plan opposite way to be supported cause we need raw field for fp64/fp32/fp16 cross-compatibility.

**Comment by beng0d** [comment]
I was talking about exporting trained fp32 (or fp64) caffemodels from nvidia/caffe to be consumed by other forks of bvlc/caffe in the regular protobuf format. I understand the need for better support of alternate data types through raw_data. I am sure some export or conversion function would be welcomed for users who deploy trained models on other platforms. I personally was surprised when it stopped working after an update last week.

If, as you say, you don't plan to support it, I will write my own conversion function for fp32 models from the nvidia/caffe.proto definition.

**Comment by drnikolaev** [comment]
Got it. Yeah, seems like simple converter is the way to go.

**Comment by drozdvadym** [comment]
So, should we wait for official converter  NV -> bvlc (just for deploying)?
The main idea is next:  I'm using nvidia-caffe and DIGITS to train new models on my GPU-cluster, but deploy all models on a  simple device which doesn't have any GPU on it, so I prefer to use customized version of caffe which is based on bvlc. After last update I cant' do that.

**Comment by beng0d** [comment]
This should be better documented. It would be nice to have some converter part of the distribution and ideally available in DIGITS export functions for our non programmer users. 

I share my python script with no dependencies to nvidia caffe. I first compiled the nvidia caffe.proto to nvcaffe_pb2.py using cproto. 

```
import array
import proto.nvcaffe_pb2 as pb

def caffe_nv_to_bvlc( nvidia_model_file, bvlc_model_file ):
    
    param = pb.NetParameter()
    with open(nvidia_model_file, 'rb') as f:
        param.ParseFromString(f.read())
        
    for layer in param.layer:
        for blob in layer.blobs:
            if len(blob.raw_data) > 0 and blob.raw_data_type == pb.FLOAT:
                float_array = array.array( 'f' )
                float_array.frombytes( blob.raw_data )
                blob.data.extend( float_array )
                blob.raw_data = bytes()
                
            if len(blob.raw_data) > 0 and blob.raw_data_type == pb.DOUBLE:
                double_array = array.array( 'd' )
                double_array.frombytes( blob.raw_data )
                blob.double_data.extend( double_array )
                blob.raw_data = bytes()
                
            if len(blob.raw_diff) > 0 and blob.raw_diff_type == pb.FLOAT:
                float_array = array.array( 'f' )
                float_array.frombytes( blob.raw_diff )
                blob.diff.extend( float_array )
                blob.raw_diff = bytes()
                
            if len(blob.raw_diff) > 0 and blob.raw_diff_type == pb.DOUBLE:
                double_array = array.array( 'd' )
                double_array.frombytes( blob.raw_diff )
                blob.double_diff.extend( double_array )
                blob.raw_diff = bytes()
                
    
    with open(bvlc_model_file, 'wb') as f:
        f.write(param.SerializeToString())
```

**Comment by drnikolaev** [comment]
@beng0d @drozdvadym Let's make it on demand thing: in your solver.prototxt you would be able to switch back to bvlc format. Would it work?

**Comment by beng0d** [comment]
Good idea on your part. You would still have to access this new parameter in blob::ToProto or convert after the fact. 

There is still the problem of accessing those on DIGITS. (Issues [565](https://github.com/NVIDIA/DIGITS/issues/565) and [730](https://github.com/NVIDIA/DIGITS/issues/730)).

It would have to be a front end option in their solver parameters. If both changes are made, then we have a pretty good solution for users of all level.

**Comment by drnikolaev** [comment]
Done, please update to 0.16.3. Just do `store_blobs_in_old_format: true` when you train.

**Comment by drozdvadym** [comment]
Thanks!
