### ISSUE TITLE
I can't see much improment in jetson TX1

### ISSUE THREAD

**Issue by gaqiness** [NVIDIA/caffe#385]
I build nvcaffe 0.16 in jetson TX1(with **jetpack 3.1**, Host:ubuntu16.04), and follow this 
https://leotam.github.io/general/2016/05/05/EmbeddedVision.html
to test the alexnet.
By use CMD : caffe time --model=models/bvlc_alexnet/deploy.prototxt -gpu 0 -iterations 300
"deploy,prototxt " just edit and add:
default_forward_type:  FLOAT16
default_backward_type: FLOAT16
default_forward_math:  FLOAT16
default_backward_math: FLOAT16

But i just get follwing result ,and can't see much improment in TX1, why?
Any thing I miss?
My test result:
![capture](https://user-images.githubusercontent.com/22125450/28911569-834c6aa6-7863-11e7-801a-a8ed152904f1.JPG)
Leo K. Tam Blog's test result:
![jetsontx1fwd](https://user-images.githubusercontent.com/22125450/28911599-a023a720-7863-11e7-8b5f-dbd2510ecce1.png)

**Comment by drnikolaev** [comment]
Hi @gaqiness ,  I'd like to reproduce these timings. May I have complete log and all the steps taken to get it? Also, I'd suggest to train your model in FP16 to avoid 32->16 conversion.

**Comment by gaqiness** [comment]
thanks @drnikolaev, I train cifar10_fp16 in nvcaffe/models/cifar10_nv by GTX1080.

Then, I test that models in Jetson TX1.

All log and file is here
[log_and_file.zip](https://github.com/NVIDIA/caffe/files/1203665/log_and_file.zip)

**Comment by gaqiness** [comment]
Hi @drnikolaev , can you reproduce the issue?

**Comment by drnikolaev** [comment]
hi @gaqiness  , yes, thank you. NVML issue has been fixed, please pull the latest.

As of `caffe test` mode support on TX-1, it's fixed too. 
These are diffs I made before train in FP16: [train.diff.txt](https://github.com/NVIDIA/caffe/files/1216844/train.diff.txt)
These are test results: [test.log.txt](https://github.com/NVIDIA/caffe/files/1216848/test.log.txt)

As of `caffe time` speed you reported earlier, you run forward and backward 
but Leo runs forward only. Besides that, the branch he used is no longer there,
so I doubt that it's reproducible.

**Comment by gaqiness** [comment]
Thanks very much @drnikolaev , I will pull the latest and test again.

**Comment by shuyu0815** [comment]
Pull the latest means reboot the nvcaffe0.16 ?
Thanks !

**Comment by drnikolaev** [comment]
`git pull` to update the code
