### ISSUE TITLE
half_float/half.hpp

### ISSUE THREAD

**Issue by proCoderDude** [NVIDIA/caffe#389]
I compiled NVcaffe using CMakelist. make all and make runtest compiles. But when I try to build a separate app, it fails giving me this error:
 "~/NVcaffe/build/install/include/caffe/util/float16.hpp:13: error: half_float/half.hpp: No such file or directory"

half_float/half.hpp is include 3rdParty folder inside ~/NVcaffe/ but it seems like it was not installed in the install folder.

**Comment by drnikolaev** [comment]
Hi @proCoderDude , it's now fixed. Please clone the latest code and verify. Thanks for reporting.

**Comment by proCoderDude** [comment]
Thanks @drnikolaev, it did the trick. Can you also update the CMakelist.txt aswell.

Thank you.

**Comment by drnikolaev** [comment]
Fixed.
