### ISSUE TITLE
How to turn off the CUDNN in the nvidia-docker

### ISSUE THREAD

**Issue by MichaleWong** [NVIDIA/caffe#395]
I use the nvidia/caffe in my nvidia-docker, my video card cannot support cudnn (quadro 4000), the compute capability is 2.0.
So I want to use cuda and turn off the cudnn, how to do that using caffe commands, do I need to rebuild all my project?

**Comment by drnikolaev** [comment]
hi @MichaleWong , please set in your model
```
engine: CAFFE
```
for every layer having cuDNN implementation.

**Comment by MichaleWong** [comment]
@drnikolaev ，I got， I would try it，thank you very much
