### ISSUE TITLE
pre trained weights from nv-caffe 0.16?

### ISSUE THREAD

**Issue by RSly** [NVIDIA/caffe#398]
Hi,

I wonder if the pre-trained weights (eg. imagenet) from nv-caffe 0.16 implementations of models in
https://github.com/NVIDIA/caffe/tree/caffe-0.16/models
are available somewhere?

**I am especially intrested in inception v3 and resnet** 

thanks

**Comment by drnikolaev** [comment]
Hi @RSly , no plans to do this, sorry.

**Comment by RSly** [comment]
uh! we love caffe 0.16 and its models! :)
/cc @lukeyeager @gheinrich maybe these models are good candidates for the Model Store?

**Comment by drozdvadym** [comment]
at least main models

**Comment by drnikolaev** [comment]
@RSly @drozdvadym what would be the top 5 for you?

**Comment by RSly** [comment]
I vote for these :)
* Inception V4 and V3  
* ResNets (50 / 101 / 152)
* RCNN (best would be Mask rcnn)

**Comment by drozdvadym** [comment]
If we should choose from list https://github.com/NVIDIA/caffe/tree/caffe-0.16/models then:

* inception_v3
* resnet18
*  resnet50
* alexnet_bn
* bvlc_reference_rcnn_ilsvrc13

**Comment by drnikolaev** [comment]
@RSly @drozdvadym we got green light: https://github.com/NVIDIA/caffe/tree/models
Please give it a try
