### ISSUE TITLE
Batch normalization seems not work in "FLOAT16" mode

### ISSUE THREAD

**Issue by buptlion** [NVIDIA/caffe#401]
Hi, 
we are training "resnet-101" on dgx-1 with nvidia-dokcer image "nvcr.io/nvidia/caffe:17.07", it works well with net parameter:  
```
default_forward_type: FLOAT
default_backward_type: FLOAT 
default_forward_math: FLOAT 
default_backward_math: FLOAT
```
but get errors when its setting change to:
```
default_forward_type:  FLOAT16
default_backward_type: FLOAT16
default_forward_math:  FLOAT16
default_backward_math: FLOAT16
```
The errors are shown as following:
> caffe: /usr/include/boost/smart_ptr/shared_ptr.hpp:648: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = caffe::Blob; typename boost::detail::sp_member_access<T>::type = caffe::Blob*]: Assertion `px != 0' failed.
> *** Aborted at 1502681905 (unix time) try "date -d @1502681905" if you are using GNU date ***
> PC: @     0x7fb00bd13428 gsignal
> *** SIGABRT (@0x10f) received by PID 271 (TID 0x7fab27ffe700) from PID 271; stack trace: ***
>     @     0x7fb00bd134b0 (unknown)
>     @     0x7fb00bd13428 gsignal
>     @     0x7fb00bd1502a abort
>     @     0x7fb00bd0bbd7 (unknown)
>     @     0x7fb00bd0bc82 __assert_fail
>     @     0x7fb00e0ff7bf boost::shared_ptr<>::operator->()
>     @     0x7fb00e1dd8a1 caffe::CuDNNBatchNormLayer<>::Backward_gpu()
>     @     0x7fb00e0e0221 caffe::Net::BackwardFromToAu()
>     @     0x7fb00e0e0575 caffe::Net::Backward()
>     @     0x7fb00e0e0850 caffe::Net::ForwardBackward()
>     @     0x7fb00e0bcec9 caffe::Solver::Step()
>     @     0x7fb00e0be890 caffe::Solver::Solve()
>     @     0x7fb00e0c287c caffe::P2PSync::InternalThreadEntry()
>     @     0x7fb00e0219bb caffe::InternalThread::entry()
> caffe: /usr/include/boost/smart_ptr/shared_ptr.hpp:648: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = caffe::Blob; typename boost::detail::sp_member_access<T>::type = caffe::Blob*]: Assertion `px != 0' failed.
>     @     0x7fb00e023a3b boost::detail::thread_data<>::run()
>     @     0x7fb00bac95d5 (unknown)
>     @     0x7fb00b8a26ba start_thread
>     @     0x7fb00bde53dd clone
>     @                0x0 (unknown)
> 
thanks for checking this issue or pointing out our mistakes!

**Comment by buptlion** [comment]
the prototxt files and scripts we use are attached here: 
[res-101.zip](https://github.com/NVIDIA/caffe/files/1221255/res-101.zip)

**Comment by drnikolaev** [comment]
Hi @buptlion thank you for reporting this. We already discovered and fixed this issue:
https://github.com/NVIDIA/caffe/pull/383/commits/3d02ab91c72e8cd75fe59709d4535be6dfe5ce01#diff-355522b16af9f9d14aefc15460d452a3R156
Please update to 17.08 (coming soon) and verify.

**Comment by buptlion** [comment]
@drnikolaev thank you very much
