### ISSUE TITLE
cuda 9 compilation error

### ISSUE THREAD

**Issue by renganxu** [NVIDIA/caffe#408]
I am using CUDA 9, CUDNN 7 and NCCL 2.0.4 to compile the latest NV-Caffe (commit  5e106ce3062b65674ff4932f545a6a7f6cfffa93), but it has the following compilation error:

NVCC src/caffe/data_transformer.cu
In file included from /cm/shared/apps/cuda90/toolkit/9.0.103/include/common_functions.h:50:0,
                 from /cm/shared/apps/cuda90/toolkit/9.0.103/include/cuda_runtime.h:115,
                 from <command-line>:0:
/cm/shared/apps/cuda90/toolkit/9.0.103/include/crt/common_functions.h:64:24: error: token ""__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."" is not valid in preprocessor expressions
 #define __CUDACC_VER__ "__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."

Anyone has the same error and know how to fix it?

Regards,
Rengan

**Comment by cliffwoolley** [comment]
Hi Rengan,

Can you please tell us which host compiler you are using?  GCC?  ICC?
Something else?

Thanks,
Cliff

**Comment by cliffwoolley** [comment]
(Also which version of that host compiler.)

**Comment by renganxu** [comment]
Hi Cliff,

I compiled NV-Caffe on Centos 7.3 with GCC 4.8.5. 

An interesting finding is that after this issue, I also compiled the same NV-Caffe with CUDA 9, CUDNN 7, NCCL 2.0.4 and GCC 5.3.1 on Ubuntu 16.04 and it works.  So is it because of GCC version? I can try a higher version GCC later on Centos and see what will happen.

Regards,
Rengan

**Comment by cliffwoolley** [comment]
Thanks.  Can you provide the complete build logs in the passing and failing cases, please?

**Comment by renganxu** [comment]
Hi @cliffwoolley ,

I found that without CUDNN 7 and NCCL 2.0.4, RHEL/Centos 7.3 still has the same compiling error and Ubuntu 16.04 does not have that error.  I attached the failing case rhel7.3_compile.txt and the passing case ubuntu16.04_compile.txt.

[rhel7.3_compile.txt](https://github.com/NVIDIA/caffe/files/1255141/rhel7.3_compile.txt)
[ubuntu16.04_compile.txt](https://github.com/NVIDIA/caffe/files/1255142/ubuntu16.04_compile.txt)

Could you help check what's the possible reason for the failing case? Thanks.

Regards,
Rengan

**Comment by cliffwoolley** [comment]
We attempted to reproduce this on our end with a fresh CentOS 7.3
installation and everything checked out fine.

Is there any chance you have multiple CUDA installations on the CentOS
machine and might be picking up a mixture of different versions' headers?

What versions of Boost do you have on the two systems?

Thanks,
Cliff

**Comment by renganxu** [comment]
@cliffwoolley We indeed installed both cuda 8 and cuda 9 in our cluster, but we only used cuda 9 to compile NV-Caffe and the header was from cuda 9 based on the compilation log. 

The boost version is 1.61.0 in RHEL/Centos 7.3 and 1.58.0 in Ubuntu 16.04.

Since the RHEL was installed by Bright Computing in our cluster, I will try to install a bare-metal Centos 7.3 in a standalone server and let you know whether this error still happens.

Regards,
Rengan

**Comment by omaralvarez** [comment]
I am having this same issue on Ubuntu 17.04 (GCC 6.3.0, CUDA 9, CUDNN 7):

```
[  3%] Built target proto
[  3%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile_1.dir/util/cuda_compile_1_generated_math_functions2.cu.o
In file included from /usr/local/cuda-9.0/include/common_functions.h:50:0,
                 from /usr/local/cuda-9.0/include/cuda_runtime.h:115,
                 from <command-line>:0:
/usr/local/cuda-9.0/include/crt/common_functions.h:64:24: error: token ""__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."" is not valid in preprocessor expressions
 #define __CUDACC_VER__ "__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."
                        ^
CMake Error at cuda_compile_1_generated_math_functions2.cu.o.Release.cmake:218 (message):
  Error generating
  /home/caffe-0.16.3/build/src/caffe/CMakeFiles/cuda_compile_1.dir/util/./cuda_compile_1_generated_math_functions2.cu.o


src/caffe/CMakeFiles/caffe.dir/build.make:511: recipe for target 'src/caffe/CMakeFiles/cuda_compile_1.dir/util/cuda_compile_1_generated_math_functions2.cu.o' failed
make[2]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/util/cuda_compile_1_generated_math_functions2.cu.o] Error 1
CMakeFiles/Makefile2:272: recipe for target 'src/caffe/CMakeFiles/caffe.dir/all' failed
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

Config options:

```
-- General:
--   Version           :   0.16.3
--   Git               :   unknown
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -std=c++11 -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -DDEBUG -fPIC -Wall -std=c++11 -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   ON
--   USE_LEVELDB       :   ON
--   USE_LMDB          :   ON
--   ALLOW_LMDB_NOLOCK :   OFF
--   TEST_FP16         :   OFF
-- 
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.62)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 3.0.0)
--   lmdb              :   Yes (ver. 0.9.18)
--   LevelDB           :   Yes (ver. 1.18)
--   Snappy            :   Yes (ver. 1.1.4)
--   OpenCV            :   Yes (ver. 3.3.0)
--   CUDA              :   Yes (ver. 9.0)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_61
--   cuDNN             :   Yes (ver. 7.0)
--   NCCL              :   Not found
--   NVML              :   /usr/lib/x86_64-linux-gnu/libnvidia-ml.so
```

**Comment by renganxu** [comment]
Hi @cliffwoolley, thanks for your reminder about the boost version. Just let you know that the error disappeared when I used boost 1.58.0 (the same version as in Ubuntu) in bare metal RHEL/Centos 7.3. So it seems NV-Caffe has some restrictions on boost library version if CUDA 9 is used. 

@omaralvarez, you can also try a lower boost library version to see whether it works or not.

Regards,
Rengan

**Comment by omaralvarez** [comment]
Indeed, this is boost related:

https://svn.boost.org/trac10/ticket/13152#no2

But in the previous RC was working fine, a variable should not be removed, it should be first deprecated and then removed.

**Comment by drnikolaev** [comment]
@omaralvarez Similar issue in BOOST was fixed by adding
https://github.com/NVIDIA/caffe/blob/caffe-0.16/include/caffe/common.hpp#L10
Most probably, you need to do something like that.
