### ISSUE TITLE
Linux specific code in data_reader.cpp

### ISSUE THREAD

**Issue by agnat** [NVIDIA/caffe#414]
caca97af29750a8f8928beffa96028235933c0f9 introduces linux specific code unconditionally. In particular [`DataReader::DataCache::check_memory()`](https://github.com/NVIDIA/caffe/blob/cdb3d9a5d46774a3be3cc4c4ecc0bcd760901cc1/src/caffe/data_reader.cpp#L175-L226) in `data_reader.cpp` looks rather linux specific. 

On Mac OS I see the following issues:

1. Checking swap memory does not apply since swap is dynamically allocated.
1. There is no `sysinfo`
1. There is no `/proc`

Is this an accident or did you decide to drop builds on other platforms? Have you considered adding a naive yet generic implementation of `DataReader::DataCache`?

Thanks!

**Comment by drnikolaev** [comment]
Please check v0.16.5 and reopen the issue if the problem still exists.
