### ISSUE TITLE
The first GPU takes much more memory when dilated convolution is used

### ISSUE THREAD

**Issue by mathmanu** [NVIDIA/caffe#419]
When I use dilated convolution, the GPU 0 takes much more memory than the others. This limits my batch size and I am forced to use a lower batch size. I am using 3 GPUs. 

The run time is also higher. I believe dilated convolutions are not paralleled across multiple GPUs and is constrained to one GPU. 

The behavior is same when using CUDNN6 and CUDNN7. This is nv caffe version 0.16.4. 

Thanks.

**Comment by mathmanu** [comment]
Even if I set engine:CAFFE for these dilated convolution layers, the issue is still there. So looks like it is not specific to CUDNN.

**Comment by drnikolaev** [comment]
Hi @mathmanu thanks. Interesting. May I have your model attached here to reproduce it?

**Comment by mathmanu** [comment]
I use some custom layers, so it won't work for you as it is. Kindly give me some time to make a working example for you.

I thought CUDNN supports dilated convolution since version 6. But CUDNN convolution is used only if there is no dilation. Below snippet is taken from layer_factory.cpp

  if (engine == ConvolutionParameter_Engine_DEFAULT) {
    engine = ConvolutionParameter_Engine_CAFFE;
#ifdef USE_CUDNN
    if (**!use_dilation** && Caffe::mode() == Caffe::GPU) {
      engine = ConvolutionParameter_Engine_CUDNN;
    }
#endif
  }

**Comment by mathmanu** [comment]
My model won't work in NVIDIA/caffe as it uses several custom layers. Also this issue is not seen in a classification scenario which doesn't use those custom layers. Closing this for now as I am not able to give a simple test case to debug this scenario. Shall reopen this if I come across this issue in a scenario that doesn't use those custom layers. Thanks.
