### ISSUE TITLE
How to use V100 Tensor cores?

### ISSUE THREAD

**Issue by renganxu** [NVIDIA/caffe#420]
The NV-Caffe resnet50 model directory has the solver file for FP16. Now I want to know when running FP16 on V100, does it automatically use Tensor cores? Because P100 can also run FP16 solver but uses CUDA cores. So when V100 runs FP16 solver, does it use CUDA cores or Tensor cores? If it does not use Tensor cores by default, how to enable it?

Thanks,
Rengan

**Comment by drnikolaev** [comment]
Hi @hfutxrg 
Yes, it does. However, to get the top speed please use this parameter in your solver:
```
solver_data_type: FLOAT16
```
and these ones in your net:
```
default_forward_type:  FLOAT16
default_backward_type: FLOAT16
default_forward_math:  FLOAT16
default_backward_math: FLOAT16
global_grad_scale: 100
```

**Comment by renganxu** [comment]
Hi @drnikolaev,

Thanks for your reply. I have some other questions:
1. The original solver did not have "solver_data_type: FLOAT16", and the net file was using:
``default_forward_type:  FLOAT16``
``default_backward_type: FLOAT16``
``default_forward_math:  FLOAT``
``default_backward_math: FLOAT``

Does this mean it is using mixed precision training?

2. Generally how to use Tensor cores? Is it handled by CUDA compiler automatically or the user needs to write the GPU computation kernels with some special APIs? If using API, what are those APIs? Is there any example code shown how to use tensor cores?

3. Does the nvidia profiler like nvprof and nvvp can detect whether tensor cores are used?

4. What papers do you developers refer to when implementing these FP16 operations? Can you point out those papers to us? I want to know all underlying details. 

Thanks.
Rengan

**Comment by borisgin** [comment]
For GV-100  to use TensorOps set following setting:
     default_forward_type:   FLOAT16
     default_backward_type: FLOAT16
     global_grad_scale: 1000.   # this is needed for good accuracy

Caffe chooses the fastest cudnn implementation and prints which algorithm is choosen in the log. If a;gorithm use TensorOp it will be marked as T ( e.g. 1T)  

There is a detailed tutorial on mixed precision training here: http://on-demand.gputechconf.com/gtc/2017/presentation/s7218-training-with-mixed-precision-boris-ginsburg.pdf

**Comment by renganxu** [comment]
Hi @borisgin , I have read through your presentation slides. Your setting is for mixed training with FP32 master weight while @drnikolaev 's setting is for FP16 training with FP16 master weight, right?  Can you verify that I understand the following parameters correctly:
"default_forward_type" and "default_backward_type" are used for "training values storage"
"default_forward_math" and "default_backward_math" are used for "matrix-mul accumulator"
"solver_data_type" is used for master weight storage?

Other questions:
1. What is "master weight"? Do you mean different workers have their own weights, and then they are synchronized/reduced to the master weight?
2. P100 can also run the mixed training. I know P100 does not support tensor ops, but do you think does it make sense to compare the mixed training speed of V100 to that of P100?

**Comment by borisgin** [comment]
"default_forward_type" and "default_backward_type" are used for "training values storage"
"default_forward_math" and "default_backward_math" are used for "matrix-mul accumulator"
"solver_data_type" is used for master weight storage?
RIGHT,

Master weights:  weights used for update. In caffe each GPU does Forward-Backward iteration with the same weights (except BN global mean and variance).  After Backward is done, weights grads are avearged between GPUs, and then each GPU does update with this syncghronized gradient. The update can be done or in float or in float16 ( controled by  solver_data_type").

 you can  do float16 training with GP100:( don't forget to use 
    global_grad_scale: 1000
).
GV100 mixed precision training is significantly faster than GP100 float16.

**Comment by sergey-serebryakov** [comment]
@drnikolaev, @borisgin 
I was going through the source code of NVIDIA Caffe and could not find any function calls that enable tensor core operations. As I understand, due to slightly different numerical results, tensor ops are not used by default in cuBLAS and cuDNN. Specifically, I was looking for something like  `cudnnSetConvolutionMathType`, `cublasSetMathMode` and `CUBLAS_TENSOR_OP_MATH `.  Could you please confirm NVIDIA Caffe can take advantage of Volta's tensor operations.
Thanks.

**Comment by gcp** [comment]
Those are used, see for example: https://github.com/NVIDIA/caffe/blob/caffe-0.16/src/caffe/layers/cudnn_conv_layer.cpp#L556
