### ISSUE TITLE
Repeatedly calling Solver::Step(1) leads to a memory leak

### ISSUE THREAD

**Issue by seanbell** [NVIDIA/caffe#426]
If learning step-by-step, calling `solver.step(1)` (from Python) each iteration, there is a GPU memory leak.

I think this is the thread that gets created:
https://github.com/NVIDIA/caffe/blob/caffe-0.16/src/caffe/solver.cpp#L237
and then `Solver::Reduce` calls `Caffe::set_mode` here:
https://github.com/NVIDIA/caffe/blob/caffe-0.16/src/caffe/solver.cpp#L370
which then allocates new memory and new streams for that thread.

Every iteration, the `thread_count_` increases:
https://github.com/NVIDIA/caffe/blob/caffe-0.16/src/caffe/common.cpp#L42

Note: I get a memory leak (gradual increase in GPU usage) whether or not NVML is disabled.

**Comment by seanbell** [comment]
Log output (printing `Caffe::thread_count_` each iteration):

```
...
I1010 00:04:09.741087  1838 solver.cpp:316] Iteration 2 (8.43344 s), loss = 3.21386
(omitted)
I1010 00:04:09.741221  1838 sgd_solver.cpp:136] Iteration 2, lr = 9.99995e-06, m = 0.9
I1010 00:04:09.743270  1853 common.cpp:43] Caffe thread_count_: 5
I1010 00:04:09.743798  1853 device_alternate.hpp:116] NVML initialized on thread 140695270381312
I1010 00:04:11.329491  1838 solver.cpp:311] Iteration 3 (0.629557 iter/s, 1.58842s/1 iter), loss = 4.05294
(omitted)
I1010 00:04:11.359246  1854 common.cpp:43] Caffe thread_count_: 6
I1010 00:04:11.360765  1854 device_alternate.hpp:116] NVML initialized on thread 140695270381312
I1010 00:04:12.961051  1838 solver.cpp:311] Iteration 4 (0.612916 iter/s, 1.63155s/1 iter), loss = 3.39824
(omitted)
I1010 00:04:12.961194  1838 sgd_solver.cpp:136] Iteration 4, lr = 9.99991e-06, m = 0.9
I1010 00:04:12.963176  1855 common.cpp:43] Caffe thread_count_: 7
I1010 00:04:12.963752  1855 device_alternate.hpp:116] NVML initialized on thread 140695270381312
I1010 00:04:14.592965  1838 solver.cpp:311] Iteration 5 (0.612772 iter/s, 1.63193s/1 iter), loss = 5.92507
(omitted)
I1010 00:04:14.624382  1856 common.cpp:43] Caffe thread_count_: 8
I1010 00:04:14.625530  1856 device_alternate.hpp:116] NVML initialized on thread 140695270381312
I1010 00:04:16.220396  1838 solver.cpp:311] Iteration 6 (0.614475 iter/s, 1.6274s/1 iter), loss = 2.52571
(omitted)
I1010 00:04:16.220546  1838 sgd_solver.cpp:136] Iteration 6, lr = 9.99986e-06, m = 0.9
I1010 00:04:16.223847  1857 common.cpp:43] Caffe thread_count_: 9
I1010 00:04:16.224313  1857 device_alternate.hpp:116] NVML initialized on thread 140695270381312
I1010 00:04:17.827453  1838 solver.cpp:311] Iteration 7 (0.622256 iter/s, 1.60706s/1 iter), loss = 2.27418
(omitted)
...
```

Every iteration, the NVML struct gets initialized
(https://github.com/NVIDIA/caffe/blob/caffe-0.16/src/caffe/common.cpp#L576) and this is printed:
```
I1010 00:04:17.863839  1858 device_alternate.hpp:116] NVML initialized on thread 140695270381312
```
The thread ID is the same every iteration, as you can see above.

**Comment by seanbell** [comment]
Update: I also get a memory leak (gradual increase in GPU usage) with NVML disabled.

**Comment by seanbell** [comment]
It looks like streams are not cleaned up in `Caffe::~Caffe`?
https://github.com/NVIDIA/caffe/blob/caffe-0.16/src/caffe/common.cpp#L184-L197

**Comment by seanbell** [comment]
It seems like the leak is inside `all_streams_`.

This is the output when I print the size of `all_streams_` each iteration (calling `step(1)`):
```
...
I1010 02:58:06.370962 10635 solver.cpp:311] Iteration 3 (0.495392 iter/s, 2.0186s/1 iter), loss = 4.05293
(omitted)
I1010 02:58:06.390954 10651 common.cpp:250] Stream count: 6
I1010 02:58:08.394721 10635 solver.cpp:311] Iteration 4 (0.49413 iter/s, 2.02376s/1 iter), loss = 3.39824
(omitted)
I1010 02:58:08.394927 10635 sgd_solver.cpp:136] Iteration 4, lr = 9.99991e-06, m = 0.9
I1010 02:58:08.399171 10652 common.cpp:250] Stream count: 7
I1010 02:58:10.343838 10635 solver.cpp:311] Iteration 5 (0.513052 iter/s, 1.94912s/1 iter), loss = 5.92509
(omitted)
I1010 02:58:10.377709 10653 common.cpp:250] Stream count: 8
I1010 02:58:12.348834 10635 solver.cpp:311] Iteration 6 (0.498755 iter/s, 2.00499s/1 iter), loss = 2.52571
(omitted)
I1010 02:58:12.349781 10635 sgd_solver.cpp:136] Iteration 6, lr = 9.99986e-06, m = 0.9
I1010 02:58:12.355520 10654 common.cpp:250] Stream count: 9
I1010 02:58:14.261018 10635 solver.cpp:311] Iteration 7 (0.522962 iter/s, 1.91219s/1 iter), loss = 2.27417
(omitted)
I1010 02:58:14.288379 10655 common.cpp:250] Stream count: 10
(omitted)
I1010 02:58:16.267019 10635 sgd_solver.cpp:136] Iteration 8, lr = 9.99981e-06, m = 0.9
I1010 02:58:16.272689 10656 common.cpp:250] Stream count: 11
I1010 02:58:18.237684 10635 solver.cpp:311] Iteration 9 (0.5074 iter/s, 1.97083s/1 iter), loss = 4.40386
(omitted)
I1010 02:58:18.462218 10657 common.cpp:250] Stream count: 12
...
```

(NVML is disabled here)

**Comment by seanbell** [comment]
Simply removing `all_streams_` seems to fix the memory leak, but leads to a different error when deleting the `caffe.Solver` Python instance.  A more nuanced solution is required.

**Comment by seanbell** [comment]
@drnikolaev, what is the purpose of `all_streams_`?  Right now it seems to just accumulate more and more streams until GPU memory runs out.  Every `step(1)` creates a new thread which allocates new streams (which are never deallocated because of `all_streams_`).

(Sorry for all the comments -- I'm trying to help debug this issue with you)

**Comment by seanbell** [comment]
I believe I fixed the memory leak -- see https://github.com/NVIDIA/caffe/pull/427

For NVML, I've just disabled it for now with `NO_NVML`.

**Comment by drnikolaev** [comment]
Hi @seanbell thank you. I did it too :) https://github.com/drnikolaev/caffe/tree/caffe-0.16
Could you do me a favor and check that branch?

**Comment by seanbell** [comment]
Hi @drnikolaev, I haven't directly tested your branch, but visually inspecting it, it looks like your solution should also work.  When do you think it will be merged into `NVIDIA/caffe`?

**Comment by drnikolaev** [comment]
Please check v0.16.5 and reopen the issue if the problem still exists.

**Comment by seanbell** [comment]
Thanks!  Unfortunately I still get a leak with the new version (though it seems to be different?).  I filed a new issue #459.
