### ISSUE TITLE
Can you run detections in multi-gpu mode?

### ISSUE THREAD

**Issue by alfredox10** [NVIDIA/caffe#43]
I have a trained caffemodel file and using it to detect an object in an image. I've been running it in single GPU mode for months without problems, but I recently installed a new GPU and set it up with SLI. I am wondering how to set detection to multi-GPU in python?

I have seen these functions while searching for a solution, but I have seen nothing that states how to use caffe.set_device() to set multiple GPUs. Is there a way to do that?
caffe.set_device(0)
caffe.set_mode_gpu()

**Comment by lukeyeager** [comment]
> I have only found documentation on how to enable multi-GPU training, what about multi-GPU detection with the caffemodel file? For the python interface there is this command:
caffe.set_device(gpuid) 
however it only takes one id at a time, how can we set it for multiple GPUs?
https://github.com/NVIDIA/caffe/issues/47#issuecomment-150701505

/cc @drnikolaev

**Comment by lukeyeager** [comment]
See https://github.com/BVLC/caffe/issues/3648.

Pycaffe does not support multi-GPU yet.
