### ISSUE TITLE
Caffe compiled with GPU support does not run on host without drivers

### ISSUE THREAD

**Issue by vdel** [NVIDIA/caffe#430]
When compiling Caffe with GPU support, it cannot be run on a host without drivers.

For example, running the latest nvidia/caffe docker image with docker (i.e. **without** accessible drivers) and running a `caffe time ...` command leads to:

```bash
F1011 21:59:30.374527    31 gpu_memory.hpp:185] Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version
*** Check failure stack trace: ***
    @     0x7fd2680a6daa  (unknown)
    @     0x7fd2680a6ce4  (unknown)
    @     0x7fd2680a66e6  (unknown)
    @     0x7fd2680a9687  (unknown)
    @     0x7fd2686ce108  (unknown)
    @     0x7fd2686d2f88  (unknown)
    @     0x7fd268745f75  (unknown)
    @     0x7fd26874757d  (unknown)
    @           0x40b40e  (unknown)
    @           0x40867c  (unknown)
    @     0x7fd266b9df45  (unknown)
    @           0x408e4d  (unknown)
    @              (nil)  (unknown)
```

Typically packaging an application that uses caffe in a Docker image is not straightforward. It involves distributing a CPU-only docker image or a GPU docker image according to the target configuration and setting up a proper build system with multiple environments.

**Comment by drnikolaev** [comment]
Please check v0.16.5 and reopen the issue if the problem still exists.
