### ISSUE TITLE
docker clone from BVLC. is it correct?

### ISSUE THREAD

**Issue by xuzhuoran0106** [NVIDIA/caffe#434]
in https://github.com/NVIDIA/caffe/blob/caffe-0.16/docker/standalone/gpu/Dockerfile#L32
The code clone from BVLC/caffe.git, is it correct?
I think it should clone from NVIDIA/caffe.git.

**Comment by cliffwoolley** [comment]
Good point, though a better solution is to simply `COPY . .` in from the
docker context -- getting rid of the `git  clone` completely -- since
someone presumably already has cloned the version they want before they do
`docker build`.
