### ISSUE TITLE
Compatibility with caffe

### ISSUE THREAD

**Issue by Wronskia** [NVIDIA/caffe#439]
Hello,

After retraining a BVLC/caffe model (googlenet BVLC) with NVcaffe I noticed that the size of the retrained caffemodel was half the size of the original caffe and when trying inference of the finetuned caffemodel from NVcaffe in caffe I get that : Check failed: count_ == proto.data_size() (9408 vs 0)
Is it possible to use an NVcaffe model in BVLC/caffe ??
Thanks,
Best

**Comment by drnikolaev** [comment]
When you train in NVCaffe please use:
```
store_blobs_in_old_format: true
```
More details:
```
  // If true:
  // * Stores blobs in old (less efficient) BVLC-compatible format.
  // * FP16 blobs are converted to FP32 and stored in 'data' container.
  // * FP32 blobs are stored in 'data' container.
  // * FP64 blobs are stored in 'double_data' container.
  optional bool store_blobs_in_old_format = 45 [default = false];
```

**Comment by Wronskia** [comment]
Thank you @drnikolaev

**Comment by settle** [comment]
Is there a way to modify an already trained caffemodel from NVIDIA/caffe so it can be used in BVLC/caffe, that is without retraining?

**Comment by drnikolaev** [comment]
Unfortunately, no. You can write simple converter though...

**Comment by hlnull** [comment]
@drnikolaev 
Is this converter implemented yet? If not, maybe I can write one.
