### ISSUE TITLE
Python function net.clear_param_diffs() from Net is missing

### ISSUE THREAD

**Issue by seanbell** [NVIDIA/caffe#440]
Can this line be added to `_caffe.cpp` for the Python `Net`, to expose the `clear_param_diffs` method?
```
.def("clear_param_diffs", &Net<Dtype>::ClearParamDiffs)
```

See corresponding line in BVLC/caffe: https://github.com/BVLC/caffe/blob/effcdb0b62410b2a6a54f18f23cf90733a115673/python/caffe/_caffe.cpp#L417

**Comment by drnikolaev** [comment]
Please check v0.16.5 and reopen the issue if the problem still exists.
