### ISSUE TITLE
nvcaffe speed issue

### ISSUE THREAD

**Issue by abrams90** [NVIDIA/caffe#443]
I am trying to make nvcaffe support ssd.when testing the modified ssd-nvcaffe,I found the speed was even slower than caffe master branch when dealing with detection task.But in classificaftion ,the speed is really faster.Does anyone have the same problem?

**Comment by blueardour** [comment]
@abrams90 
Is there any estimation or practical data about how slower of the nvcaffe versus the caffe master one for ssd network and classification network.

For example, it cost xx times time compared with the origin caffe master branch for ssd/resenet?

**Comment by mathmanu** [comment]
SSD uses a lot of data augmentations and these are in CPU. Writing equivalent GPU layer/code for these should make it faster.

I hope you have seen the SSD pull request that I have submitted: https://github.com/NVIDIA/caffe/pull/446
Are you interested in improving it so that it can be integrated into NVCaffe?

**Comment by abrams90** [comment]
I think maybe the speed is relative to the caculate capbility of fp16 in GPU,In 1080ti the fp16 ability is about 1/64  of fp32.

**Comment by mathmanu** [comment]
@abrams90 
Are you implying that you have SSD ported to nvcaffe with fp16 support? Would you be interested in publishing your fork or submitting a pull request for it to help the community?

**Comment by drnikolaev** [comment]
@abrams90 @mathmanu new release is coming soon - cpu-based augmentation is a little bit faster out there

**Comment by drnikolaev** [comment]
Please check v0.16.5 and reopen the issue if the problem still exists.
