### ISSUE TITLE
CUDA is not detected by cmake. Building without it.

### ISSUE THREAD

**Issue by AdamKisgergely** [NVIDIA/caffe#448]
Hi
I am trying to build caffe version 0.15 with CUDA v9.0 and cudnn v7.0.4. 
I have set the path to cuda with the following way: 
export PATH=/usr/local/cuda-9.0/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
export CUDA_HOME=/usr/local/cuda-9.0
And nvcc --version list it the right way: 
Cuda compilation tools, release 9.0, V9.0.176
cmake always show this:
CMake Warning at cmake/Dependencies.cmake:63 (message):
  -- CUDA is not detected by cmake.  Building without it...

I have already installed successfully these versions on an other pc with digits 6 by a "self made" guide by several other how to install, but i didn't face with this problem then.

Using Ubuntu 16.04, GPU Nvidia GTX 1060 with 384.90 driver version 

How could I make caffe recognize cuda?

**Comment by drnikolaev** [comment]
Hi @AdamKisgergely have you tried 0.16?

**Comment by AdamKisgergely** [comment]
Hi @drnikolaev I haven't, i would like to use the same setup on bouth pc.

**Comment by AdamKisgergely** [comment]
I have mannaged to find by installing the cuda tool kit with 
sudo apt install nvidia-cuda-toolkit
It installed the 7.5 version, but somehow the caffe with it found the 9.0.
