### ISSUE TITLE
Documentation 16.4

### ISSUE THREAD

**Issue by RSly** [NVIDIA/caffe#449]
Hi @drnikolaev 
I see in the release note it says for 16.4, new augmentations:
https://github.com/NVIDIA/caffe/releases/tag/v0.16.4

Could you please direct me to the documentation for those new functions?
thanks!

**Comment by RSly** [comment]
Hi any news on this? 
tnx

**Comment by drnikolaev** [comment]
Hi @RSly it's coming soon here: http://docs.nvidia.com/deeplearning/dgx/caffe-user-guide/index.html
Please stay tuned.
