### ISSUE TITLE
set_mode(Caffe::GPU) failed in  version 0.16

### ISSUE THREAD

**Issue by jellyDL** [NVIDIA/caffe#451]
complie caffe as dynamic lib(-lcaffe）, using set_mode(Caffe::GPU) before calling the dynamic lib， found the mode_(GPU/CPU)  can not be set in the dynamic library。 I guess it caused by "static thread_local unique_ptr<Caffe> thread_instance_" , Is there a good solution?

cudnn:6021
cuda 8000
cuda driver 9000

**Comment by drnikolaev** [comment]
Hi @xiaoxiongguilai 
Do you link using `ldd` or load so dynamically?
In upcoming release please do this in your main()
```
  vector<int> gpus;
  get_gpus(&gpus);  // fill it with ids like 0,1,2,3
  caffe::GPUMemory::Scope gpu_memory_scope(gpus);
  Caffe::set_mode(Caffe::GPU);
```
