### ISSUE TITLE
Error during make

### ISSUE THREAD

**Issue by BalintMagyar4** [NVIDIA/caffe#452]
I get the following errors if I try to make Caffe by `make -j"$(nproc)"`
...
[100%] Linking CXX executable caffe
CMakeFiles/caffe.bin.dir/caffe.cpp.o: In function `_GLOBAL__sub_I_caffe.cpp':
caffe.cpp:(.text.startup+0x4ce): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
caffe.cpp:(.text.startup+0x593): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
caffe.cpp:(.text.startup+0x651): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
caffe.cpp:(.text.startup+0x70f): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
caffe.cpp:(.text.startup+0x7cd): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
caffe.cpp:(.text.startup+0x83f): undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
caffe.cpp:(.text.startup+0x8ba): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
caffe.cpp:(.text.startup+0x978): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
collect2: error: ld returned 1 exit status
tools/CMakeFiles/caffe.bin.dir/build.make:137: recipe for target 'tools/caffe' failed
make[2]: *** [tools/caffe] Error 1
CMakeFiles/Makefile2:815: recipe for target 'tools/CMakeFiles/caffe.bin.dir/all' failed
make[1]: *** [tools/CMakeFiles/caffe.bin.dir/all] Error 2
[100%] Linking CXX shared library ../lib/_caffe.so
Creating symlink /home/bmagyar/caffe/python/caffe/_caffe.so -> /home/bmagyar/caffe/build/lib/_caffe.so
[100%] Built target pycaffe
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

I attached the whole make output, and the build parameters:
[buildParameters.txt](https://github.com/NVIDIA/caffe/files/1579952/buildParameters.txt)
[make_output.txt](https://github.com/NVIDIA/caffe/files/1579906/make_output.txt)

I use Ubuntu 16.04, gcc version 5.4.1 and I try to install NVIDIA Caffe 1.5.

**Comment by drnikolaev** [comment]
Please try
```
sudo apt-get install libgoogle-glog-dev
```
