### ISSUE TITLE
multi GPU performance decade.

### ISSUE THREAD

**Issue by aazz44ss** [NVIDIA/caffe#454]
When I use 1,2,4,8 GPU in nvcaffe 0.15, it's about 1.7X performance scaling when I double my GPU.
However when I use nvCaffe 0.16, when in 1,2,4 GPU, it have really good performance scaling about 1.95X when doubling GPU.
But when GPU number increase from 4 to 8, the performance become only half of 4 GPU. and even lower than 8 GPU with caffe 0.15.
a lot of time was waste on solver::step::iteration_wait();
Did this function wait for every GPU get an updated parameter with nccl allreduce?

BTW when using 8 GPU, I get a lot of waiting for datum message, I increase prefetch or paeser_threads and threads didnt help.
My CPU have 64 core.

**Comment by drnikolaev** [comment]
Please check v0.16.5 and reopen the issue if the problem still exists.

**Comment by aazz44ss** [comment]
problem still exists.


batch:32 | total(sec) | forward | backward | iteration_wait
1GPU  | 763   | 248 | 514 | 1
2GPU  | 774   | 247 | 499 | 28
4GPU  | 817   | 262 | 516 | 39
8GPU  | 1533 | 448 | 517 | 568
