### ISSUE TITLE
data_reader.cpp is new to BLVC/caffe and caused build failed in MacOS

### ISSUE THREAD

**Issue by winnerineast** [NVIDIA/caffe#455]
As titled. I'm not sure if it is conscious to focus caffe in linux or not. If so, I could close the issue directly. Otherwise, this file indeed caused the problem to build caffe in macos due to sys/sysinfo.h.

**Comment by drnikolaev** [comment]
Hi @winnerineast this is not BVLC Caffe and you are right, we currently focus on Linux.
