### ISSUE TITLE
multi GPU performance decade

### ISSUE THREAD

**Issue by aazz44ss** [NVIDIA/caffe#457]
When I use 1,2,4,8 GPU in nvcaffe 0.15, it's about 1.7X performance scaling when I double my GPU.
However when I use nvCaffe 0.16, when in 1,2,4 GPU, it have really good performance scaling about 1.95X when doubling GPU.
But when GPU number increase from 4 to 8, the performance become only half of 4 GPU. and even lower than 8 GPU with caffe 0.15.
a lot of time was waste on solver::step::iteration_wait();
Did this function wait for every GPU get an updated parameter with nccl allreduce?

I am using 64 core CPU on 8 GPU, I get a lot of waiting for datum message, I increase prefetch or paeser_threads or threads didn't help.

NVcaffe 0.16.4, 0.16.5
NCCL 1.3
Cudnn 6
cuda 8

Here is my test
batch:32 | total(sec) | forward | backward | iteration_wait
1GPU      | 763   | 248 | 514 | 1
2GPU      | 774   | 247 | 499 | 28
4GPU      | 817   | 262 | 516 | 39
8GPU      | 1533 | 448 | 517 | 568

forward and iteration_wait increased a lot.

**Comment by drnikolaev** [comment]
Hi @aazz44ss 
we'd strongly suggest to step up to NCCL 2.1, CuDNN 7 and CUDA 9.
Also, please compare two runs: `--gpu 0,1,2,3` and `--gpu 4,5,6,7`. Are they identical?
One more question: do you use NVLink?

**Comment by aazz44ss** [comment]
--gpu 4,5,6,7 is the same as --gpu 0,1,2,3 very good performance.
Yes, I have use NVLink. my test sample is bvlc_googlenet. I will try NCCL2.1, CuDNN 7 and Cuda 9

1. iteration_wait have increase a lot of time cost when using 8 GPU, may owing to NCCL reduce function?
2. and forward also increase a lot of time, may owing to LOG message "waiting for datum" ?
how to solve waiting for datum? I try to increase parser_thread, threads or prefetch, but not help.

**Comment by nViso** [comment]
Maybe it would be good to update the README.md that suggests NCCL 1.34 and CuDNN 6 are the recommended configuration. BTW are the optimized FP16 instructions in CuDNN 7 being leveraged?

**Comment by aazz44ss** [comment]
I haven't change any setting, so I am not sure optimized FP16 instructions in CuDNN 7 being leveraged.

**Comment by drnikolaev** [comment]
@aazz44ss could you upload log files for 4 and 8 GPUs please?
"Waiting for datum" means that your disk reads data slower than Caffe computes. 
If your system is capable to store your data set as a whole in RAM, you may do so. Just add
```
data_param {
    cache: true
    shuffle: true
...
```
in DataLayer. After reading whole dataset Caffe will use RAM. Shuffle is optional but it helps to improve accuracy.

**Comment by drnikolaev** [comment]
@nViso yes, CuDNN 7 does use FP16 and runs fast on Volta boards

**Comment by nViso** [comment]
@drnikolaev Great we will try it out. It might be worth updating the README.md for the latest CuDNN version supported and NCCL version as currently it mentioned CuDNN v6 and NCCL v1.3.4.

Having NVIDIA Caffe support FP16, multi-GPU and the new Volta boards is definitely a big plus to accelerate and improve training.

**Comment by aazz44ss** [comment]
When I try to use NCCL2,
I0103 16:20:48.981690  6024 net.cpp:1492] [4] Reserving 53516544 bytes of shared learnable space for type FLOAT
I0103 16:20:48.981690  6021 net.cpp:1492] [1] Reserving 53516544 bytes of shared learnable space for type FLOAT
I0103 16:20:48.981789  6026 net.cpp:1492] [6] Reserving 53516544 bytes of shared learnable space for type FLOAT
I0103 16:20:48.981765  6025 net.cpp:1492] [5] Reserving 53516544 bytes of shared learnable space for type FLOAT
I0103 16:20:48.981763  6027 net.cpp:1492] [7] Reserving 53516544 bytes of shared learnable space for type FLOAT
I0103 16:20:48.981919  6022 net.cpp:1492] [2] Reserving 53516544 bytes of shared learnable space for type FLOAT
I0103 16:20:48.982205  6023 net.cpp:1492] [3] Reserving 53516544 bytes of shared learnable space for type FLOAT
I0103 16:20:48.982367  6020 net.cpp:1492] [0] Reserving 53516544 bytes of shared learnable space for type FLOAT
F0103 16:20:49.668439  6024 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data type
*** Check failure stack trace: ***
F0103 16:20:49.668428  6023 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data typeF0103 16:20:49.668442  6022 parallel.cpp:204] Check failed: F0 0103 08 in
49.668454  6026 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data typeF0103 16:20:49.668457  6025 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data typeF0103 16:20:49.668447  6020 parallel.cpp:204] Check failed: F0103 16:20:49. 668428  invalid data type6021 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data typeF0103 16:20:49.668447  6027 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data type
*** Check failure stack trace: ***
F0103 16:20:49.668428  6023 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data typeF0103 16:20:49.668442  6022 parallel.cpp:204] Check failed: F0 0103 08 in
49.668454  6026 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data typeF0103 16:20:49.668457  6025 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data typeF0103 16:20:49.668447  6020 parallel.cpp:204] Check failed: F0103 16:20:49. 668428  invalid data type6021 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data typeF0103 16:20:49.668447  6027 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data type
*** Check failure stack trace: ***
F0103 16:20:49.668428  6023 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data typeF0103 16:20:49.668442  6022 parallel.cpp:204] Check failed: F0 0103 08 in
49.668454  6026 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data typeF0103 16:20:49.668457  6025 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data typeF0103 16:20:49.668447  6020 parallel.cpp:204] Check failed: F0103 16:20:49. 668428  invalid data type6021 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data typeF0103 16:20:49.668447  6027 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data type
*** Check failure stack trace: ***
F0103 16:20:49.668428  6023 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data typeF0103 16:20:49.668442  6022 parallel.cpp:204] Check failed: F0 0103 08 in
49.668454  6026 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data typeF0103 16:20:49.668457  6025 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data typeF0103 16:20:49.668447  6020 parallel.cpp:204] Check failed: F0103 16:20:49. 668428  invalid data type6021 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data typeF0103 16:20:49.668447  6027 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data type
*** Check failure stack trace: ***
F0103 16:20:49.668428  6023 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data typeF0103 16:20:49.668442  6022 parallel.cpp:204] Check failed: F0 0103 08 in
49.668454  6026 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data typeF0103 16:20:49.668457  6025 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data typeF0103 16:20:49.668447  6020 parallel.cpp:204] Check failed: F0103 16:20:49. 668428  invalid data type6021 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data typeF0103 16:20:49.668447  6027 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data type
*** Check failure stack trace: ***
F0103 16:20:49.668428  6023 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data typeF0103 16:20:49.668442  6022 parallel.cpp:204] Check failed: F0 0103 08 in
49.668454  6026 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data typeF0103 16:20:49.668457  6025 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data typeF0103 16:20:49.668447  6020 parallel.cpp:204] Check failed: F0103 16:20:49. 668428  invalid data type6021 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data typeF0103 16:20:49.668447  6027 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data type
*** Check failure stack trace: ***
F0103 16:20:49.668428  6023 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data typeF0103 16:20:49.668442  6022 parallel.cpp:204] Check failed: F0 0103 08 in
49.668454  6026 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data typeF0103 16:20:49.668457  6025 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data typeF0103 16:20:49.668447  6020 parallel.cpp:204] Check failed: F0103 16:20:49. 668428  invalid data type6021 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data typeF0103 16:20:49.668447  6027 parallel.cpp:204] Check failed: result == ncclSuccess (13 vs. 0)  invalid data type
*** Check failure stack trace: ***
    @     0x7f4a8b0f1daa  (unknown)
    @     0x7f4a8b0f1daa  (unknown)
    @     0x7f4a8b0f1daa  (unknown)
    @     0x7f4a8b0f1daa  (unknown)
    @     0x7f4a8b0f1daa  (unknown)
    @     0x7f4a8b0f1daa  (unknown)
    @     0x7f4a8b0f1daa  (unknown)
    @     0x7f4a8b0f1daa  (unknown)
    @     0x7f4a8b0f1ce4  (unknown)
    @     0x7f4a8b0f1ce4  (unknown)
    @     0x7f4a8b0f1ce4  (unknown)
    @     0x7f4a8b0f1ce4  (unknown)
    @     0x7f4a8b0f1ce4  (unknown)
    @     0x7f4a8b0f1ce4  (unknown)
    @     0x7f4a8b0f1ce4  (unknown)
    @     0x7f4a8b0f16e6  (unknown)
    @     0x7f4a8b0f16e6  (unknown)
    @     0x7f4a8b0f1ce4  (unknown)
    @     0x7f4a8b0f4687  (unknown)
    @     0x7f4a8b0f4687  (unknown)
    @     0x7f4a8b0f16e6  (unknown)
    @     0x7f4a8b0f16e6  (unknown)
    @     0x7f4a8b0f16e6  (unknown)
    @     0x7f4a8b0f16e6  (unknown)
    @     0x7f4a8b0f16e6  (unknown)
    @     0x7f4a8b0f16e6  (unknown)
    @     0x7f4a8bb2d550  caffe::P2PSync::on_start()
    @     0x7f4a8bb2d550  caffe::P2PSync::on_start()
    @     0x7f4a8b0f4687  (unknown)
    @     0x7f4a8b0f4687  (unknown)
    @     0x7f4a8b0f4687  (unknown)
    @     0x7f4a8b0f4687  (unknown)
    @     0x7f4a8b0f4687  (unknown)
    @     0x7f4a8b0f4687  (unknown)
    @     0x7f4a8bb281f0  caffe::Solver::Step()
    @     0x7f4a8bb281f0  caffe::Solver::Step()
    @     0x7f4a8bb2d550  caffe::P2PSync::on_start()
    @     0x7f4a8bb29988  caffe::Solver::Solve()
    @     0x7f4a8bb2d550  caffe::P2PSync::on_start()
    @     0x7f4a8bb2d550  caffe::P2PSync::on_start()
    @     0x7f4a8bb2d550  caffe::P2PSync::on_start()
    @     0x7f4a8bb2d550  caffe::P2PSync::on_start()
    @     0x7f4a8bb2d550  caffe::P2PSync::on_start()
    @     0x7f4a8bb29988  caffe::Solver::Solve()
    @     0x7f4a8bb2e06e  caffe::P2PSync::InternalThreadEntry()
    @     0x7f4a8bb281f0  caffe::Solver::Step()
    @     0x7f4a8bb2e06e  caffe::P2PSync::InternalThreadEntry()
    @     0x7f4a8bb281f0  caffe::Solver::Step()
    @     0x7f4a8bb281f0  caffe::Solver::Step()
    @     0x7f4a8bb281f0  caffe::Solver::Step()
    @     0x7f4a8bb281f0  caffe::Solver::Step()
    @     0x7f4a8bdeca0a  caffe::InternalThread::entry()
    @     0x7f4a8bb281f0  caffe::Solver::Step()
    @     0x7f4a8bb29988  caffe::Solver::Solve()
    @     0x7f4a8bdeca0a  caffe::InternalThread::entry()
    @     0x7f4a8bded564  boost::detail::thread_data<>::run()
    @     0x7f4a8bb29988  caffe::Solver::Solve()
    @     0x7f4a8bb29988  caffe::Solver::Solve()
    @     0x7f4a8bb29988  caffe::Solver::Solve()
    @     0x7f4a8bb29988  caffe::Solver::Solve()
    @     0x7f4a80f17a4a  (unknown)
    @     0x7f4a8bded564  boost::detail::thread_data<>::run()
    @     0x7f4a8bb29988  caffe::Solver::Solve()
    @     0x7f4a8bb2e06e  caffe::P2PSync::InternalThreadEntry()
    @     0x7f4a8bb2e06e  caffe::P2PSync::InternalThreadEntry()
    @     0x7f4a74c0b184  start_thread
    @     0x7f4a8bb2e06e  caffe::P2PSync::InternalThreadEntry()
    @     0x7f4a8bb2e06e  caffe::P2PSync::InternalThreadEntry()
    @     0x7f4a8bb2e06e  caffe::P2PSync::InternalThreadEntry()
    @     0x7f4a80f17a4a  (unknown)
    @     0x7f4a8a263ffd  (unknown)
    @     0x7f4a8bb2e06e  caffe::P2PSync::InternalThreadEntry()
    @     0x7f4a8bdeca0a  caffe::InternalThread::entry()
    @     0x7f4a74c0b184  start_thread
    @     0x7f4a8bdeca0a  caffe::InternalThread::entry()
    @     0x7f4a8bdeca0a  caffe::InternalThread::entry()
    @     0x7f4a8bdeca0a  caffe::InternalThread::entry()
    @     0x7f4a8bdeca0a  caffe::InternalThread::entry()
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by aazz44ss** [comment]
@drnikolaev  Thanks, I'll try cache.
Here is my bvlc_googlenet 4GPU and 8GPU log running on centos7, 
there are some additional information in log, which i used it to benchmark.
the batch size is 32/GPU.
[4GPU_googlenet.log](https://github.com/NVIDIA/caffe/files/1602198/4GPU_googlenet.log)
[8GPU_googlenet.log](https://github.com/NVIDIA/caffe/files/1602199/8GPU_googlenet.log)

**Comment by drnikolaev** [comment]
@aazz44ss seems like you hit the limit of your disk when you do 8GPU train. Please try `cache: true` and run few epochs to see the difference.

**Comment by aazz44ss** [comment]
@drnikolaev 
I have try cache: true, but the 8GPU performance is still much lower than 4GPU.
maybe my RAM (64G) is not large enough to include my train set (240G)?
but the performance may not only affected by waiting for datum, because 8GPU takes 10 times time than 4 GPU on computing reduce function.

**Comment by drnikolaev** [comment]
@aazz44ss 64G won't work.
10 times? Your logs say:
```
I0104 09:01:34.019235 48726 parallel.cpp:83] Overall multi-GPU performance: 1584.64 img/sec
```
vs.
```
I0103 17:10:30.203011 44152 parallel.cpp:83] Overall multi-GPU performance: 1796.15 img/sec
```
So, 8 GPU is "better". Why 10 times?

**Comment by aazz44ss** [comment]
@drnikolaev 
8GPU is better but not linear scaling,
1 GPU performance 400 img/sec
2 GPU performance 790 img/sec
4 GPU performance 1580 img/sec
8 GPU performance 1790 img/sec

10 times which means I record the time of program use NCCL reduce function.
in 2 GPU it takes 56 sec.
in 4 GPU it takes 78 sec.
in 8 GPU it takes 813 sec.
which increase a lot of time on solver::step iteration_wait(), it affect performance directly.
in 2 GPU it takes 28 sec.
in 4 GPU it takes 39 sec.
in 8 GPU it takes 568 sec.

**Comment by drnikolaev** [comment]
@aazz44ss 
I see. Too much traffic. Could you run the same in float 16 mode please? Just add to your train*.prototxt this:
```
default_forward_type:  FLOAT16
default_backward_type: FLOAT16
default_forward_math:  FLOAT16
default_backward_math: FLOAT16
```
And to your solver*.prototxt this:
```
solver_data_type: FLOAT16
```

**Comment by aazz44ss** [comment]
@drnikolaev 
[8GPU_float16_googlenet.log](https://github.com/NVIDIA/caffe/files/1602366/8GPU_float16_googlenet.log)
I use FLOAT16 won't help improve performance

**Comment by drnikolaev** [comment]
@aazz44ss 
Could you run the following:
```
nvidia-smi topo -m
```
and
```
nvidia-smi topo -p2p n
```
Also, what is `disk2` throughput? Is it local?

**Comment by aazz44ss** [comment]
GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    CPU Affinity
GPU0     X      NV1     NV1     NV1     NV1     SOC     SOC     SOC     0-15,32-47
GPU1    NV1      X      NV1     NV1     SOC     NV1     SOC     SOC     0-15,32-47
GPU2    NV1     NV1      X      NV1     SOC     SOC     NV1     SOC     0-15,32-47
GPU3    NV1     NV1     NV1      X      SOC     SOC     SOC     NV1     0-15,32-47
GPU4    NV1     SOC     SOC     SOC      X      NV1     NV1     NV1     16-31,48-63
GPU5    SOC     NV1     SOC     SOC     NV1      X      NV1     NV1     16-31,48-63
GPU6    SOC     SOC     NV1     SOC     NV1     NV1      X      NV1     16-31,48-63
GPU7    SOC     SOC     SOC     NV1     NV1     NV1     NV1      X      16-31,48-63

**Comment by aazz44ss** [comment]
root@DGX-1:/disk2/gin/caffe-0.16.4# nvidia-smi topo -p2p n
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7
 GPU0   X       OK      OK      OK      OK      NS      NS      NS
 GPU1   OK      X       OK      OK      NS      OK      NS      NS
 GPU2   OK      OK      X       OK      NS      NS      OK      NS
 GPU3   OK      OK      OK      X       NS      NS      NS      OK
 GPU4   OK      NS      NS      NS      X       OK      OK      OK
 GPU5   NS      OK      NS      NS      OK      X       OK      OK
 GPU6   NS      NS      OK      NS      OK      OK      X       OK
 GPU7   NS      NS      NS      OK      OK      OK      OK      X

**Comment by aazz44ss** [comment]
@drnikolaev 
disk2 is hard disk

root@DGX-1:/disk2/gin/caffe-0.16.4# sudo hdparm -Tt /dev/sda
/dev/sda:
 Timing cached reads:   17236 MB in  2.00 seconds = 8626.76 MB/sec
 Timing buffered disk reads: 2754 MB in  3.00 seconds = 917.89 MB/sec

**Comment by drnikolaev** [comment]
@aazz44ss 917MB is way too slow. Do you have raid array?

**Comment by aazz44ss** [comment]
@drnikolaev 
I'll try other disk. what level do you recommend the Timing buffered disk reads throughput?
and how this affect performance ? is this only affect waiting for datum ? or it will also affect NCCL::reduce?

**Comment by drnikolaev** [comment]
@aazz44ss Actually you are ok in terms of disk perf, sorry. This is not AlexNet... :)
So, there might be something with NVLink. Is this DGX-1 box?

**Comment by aazz44ss** [comment]
Yes, I am using DGX-1 box.
and I have test every NVLink, seems like NVLink is fine.

from | to | bandwidth
0 | 1 | 14.5
0 | 2 | 14.5
0 | 3 | 14.5
0 | 4 | 14.5
0 | 5 | 5.5
0 | 6 | 5.5
0 | 7 | 5.5
1 | 2 | 14.5
1 | 3 | 14.5
1 | 4 | 5.5
1 | 5 | 14.5
1 | 6 | 5.5
1 | 7 | 5.5
2 | 3 | 14.5
2 | 4 | 5.5
2 | 5 | 5.5
2 | 6 | 14.5
2 | 7 | 5.5
3 | 4 | 5.5
3 | 5 | 5.5
3 | 6 | 5.5
3 | 7 | 14.5
4 | 5 | 14.5
4 | 6 | 14.5
4 | 7 | 14.5
5 | 6 | 14.5
5 | 7 | 14.5
6 | 7 | 14.5

and also, the performance decade only happened in NVcaffe 0.16 above.
I have test same condition on NVcaffe 0.1513, although performance is not as good as running on NVcaffe 0.16, but scaling is linear increase (1.7X).
1 GPU:333
2 GPU:626
4 GPU:1196
8 GPU:2048

**Comment by drnikolaev** [comment]
@aazz44ss have you upgraded to NCCL2.1, CuDNN 7 and Cuda 9?
