### ISSUE TITLE
How to install the caffe verison?

### ISSUE THREAD

**Issue by nalan210** [NVIDIA/caffe#460]
Excuse me, I am a newcomer for the nvidia/caffe. There isn't any installation guides for me to do the setup work. Now I want to install this latest caffe version(0.16), how could I achieve the setup process and tune the inference process to support FP16 instead of FP32? Thank you very much for your help!

**Comment by drnikolaev** [comment]
@nalan210 This guide should be a good start: 
http://caffe.berkeleyvision.org/installation.html
