### ISSUE TITLE
memory leak while training Mobilenet model

### ISSUE THREAD

**Issue by leon-liangwu** [NVIDIA/caffe#461]
Memory usage is arising while traing Mobilenet model, and the process will be killed due to memory leak.
I find memory leak exists when training models with group channels.
Does anyone have come across the same problem, and how do you solve it?
@drnikolaev

**Comment by drnikolaev** [comment]
@DreamHorse0301 thanks
May I have the log please?

**Comment by leon-liangwu** [comment]
I have only got the training log, and I found that when training the memory usage of this process increased to 100% and the process got killed. 
@drnikolaev 
By the way, I got this issue in the previous tag, 0.16.4. If the issue has not been specifically fixed, it may still exists. 
I am testing with 0.16.5. 

![screenshot from 2018-01-05 11-57-56](https://user-images.githubusercontent.com/7507360/34595182-cc785556-f210-11e7-9525-ec029803fc92.png)

**Comment by drnikolaev** [comment]
@DreamHorse0301 the log above was not generated by v0.16.5, look:
https://github.com/NVIDIA/caffe/blob/caffe-0.16/src/caffe/solvers/sgd_solver.cpp#L136
Line 136 does not print Iteration. Also:
https://github.com/NVIDIA/caffe/blob/caffe-0.15/src/caffe/solver.cpp#L309
https://github.com/NVIDIA/caffe/blob/caffe-0.15/src/caffe/solver.cpp#L331

**Comment by leon-liangwu** [comment]
@drnikolaev 
yes, it's generated by v0.16.4. I wonder if the problem has been fixed in the latest version, v0.16.5? 
I am testing this, and until now it looks ok. 
![2222](https://user-images.githubusercontent.com/7507360/34602121-99a8f9b8-f239-11e7-89bd-f396a803f29b.png)

**Comment by leon-liangwu** [comment]
@drnikolaev 

But unfortunately, it was still killed by the system.
![3333](https://user-images.githubusercontent.com/7507360/34605049-e745cb6e-f244-11e7-9057-03c44ff333ba.png)

**Comment by drnikolaev** [comment]
@DreamHorse0301 may I have complete log attached please? And your model's prototxt files?

**Comment by leon-liangwu** [comment]
@drnikolaev 
[log.mb-reg-0.75-test.txt](https://github.com/NVIDIA/caffe/files/1608955/log.mb-reg-0.75-test.txt)

**Comment by drnikolaev** [comment]
@DreamHorse0301 thanks
I couldn't reproduce the crash itself but I did find and fixed some leaks. Release candidate with the fix is here: https://github.com/drnikolaev/caffe/tree/caffe-0.16
Could you please verify it? 
One note: you may comment out these parameters to speed up training:
```
#    threads: 1
#    parser_threads: 1
```
Also, Massif report (looks better now):
![screenshot from 2018-01-07 21-47-15](https://user-images.githubusercontent.com/7504104/34666556-cbece86c-f419-11e7-9235-10c2c0febda8.png)

**Comment by leon-liangwu** [comment]
@drnikolaev 
Thanks very much. I will try to verify it and tell you the results later.
Thanks again for your recommendation.

**Comment by leon-liangwu** [comment]
Dear @drnikolaev, the leak still exists.

**Comment by drnikolaev** [comment]
@DreamHorse0301 thanks. Could you estimate how much memory gets leaked per iteration?
And please run `ldd build/lib/libcaffe-nv.so` and paste its payload here.

**Comment by leon-liangwu** [comment]
@drnikolaev  the memory leak increase  linearly. At the beginning, it increases faster.
The result of `ldd build/lib/libcaffe-nv.so`  is in the following file.
[ldd_so.txt](https://github.com/NVIDIA/caffe/files/1620992/ldd_so.txt)

**Comment by drnikolaev** [comment]
@DreamHorse0301 but how much? Let say, on 0th iteration it takes 2G but on 50000th it's about 62G. Then we have (62-2)/50000=1.2BM lost per iteration.
No one reported any leaks yet, this is interesting.
Also, these things don't look good:
```
	libprotobuf.so.8 => /usr/lib/x86_64-linux-gnu/libprotobuf.so.8 (0x00007fb0ae1e9000)
	libopencv_core.so.2.4 => /data/3rdparty/lib/libopencv_core.so.2.4 (0x00007fb0ace41000)
	libnccl.so.1 => /home/wuliang/opt/nccl/lib/libnccl.so.1 (0x00007fb09ca72000)
```
Here are mine:
```
	libprotobuf.so.9 => /usr/lib/x86_64-linux-gnu/libprotobuf.so.9 (0x00007fe8739a1000)
	libopencv_core.so.3.4 => /usr/lib/x86_64-linux-gnu/libopencv_core.so.3.4 (0x00007fe872690000)
	libnccl.so.2 => /usr/lib/libnccl.so.2 (0x00007fe8593fb000)
```
Makes sense to upgrade.

**Comment by leon-liangwu** [comment]
@drnikolaev  I trained mobilenet on 4 Tiatan X GPUs with batch size 256.
The max iteration is 500,000. 
Maybe you can try to reproduce it 
My server machine has 128GB memory, and the memory will be fully consummed during the training.

**Comment by leon-liangwu** [comment]
@drnikolaev  Thanks. I will update these libraries and try to rerun the process.

**Comment by drnikolaev** [comment]
@DreamHorse0301 I did try and I did use Titans. No leak. See picture above.

**Comment by leon-liangwu** [comment]
@drnikolaev  Fine. Let me replace the 3 libraries, and let you know later.

**Comment by leon-liangwu** [comment]
Dear @drnikolaev.  Only 1.6GB memory was consumed on your cpu memory ? 
Gpu memory used is stable.

**Comment by drnikolaev** [comment]
@DreamHorse0301 yes but I had to reduce dataset size due to Valgrind limitations.

**Comment by leon-liangwu** [comment]
@drnikolaev  in io.cpp , line 107, The shape_only condition block should be inserted in one line .

**Comment by drnikolaev** [comment]
@DreamHorse0301 this? https://github.com/drnikolaev/caffe/blob/caffe-0.16/src/caffe/util/io.cpp#L107-L110

I'm not sure I follow...

**Comment by leon-liangwu** [comment]
@drnikolaev  Yes, your repo is right. 
I know this is not the reason the process got killed, because my lmdb is not encoded.
I replaced nccl v1 with nccl v2, and it has been running 8 hours without being killed.

**Comment by drnikolaev** [comment]
@DreamHorse0301 
Please also try  https://github.com/drnikolaev/caffe/tree/caffe-0.17

**Comment by leon-liangwu** [comment]
@drnikolaev  Thanks very much. 
Even the valgrind can not find any leek. The memory arising is mainly caused by the data cache. 
The training still can be killed by the system after a long time running, maybe 12 hours.
By the way, my gpus are Titan X pascal.

**Comment by drnikolaev** [comment]
@DreamHorse0301 did you try other models? ResNet-50 may be? Also, could you switch to OpenCV 3.4?

**Comment by leon-liangwu** [comment]
Dear @drnikolaev,

Finally, I find the true reason why the training can be killed through time. 
It is due to the GPU type and its driver. If I use TITAN X (Pascal) with driver version 375.39, the process will definetely be killed.  When I train on new GPUs whose type is TITAN Xp, the killing will not happen. And the training has been OK for more than 48 hours. I believe the reason is this. 

Thanks a lot for your help.
And if you have the devices, you can reproduce the killing, and maybe you can also report to your colleagues related.

**Comment by drnikolaev** [comment]
Thanks @DreamHorse0301 for the update!
