### ISSUE TITLE
ClipGradients() behavior diverges from BVLC caffe

### ISSUE THREAD

**Issue by constroy** [NVIDIA/caffe#462]
In BVLC caffe, ClipGradients() rescales the gradients based on their L2 norm.
But in Nvidia caffe, a gradient is cleared once updated. Thus the gradients are all zeros except the currently updating one. L2 norm degenerates into absolute value of that only gradient. As a result, ClipGradients() rescales gradients element-wise.

**Comment by drnikolaev** [comment]
@constroy thanks.
Could you set solver's `snapshot_diff: true` and verify that clipping works as it's supposed to?

**Comment by constroy** [comment]
@drnikolaev thanks for your reply
If `snapshot_diff: true` is set, some gradients become lastest values (already reduced from all solvres), but others still remain zeros since ClearParamDiffs() (not back-proped and reduced yet). So the L2 norm is not calculated correctly.

**Comment by drnikolaev** [comment]
@constroy it's fixed. Fix is coming in the next release. For early access please use https://github.com/drnikolaev/caffe/tree/caffe-0.17
