### ISSUE TITLE
Missing libturbojpeg.so

### ISSUE THREAD

**Issue by twmht** [NVIDIA/caffe#463]
Hi,

I am using ubuntu 16.04 and have installed both `libjpeg-turbo8-dev` and  `libjpeg-turbo8`.

However, I can not find libturbojpeg.so as in https://github.com/NVIDIA/caffe/blob/caffe-0.16/cmake/Modules/FindJPEGTurbo.cmake

there is only one static library `libturbojpeg.a` in `/usr/lib/x86_64-linux-gnu/`.

If I link to the static file, it will throw the errors when make

```
[ 82%] Linking CXX shared library ../../lib/libcaffe-nv.so
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-turbojpeg.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC

```

was something important I missed?

thank you

**Comment by twmht** [comment]
after installing `libturbojpeg`, the problem can be solved.

**Comment by psyhtest** [comment]
To confirm, this did the trick for me to:
```
$ sudo apt install libturbojpeg
```
