### ISSUE TITLE
add new SolverParameter bug

### ISSUE THREAD

**Issue by leon-liangwu** [NVIDIA/caffe#464]
When add new solver parameter in message SolverParameter ,
like repeated int32 param_iter = 55;
in caffe.proto.

Error will occur when run training. 
  
![444](https://user-images.githubusercontent.com/7507360/34641283-8c0efa24-f33c-11e7-9b60-ae46f51b949e.png)

**Comment by leon-liangwu** [comment]
[log.txt](https://github.com/NVIDIA/caffe/files/1608958/log.txt)
@drnikolaev

You can try to add a new repeated parameter in message SolverParameter of the caffe.proto, and train a model. You will get an error like the above.

Could you please solve this problem?

**Comment by drnikolaev** [comment]
@DreamHorse0301 I can't reproduce this. I'd suggest to rebuild the whole world when you touch `caffe.proto`. Begin with `make superclean`.

**Comment by leon-liangwu** [comment]
@drnikolaev 
Thanks very much. It really helps.
