### ISSUE TITLE
Python 0.16.5: Deleting net invalidates all previous GPU memory allocations?

### ISSUE THREAD

**Issue by gomlgs** [NVIDIA/caffe#466]
We're using pycaffe, and are running into an issue with using multiple nets in the same process. When an existing net is gc'ed from Python, it seems to make other previously created nets stop working.

Specifically, the crash is (with DEBUG), in convolutional layers:
```
/usr/include/boost/smart_ptr/shared_ptr.hpp:648: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = caffe::GPUMemory::Workspace; typename boost::detail::sp_member_access<T>::type = caffe::GPUMemory::Workspace*]: Assertion `px != 0' failed.
```

This appears to be because of a call to `GPUMemory::Finalize()` in src/caffe/layers/cudnn_conv_layer.cpp:~CuDNNConvolutionLayer, which in turn resets the GPU memory workspace for the entire device. It looks like this code was actually added in 0.16.4, but we skipped from 0.16.3 to 0.16.5 so missed this issue previously.

I can confirm that commenting out that line causes our code to work "correctly" - but I'm not sure if memory deallocations are happening correctly.

Is this not a supported use case?

**Comment by drnikolaev** [comment]
Hi @gomlgs thank you. This Finalize call is redundant, you can remove it. It's just a leftover missed to be cleaned.

**Comment by gomlgs** [comment]
@drnikolaev Thanks, I created https://github.com/NVIDIA/caffe/pull/467 .

**Comment by drnikolaev** [comment]
Done here: https://github.com/drnikolaev/caffe/tree/caffe-0.17
Coming soon in next release.
