### ISSUE TITLE
How to add layers from the private version?

### ISSUE THREAD

**Issue by zhouyongxiu** [NVIDIA/caffe#469]
Hi, I try to add the margin_inner_product_layer(https://github.com/wy1iu/sphereface/blob/master/tools/caffe-sphereface/include/caffe/layers/margin_inner_product_layer.hpp) from the sphereface(https://github.com/wy1iu/sphereface/tree/master/tools/caffe-sphereface), but there are errors when I make the files. I find it is lead by the layer and blob is redefined in NVIDIA caffe  version. Is there any method to add the new layers without redefine the all type in new function.

**Comment by drnikolaev** [comment]
@zhouyongxiu the only method is to redefine margin_inner_product_layer.

**Comment by zhouyongxiu** [comment]
@drnikolaev thank you!
