### ISSUE TITLE
Does this Caffe support multiGPUs

### ISSUE THREAD

**Issue by linnanwang** [NVIDIA/caffe#47]
hello,

caffe arguments suggest multiGPU support, I'm asking to verify this point. Thank you.

**Comment by lukeyeager** [comment]
Yes, this fork of Caffe has supported multi-GPU support since version 0.12.
https://github.com/NVIDIA/caffe/releases

**Comment by alfredox10** [comment]
I have only found documentation on how to enable multi-GPU training, what about multi-GPU detection with the caffemodel file? For the python interface there is this command:
caffe.set_device(gpuid) 
however it only takes one id at a time, how can we set it for multiple GPUs?
