### ISSUE TITLE
Initialize GPU memory have a high peak with float16

### ISSUE THREAD

**Issue by zhouyongxiu** [NVIDIA/caffe#470]
Hi, when I try to float16 with resnet 50, I find that when I set train batch size is 32, test batch size is 1, the GPU memory usage will rise to 11000MB in initialize stage, and then drop to 6800MB in train stage, so I cannot set the train batch size more then 32. My GPU is 1080ti, CUDA=8.0, cudnn=7.0, nvcaffe=0.16.5.

**Comment by drnikolaev** [comment]
@zhouyongxiu  Initial usage is Algo Finder, it's trying to take everything even for small batches. In pure fp16 mode v0.16.5 fits batch of 128 cropped images (224x224) on a GPU with 16GB of memory. 1080ti should handle 96. Please post here your RN-50 prototxt files, we might help.

**Comment by zhouyongxiu** [comment]
@drnikolaev  there is my prototxt file, please check.
[resnet50_solver.txt](https://github.com/NVIDIA/caffe/files/1638761/resnet50_solver.txt)
[ResNet_50_train_val.txt](https://github.com/NVIDIA/caffe/files/1638762/ResNet_50_train_val.txt)

**Comment by drnikolaev** [comment]
Hi @zhouyongxiu we did some improvements after your report, thank you. This is pre-release, could you give it a try?
https://github.com/drnikolaev/caffe/tree/caffe-0.17

**Comment by zhouyongxiu** [comment]
@drnikolaev thanks for your work, the new version solve the problem, and it has better performance on multi GPU compare with old version, thank you!
