### ISSUE TITLE
make: *** [.build_release/tools/caffe.bin] Error 1

### ISSUE THREAD

**Issue by haruky** [NVIDIA/caffe#471]
Hi, I need some help to make nvcaffe. There is some problems, did i any mistakes?  
The caffe make is stopped with below error message.

CXX/LD -o .build_release/tools/caffe.bin
.build_release/lib/libcaffe-nv.so: undefined reference to `boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >::maybe_assign(boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > const&)'
.build_release/lib/libcaffe-nv.so: undefined reference to `boost::re_detail::raise_runtime_error(std::runtime_error const&)'
.build_release/lib/libcaffe-nv.so: undefined reference to `boost::re_detail::put_mem_block(void*)'
.build_release/lib/libcaffe-nv.so: undefined reference to `boost::re_detail::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
.build_release/lib/libcaffe-nv.so: undefined reference to `boost::re_detail::get_mem_block()'
.build_release/lib/libcaffe-nv.so: undefined reference to `boost::re_detail::verify_options(unsigned int, boost::regex_constants::_match_flags)'
.build_release/lib/libcaffe-nv.so: undefined reference to `boost::re_detail::get_default_error_string(boost::regex_constants::error_type)'
.build_release/lib/libcaffe-nv.so: undefined reference to `boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::do_assign(char const*, char const*, unsigned int)'
.build_release/lib/libcaffe-nv.so: undefined reference to `boost::re_detail::cpp_regex_traits_implementation<char>::transform(char const*, char const*) const'
.build_release/lib/libcaffe-nv.so: undefined reference to `boost::re_detail::cpp_regex_traits_implementation<char>::transform_primary(char const*, char const*) const'
collect2: error: ld returned 1 exit status
Makefile:659: recipe for target '.build_release/tools/caffe.bin' failed
make: *** [.build_release/tools/caffe.bin] Error 1

The libcaffe-nv.so said 'undefined reference to `boost::match_results...'
But, i already installed the boost dev tools and the other version caffe is already running on our environment..
Thanks all.

**Comment by drnikolaev** [comment]
Hi @haruky what Linux do you use? How do you run the build? Could you try CMake please?

**Comment by haruky** [comment]
Hi, thanks comment. I use ubuntu 16.04.3 LTS,
I solve this Make problems by https://github.com/rbgirshick/fast-rcnn/issues/52 .
I add a definition in Makefile.
263 LIBRARIES += boost_thread stdc++ boost_regex
Then, i got better result.
Thank you.

**Comment by WUhailing** [comment]
@drnikolaev ubuntu17.10, cuda8, opencv3.3, g++-5, boost1.6.2(sudo apt-get install), neither cmake nor make can work.  Adding boost_regex to LIBRARIES makes no difference. Any suggestions?

**Comment by drnikolaev** [comment]
@WUhailing could you paste the payload please?

**Comment by WUhailing** [comment]
Hi @drnikolaev this is the error output file using cmake,
[ 84%] Linking CXX executable caffe
/usr/bin/cmake: /home/hailing/anaconda3/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `boost::re_detail_106200::cpp_regex_traits_implementation<char>::transform(char const*, char const*) const'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `boost::re_detail_106200::cpp_regex_traits_implementation<char>::transform_primary(char const*, char const*) const'
collect2: error: ld returned 1 exit status
tools/CMakeFiles/caffe.bin.dir/build.make:141: recipe for target 'tools/caffe' failed
make[2]: *** [tools/caffe] Error 1
CMakeFiles/Makefile2:517: recipe for target 'tools/CMakeFiles/caffe.bin.dir/all' failed
make[1]: *** [tools/CMakeFiles/caffe.bin.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

FYI, I just comment out regex,rv lines in detection_output_layer.cu, regex,rv and #include<boost/regex.hpp> lines in detection_output_layer.hpp, and it does the trick.

**Comment by pupu1998** [comment]
I have the same problems. But the solution can't solve it. My problem like this :

make: *** [.build_release/tools/upgrade_net_proto_binary.bin] Error 1
make: *** Waiting for unfinished jobs....
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libboost_python.so: undefined reference to `PyClass_Type'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libboost_python.so: undefined reference to `PyString_FromString'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libboost_python.so: undefined reference to `PyFile_AsFile'
