### ISSUE TITLE
Don't install django 2: it requires python >= 3.4

### ISSUE THREAD

**Issue by thomas-riccardi** [NVIDIA/caffe#472]
# Some context
- Commit https://github.com/NVIDIA/caffe/commit/4ab7348cc0a9a0e306dc97f06925bab0de7cb778 added `image` and `django` to `python/requirements.txt`.
- It's not clear why `django` was needed: the commit message only talks about `image`, and a grep in `python/` reveals no `django` usage.
- `image` usage was removed by commit https://github.com/NVIDIA/caffe/commit/5eab61dc7b3a5852529bea711aa4c67f9f097714#diff-2d462ed1996a384d046687b756701360L10: replaced by pillow. (see https://github.com/NVIDIA/caffe/commit/5eab61dc7b3a5852529bea711aa4c67f9f097714#diff-d86c2fdd3201fda455d5aee979a57a9cL12 for usage, and https://github.com/NVIDIA/caffe/commit/5eab61dc7b3a5852529bea711aa4c67f9f097714#diff-2d462ed1996a384d046687b756701360L10 for pillow installation); but `image` is still installed, probably for nothing.

# Issue
Installing `django>=1.11.5` makes `pip` install `django 2`, which requires `python >= 3.4.0`, which is not available in the various installation Dockerfiles (python2 is installed):
- here: https://github.com/NVIDIA/caffe/tree/caffe-0.16/docker
- docker digits (with nvcaffe 0.15): https://gitlab.com/nvidia/digits/blob/efbe7671d197c9c1d6b6bcf565566c72b8762bee/6.0/Dockerfile

This breaks (at least) the build of digits when using nvcaffe 0.16.5.

# Remarks/cleanup TODO?
- if django is not used: just remove it from `python/requirements.txt`, else limit to `<2`: `django>=1.11.5,<2`
- cleanup unused `image` in `python/requirements.txt`: always use pillow
- https://github.com/NVIDIA/caffe/tree/caffe-0.16/docker seems outdated: older and different than nvidia/digits build of nvcaffe (https://gitlab.com/nvidia/digits/blob/efbe7671d197c9c1d6b6bcf565566c72b8762bee/6.0/Dockerfile); and than https://github.com/NVIDIA/caffe/blob/caffe-0.16/scripts/travis/: is it deprecated? maybe say it in the README?
- why is pillow only installer for python 2 and not python 3? https://github.com/NVIDIA/caffe/blob/52ccc5c626d6aedb78207960900126663b77e1f3/scripts/travis/install-python-deps.sh#L10

**Comment by drnikolaev** [comment]
Hi @thomas-riccardi thanks. This pre-release has the fix, could you give it a try?
https://github.com/drnikolaev/caffe/tree/caffe-0.17

**Comment by thomas-riccardi** [comment]
Hi @drnikolaev , your branch indeed removes the django dependency, fixing my initial issue.

However, it does not address the other points: 
- I believe `image` could also be removed
- what about `docker/` ?
- ~~pillow python3~~ pillow is installed via python3-pil, so it's OK
