### ISSUE TITLE
Failed to parse SolverParameter file: models/resnet50/solver.prototxt in example

### ISSUE THREAD

**Issue by haruky** [NVIDIA/caffe#473]
Hi, I attempted to train resnet50, but it does not work. Some solver parameter fields are not matched to definition.

~/caffe$ ./models/resnet50/train_resnet50.sh 
I0119 20:04:23.812739 32156 caffe.cpp:472] This is NVCaffe 0.16.5
I0119 20:04:23.812930 32156 caffe.cpp:475] CuDNN version: 7005
I0119 20:04:23.812935 32156 caffe.cpp:476] CuBLAS version: 9010
I0119 20:04:23.812937 32156 caffe.cpp:477] CUDA version: 9010
I0119 20:04:23.812939 32156 caffe.cpp:478] CUDA driver version: 9010
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.SolverParameter: 14:14: Message type "caffe.SolverParameter" has no field named "local_lr_auto".
F0119 20:04:23.834980 32156 upgrade_proto.cpp:1063] Check failed: ReadProtoFromTextFile(param_file, &param) Failed to parse SolverParameter file: models/resnet50/solver.prototxt
*** Check failure stack trace: ***
    @     0x7f8d3801f5cd  google::LogMessage::Fail()
    @     0x7f8d38021433  google::LogMessage::SendToLog()
    @     0x7f8d3801f15b  google::LogMessage::Flush()
    @     0x7f8d38021e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f8d38de3b22  caffe::ReadSolverParamsFromTextFileOrDie()
    @           0x40d65b  train()
    @           0x40aa98  main
    @     0x7f8d365b9830  __libc_start_main
    @           0x40b339  _start
    @              (nil)  (unknown)
Aborted (core dumped)

It seems the libprotobuf does not have a field for local_lr_auto.
Should i update any libraries or,, did i some mistake ?
Thanks.

**Comment by drnikolaev** [comment]
Hi @haruky it's a leftover, sorry. We'll clean this in next release. Please use:
```
larc: true
larc_policy: "clip"
larc_eta: 0.002
```

**Comment by haruky** [comment]
Hi Thanks! I want t train resnet50 with lars LR option in model examples. 
I think a local_lr_auto is used to enable a layer basis LR adaptation by lars function, is it collect? 
But, how to correct those definition to enable a lars function. (i'm looking at solver_lars.prototxt. )
Thanks!

**Comment by drnikolaev** [comment]
Hi @haruky local_lr_auto was experimental feature. It' now replaced by `larc`. See my comment above
