### ISSUE TITLE
gpu memory consume more on 0.16.5 than that on 0.16.4

### ISSUE THREAD

**Issue by leon-liangwu** [NVIDIA/caffe#476]
@drnikolaev 

Gpu consumption on 0.16.5 and 0.16.4. I find that it needs much more gpu memory on 0.16.5.
![mb-0 75-zero_loss-0 16 4](https://user-images.githubusercontent.com/7507360/35717252-fc71e2ea-0818-11e8-8604-db1d6024359a.png)
![mb-0 75-zero_loss_0 16 5](https://user-images.githubusercontent.com/7507360/35717259-01edbb72-0819-11e8-8123-2304b51e5b9c.png)

Try this zero_loss:
[zero_loss_layer.hpp.txt](https://github.com/NVIDIA/caffe/files/1688099/zero_loss_layer.hpp.txt)
[zero_loss_layer.cpp.txt](https://github.com/NVIDIA/caffe/files/1688100/zero_loss_layer.cpp.txt)
[mb-0.75-zero_loss.prototxt.txt](https://github.com/NVIDIA/caffe/files/1688101/mb-0.75-zero_loss.prototxt.txt)

**Comment by leon-liangwu** [comment]
Dear @drnikolaev, could please help me to solve this problem?
This is needed because if too much memory used on gpu 0, no other training can be run on other gpus.
Please.

**Comment by drnikolaev** [comment]
hi @DreamHorse0301 what CUDA/CuDNN/NCCL versions do you use?

**Comment by leon-liangwu** [comment]
@drnikolaev 
I am using
cuda 8.0,
cudnn 7.0 ,
nccl 2.1.

**Comment by drnikolaev** [comment]
@DreamHorse0301 could you paste `nvidia-smi` output (while you train) here?

**Comment by DreamHorse0301** [comment]
@drnikolaev 
![11](https://user-images.githubusercontent.com/7507360/35953310-efafafba-0cbe-11e8-9791-9ac69e3fbfd3.png)

**Comment by leon-liangwu** [comment]
@drnikolaev 
Can you reproduce that with the attachments?

**Comment by leon-liangwu** [comment]
@drnikolaev 
![22](https://user-images.githubusercontent.com/7507360/35955065-28c296d8-0cc8-11e8-9632-ebb8eccd1811.png)

**Comment by drnikolaev** [comment]
@DreamHorse0301 well, I see even distribution among 6 out of 8, but 4th and 5th are down. Are you running with `-gpu=all`? Could you paste `nvidia-smi topo -m` here?
Also, this snapshot is missing bottom part with caffe process details.

**Comment by leon-liangwu** [comment]
@drnikolaev  Im running on 6 and 7.

**Comment by leon-liangwu** [comment]
@drnikolaev 
![333](https://user-images.githubusercontent.com/7507360/35958238-a3d4b056-0cda-11e8-99ab-7d863a8bd6d8.png)

**Comment by drnikolaev** [comment]
Hi @DreamHorse0301 while running your model with v0.16.6 and CUDA 9.0 I get this:
```
Thu Feb  8 16:20:05 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.112                Driver Version: 384.112                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro GP100        Off  | 00000000:01:00.0  On |                    0 |
| 54%   75C    P0   153W / 235W |   5204MiB / 16272MiB |     92%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Quadro GP100        Off  | 00000000:02:00.0 Off |                  Off |
| 51%   71C    P0   133W / 235W |   4200MiB / 16273MiB |     93%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       459      C   ...v/caffe/cmake-build-debug/tools/caffe-d  4189MiB |
|    0      1498      G   /usr/lib/xorg/Xorg                           563MiB |
|    0      2410      G   compiz                                       369MiB |
|    0      3449      G   /usr/lib/firefox/firefox                      78MiB |
|    1       459      C   ...v/caffe/cmake-build-debug/tools/caffe-d  4189MiB |
+-----------------------------------------------------------------------------+

```

**Comment by leon-liangwu** [comment]
@drnikolaev 
Maybe the problem I proposed before was not exact.
I have tested several times on v0.16.5. Finally, I found the problem.
With same base model, when the feature map is 7x7, the gpu memory is ok. But, if I cut all the layers whose outputs are 7x7  feature maps leaving 14x14 to be the top feature map, and send it to zero loss. The memory doubles. 
As the net is getting smaller, the gpu memory consumption should decrease, but it did not. This still occurs on v0.16.6.

[MobileNet_deploy_0.75-14x14.prototxt.txt](https://github.com/NVIDIA/caffe/files/1710098/MobileNet_deploy_0.75-14x14.prototxt.txt)
[MobileNet_deploy_0.75-7x7.prototxt.txt](https://github.com/NVIDIA/caffe/files/1710099/MobileNet_deploy_0.75-7x7.prototxt.txt)

Please check.

**Comment by leon-liangwu** [comment]
Dear @drnikolaev ,
Can you reproduce what I came across ? I am very confused about this. The memory should decrease if I remove all the top 7x7 output layers leaving 14x14 to be the top feature map. 
If you see the same phenomenon, could you please help me to solve this?
Help ~ ~

**Comment by drnikolaev** [comment]
Hi @DreamHorse0301 I tried and got this for 7x7:
```
|    0     27836      C   ...v/caffe/cmake-build-debug/tools/caffe-d  4177MiB |
|    1     27836      C   ...v/caffe/cmake-build-debug/tools/caffe-d  4177MiB |
```
and this for 14x14:
```
|    0     27979      C   ...v/caffe/cmake-build-debug/tools/caffe-d  4001MiB |
|    1     27979      C   ...v/caffe/cmake-build-debug/tools/caffe-d  4001MiB |
```
I suspect that in your case Algorithm Finder chooses other one requiring more memory. Please hard set all algorithms to the defaults like this:
```
name: "MobileNet"
default_conv_algos_override: "1,1,1"
layer {
...
```
and compare.

**Comment by leon-liangwu** [comment]
@drnikolaev 
Yes, it really helps. Thanks a lot. 
But I did not figure out what this parameter mean. Could you please give me some thing to understand this?

**Comment by drnikolaev** [comment]
@DreamHorse0301 here we go:
https://github.com/NVIDIA/caffe/blob/caffe-0.16/src/caffe/proto/caffe.proto#L189-L190
https://github.com/NVIDIA/caffe/blob/caffe-0.16/src/caffe/proto/caffe.proto#L926-L933

**Comment by leon-liangwu** [comment]
@drnikolaev ，
But I tested and find the speed is more slower.

**Comment by drnikolaev** [comment]
@DreamHorse0301 Yes. This is the deal: more memory -> faster algorithm.

**Comment by leon-liangwu** [comment]
@drnikolaev  However, By using this parameter, 0.16.5 is 15% slower than 0.16.4 which does need to set this parameter.

**Comment by drnikolaev** [comment]
@DreamHorse0301 could you try 0.16.6 please?

**Comment by leon-liangwu** [comment]
@drnikolaev  It is the same as 0.16.5. But it is ok. I am just confused why 0.16.4 uses much less memory and can be fast.

**Comment by drnikolaev** [comment]
hi @DreamHorse0301 we reproduced this problem and we plan to fix it in next release. Thank you.

**Comment by leon-liangwu** [comment]
@drnikolaev  Thanks very much.

**Comment by drnikolaev** [comment]
@DreamHorse0301 please check this pre-release: https://github.com/drnikolaev/caffe/tree/caffe-0.17
