### ISSUE TITLE
Multi-GPU difference with BVLC/Caffe

### ISSUE THREAD

**Issue by dashesy** [NVIDIA/caffe#477]
What is the benefit of using Nvidia/caffe over BVLC/caffe when it comes to multi-gpu training/testing? Can I use NVIDIA/caffe with mpirun on multiple nodes for distributed learning?

**Comment by drnikolaev** [comment]
Hi @dashesy in multi-gpu department you may find it a little bit faster and more accurate. Here 
https://github.com/NVIDIA/caffe/tree/models
you can find an example of RN-50 trained in 5h 51m to 76.77% top-1 and 93.33% top-5 accuracy.
No multi-node support though.
