### ISSUE TITLE
NVcaffe install  error

### ISSUE THREAD

**Issue by 331744738** [NVIDIA/caffe#478]
System:CentOS 7.4 x86_64
GPU:Tesla V100
cuda9.0 cudnnV7 nccl2    NVIDIA-SMI 384.111  
Rely on:#yum install  -y protobuf-devel   leveldb-devel   snappy-devel   opencv-devel   boost-devel 
                                      hdf5-devel  gflags-devel   glog-devel   lmdb-devel   openblas-devel

version :  NVcaffe 0.16.6
#make all -j 4 
CXX/LD -o .build_release/tools/upgrade_solver_proto_text.bin
CXX/LD -o .build_release/examples/cifar10/convert_cifar_data.bin
CXX/LD -o .build_release/examples/cpp_classification/classification.bin
CXX/LD -o .build_release/examples/mnist/convert_mnist_data.bin
CXX/LD -o .build_release/examples/siamese/convert_mnist_siamese_data.bin
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml
/usr/bin/ld: cannot find -lopencv_imgcode
collect2: error: ld returned 1 exit status
make: *** [.build_release/lib/libcaffe-nv.so.0.16.5] Error 1
make: *** Waiting for unfinished jobs....

Can you tell me how to solve?

**Comment by drnikolaev** [comment]
Hi @331744738 seems like you've got old OpenCV version. Please try to upgrade to 3.4.

**Comment by 331744738** [comment]
Thank you for your guidance I upgrade try

**Comment by 331744738** [comment]
opencv  upgrade to 3.4 after , Suggest a variety of incompatible
![6nc w 7 00m 8zifoshsm5](https://user-images.githubusercontent.com/36323810/36060724-1882da80-0e8a-11e8-8382-c162f3d8742c.png)

**Comment by 331744738** [comment]
@drnikolaev 
opencv3.4 
make all -j4
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml

**Comment by drnikolaev** [comment]
@331744738 This library comes with the driver. Try to update it. The best way is to install CUDA 9

**Comment by 331744738** [comment]
@drnikolaev 
By using CUDA version is 9 now

**Comment by 331744738** [comment]
@drnikolaev 
make all -j16  caffe1是没有问题的可以正常运行
make all -j16  NVcaffe下就会出现这个问题，很头痛，NVcaffe 是否有特别的设置

**Comment by 331744738** [comment]
@drnikolaev 
There is no question of the make caffe1 can run normally
Make NVcaffe will appear this problem, very headache, NVcaffe whether there is a special setting

**Comment by cliffwoolley** [comment]
The message about skipping an incompatible library is caused by 32-bit vs. 64-bit mismatches.  Can you verify your compilation settings in this regard, please?

**Comment by 331744738** [comment]
@cliffwoolley 
Compile settings refers to?

**Comment by 331744738** [comment]
@drnikolaev 
HI:
Opencv has been upgraded to 3.4, but the problem persists, ask ~ Is there any other problems
[root@master ~]#make all -j4
...
...
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml

**Comment by drnikolaev** [comment]
Hi @331744738 
To resolve this, please do the following:

1. Delete (or move to some temporary directory) this file: `/usr/lib/libnvidia-ml.so`. This is wrong version which has nothing to do with NVCaffe.
2. Check the driver version by running
```
$ nvidia-smi | grep Version
| NVIDIA-SMI 384.112                Driver Version: 384.112                   |
```
3. Verify that the right version exists here: `/usr/lib/nvidia-XYZ/libnvidia-ml.so` where `XYZ` stands for driver version. For example, on my machine I have this one:
```
$ ls /usr/lib/nvidia-384/libnvidia-ml*
/usr/lib/nvidia-384/libnvidia-ml.so  /usr/lib/nvidia-384/libnvidia-ml.so.1  /usr/lib/nvidia-384/libnvidia-ml.so.384.112
```
4. If it doesn't exist, reinstall the driver.

**Comment by HITxuefeng** [comment]
are you solved this problem. I also meet it. But i have solved. this problem because libnvidia-ml.so was compiled 32byte.so when you use the OS is 64 byte it will appear this error。you look this :https://blog.csdn.net/some_times/article/details/36187101
