### ISSUE TITLE
TensorRT vs NVIDIA/caffe

### ISSUE THREAD

**Issue by TimoSaemann** [NVIDIA/caffe#479]
Hi @drnikolaev

I would like to run a model for semantic segmentation on my TX2 board (with FP 16) and wonder whether TensorRT or NVIDIA/caffe is more suitable in terms of inference time. 
Which one provides a better performance on the TX2 board or does it make no difference?
Is there a performance comparison?

Second question: 
As far as I understand, I can use TensorRT to convert an existing caffemodel from FP 32 to FP 16. Is this also possible with NVIDIA/caffe or is it better to train the model with FP 16 again to avoid the conversion?

Thanks,
Timo

**Comment by drnikolaev** [comment]
Hi @TimoSaemann , NVCaffe doesn't support it yet. The only choice so far is TRT.

**Comment by TimoSaemann** [comment]
I don't understand exactly what do you mean by "doesn't support it". 
It's no problem to use NVcaffe on the TX2 board, isn't it? 
I can also use the BVLC/Caffe. Only it does not support FP 16.

**Comment by drnikolaev** [comment]
@TimoSaemann sorry, wrong chat :)
Yes, NVcaffe does work on TX2. And it can read any model (as well as TRT 3.0), be it 16 or 32 bit. It reads it once in the beginning and converts if needed. So, performance impact shouldn't be that big. But 16->16 way is definitely better

**Comment by TimoSaemann** [comment]
By 16->16 way, you mean to train the model with FP 16 instead of FP 32, don't you? Why is this better?
And is it only better for NVcaffe or is the same for TRT?

**Comment by drnikolaev** [comment]
It's faster to train. As of term "better" - if we measure accuracy, then it's pretty much the same. If we measure space taken, FP16 model is 2X smaller.

**Comment by TimoSaemann** [comment]
Thanks @drnikolaev !
