### ISSUE TITLE
How does NVCaffe work on MultiGPUs?

### ISSUE THREAD

**Issue by linnanwang** [NVIDIA/caffe#48]
Hello All,

Can anyone kindly explain me how does this caffe branch work on multiGPUs (at code level)? Thank you.

**Comment by lukeyeager** [comment]
I'll point you to the original Multi-GPU pull request, which has a large discussion about implementation:
https://github.com/BVLC/caffe/pull/2114

Note that some changes were made before it was finally merged into BVLC (and later, then this fork):
https://github.com/BVLC/caffe/pull/2903
