### ISSUE TITLE
Running script error

### ISSUE THREAD

**Issue by 331744738** [NVIDIA/caffe#481]
1.make runtest 
![y0a _owh_u6ldw 9gb7ag6](https://user-images.githubusercontent.com/36323810/36707453-5884ce82-1ba9-11e8-926a-d8482a2089c0.png)
2.Operation operation
![5 vc3t a 2 3 3ea xc m0](https://user-images.githubusercontent.com/36323810/36707547-bcfe3dbc-1ba9-11e8-8a36-0d37784b9f27.png)

problem
1.make runtest Does the results prove that the nvcaffe installation is correct?
2.Whether the error prompted by the operation is related to the vncaffe installation？

**Comment by drnikolaev** [comment]
hi @331744738 installation seems to be correct (runtest is good indicator) but it's hard to make sure without complete log and your prototxt files

**Comment by 331744738** [comment]
@drnikolaev 
![0 s2s_l 7 kuax kv8sj](https://user-images.githubusercontent.com/36323810/36710321-31c6b6de-1bb8-11e8-9776-ac15218cfbcf.png)

**Comment by 331744738** [comment]
@drnikolaev 

是否要打印一次安装过程

是否要打印一次安装过程

Do you want to print an installation process

**Comment by 331744738** [comment]
@drnikolaev 

Do you want to print an installation process

**Comment by 331744738** [comment]
@drnikolaev 
Want to ask! Does NVcaffe have a specific installation tutorial under Linux Centos7.*

**Comment by drnikolaev** [comment]
@331744738 I mean the log with Seg Fault. As of CentOS - not yet, sorry

**Comment by 331744738** [comment]
@drnikolaev  
 How should I get such a log

**Comment by drnikolaev** [comment]
```
$caffe train --solver=mysolver --gpu=all 2>&1 | tee caffe_segfault.log
```

**Comment by 331744738** [comment]
@drnikolaev 
$caffe train --solver=mysolver --gpu=all 2>&1 | tee caffe_segfault.log
I0301 07:43:19.161887 12018 caffe.cpp:454] This is NVCaffe 0.16.6 started at Thu Mar  1 07:43:17 2018
I0301 07:43:19.162240 12018 caffe.cpp:456] CuDNN version: 7005
I0301 07:43:19.162250 12018 caffe.cpp:457] CuBLAS version: 9010
I0301 07:43:19.162253 12018 caffe.cpp:458] CUDA version: 9010
I0301 07:43:19.162256 12018 caffe.cpp:459] CUDA driver version: 9010
F0301 07:43:19.162297 12018 io.cpp:28] Check failed: fd != -1 (-1 vs. -1) File not found: mysolver
*** Check failure stack trace: ***
    @     0x7f21f5ea184d  google::LogMessage::Fail()
    @     0x7f21f5ea361c  google::LogMessage::SendToLog()
    @     0x7f21f5ea143c  google::LogMessage::Flush()
    @     0x7f21f5ea3f2e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f21fe6c6acd  caffe::ReadProtoFromTextFile()
    @     0x7f21fe6d853f  caffe::ReadSolverParamsFromTextFileOrDie()
    @           0x40cb41  train()
    @           0x40a448  main
    @     0x7f21dd5bbc05  __libc_start_main
    @           0x40ad74  (unknown)

**Comment by drnikolaev** [comment]
By 'mysolver' I meant the solver prototxt file you use

**Comment by 331744738** [comment]
@drnikolaev 
What do you mean by the prototype of the solver?Please make it clear.

**Comment by drnikolaev** [comment]
This article might help actually: http://caffe.berkeleyvision.org/gathered/examples/imagenet.html

**Comment by 331744738** [comment]
@drnikolaev 
Ok, I'll look at this later.

**Comment by 331744738** [comment]
@drnikolaev 

net: "netConfig/net_train.prototxt"
test_iter: 10
test_interval: 500
base_lr: 0.01
lr_policy: "step"
gamma: 0.9
stepsize: 100000
display: 100
max_iter: 1000000
momentum: 0.9
weight_decay: 0.0005
snapshot: 10000
snapshot_prefix: "models/model"
solver_mode: GPU

**Comment by 331744738** [comment]
@drnikolaev 
That's mine solver.prototxt
net: "netConfig/net_train.prototxt"
test_iter: 10
test_interval: 500
base_lr: 0.01
lr_policy: "step"
gamma: 0.9
stepsize: 100000
display: 100
max_iter: 1000000
momentum: 0.9
weight_decay: 0.0005
snapshot: 10000
snapshot_prefix: "models/model"
solver_mode: GPU

**Comment by drnikolaev** [comment]
ok, looks good. could you paste `netConfig/net_train.prototxt` file as well?

**Comment by 331744738** [comment]
@drnikolaev 
[net_train.prototxt.docx](https://github.com/NVIDIA/caffe/files/1773364/net_train.prototxt.docx)

**Comment by 331744738** [comment]
@drnikolaev 
[net_train.prototxt.docx](https://github.com/NVIDIA/caffe/files/1773369/net_train.prototxt.docx)
