### ISSUE TITLE
How can I recompile libturbojpeg_la-turbojpeg.o with -fPIC

### ISSUE THREAD

**Issue by lilacbeauty** [NVIDIA/caffe#484]
Error occured when I compiled NVCaffe 0.16.6:
LD -o .build_release/lib/libcaffe-nv.so.0.16.6
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libturbojpeg.a(libturbojpeg_la-turbojpeg.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against external symbol `__stack_chk_guard@@GLIBC_2.17' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libturbojpeg.a(libturbojpeg_la-turbojpeg.o)(.text+0x64): unresolvable R_AARCH64_ADR_PREL_PG_HI21 relocation against symbol `__stack_chk_guard@@GLIBC_2.17'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Makefile:603: recipe for target '.build_release/lib/libcaffe-nv.so.0.16.6' failed
make: *** [.build_release/lib/libcaffe-nv.so.0.16.6] Error 1

**Comment by drnikolaev** [comment]
Hi @lilacbeauty please do
```
sudo apt-get install libturbojpeg
sudo ln -s /usr/lib/x86_64-linux-gnu/libturbojpeg.so.0.1.0 /usr/lib/x86_64-linux-gnu/libturbojpeg.so
```

**Comment by lilacbeauty** [comment]
problem solved! thanks a lot!
