### ISSUE TITLE
Cache and shuffling are now disabled.

### ISSUE THREAD

**Issue by huan-fu** [NVIDIA/caffe#485]
Hi anyone, 

When I trained my deep model for some iterations, I got some warning about the data cache because of memory limitation. See the sentence below for the warning.

****************************************************************
W0321 10:26:16.957023 93510 data_reader.cpp:197] Data Reader cached 1148000 records so far but it can't continue because it used more than half of swap buffer. Free swap memory left: 36476575744 of total 73014435840. Cache and shuffling are now disabled.
*****************************************************************

Will the cache and shuffling restart after some further iterations during the training?

Thanks for your help.

caffe version: caffe-0.16.6
data type: LMDB

**Comment by huanfu1029** [comment]
The used caffe version is caffe-0.16.6.

**Comment by drnikolaev** [comment]
@huanfu1029 see my reply to #486
