### ISSUE TITLE
Task abnormally terminated

### ISSUE THREAD

**Issue by huan-fu** [NVIDIA/caffe#486]
When I trained my classification model (inception-resnet-v2), the program was abnormally killed after some iterations. 
I will share the error log here (Please ignore the data_reader output).
Could any one give me some advices?

Cuda: v9.1.85
GPU card: V100
GCC: 5.4.0
caffe version: caffe-0.17.0 and caffe-0.16.6
Data type: LMDB

![611521612312_ pic_hd](https://user-images.githubusercontent.com/17946475/37696366-24724bbe-2d2a-11e8-8ff2-d26254581a93.jpg)

**Comment by drnikolaev** [comment]
@huanfu1029 you try to use cache&shuffle but your LMDB is bigger than RAM, so Linux kills it. Please try to turn off cache or install more RAM.

**Comment by huan-fu** [comment]
@drnikolaev Thanks for your reply. 
From your answer, I get that the cache progress will load the whole LMDB data into RAM. The main reason that I use cache is that I want to do the shuffle augmentation for my training. It seems that I should use ImageDataLayer as an alternative, since its shuffle progress does not rely on the cache progress.
