### ISSUE TITLE
 error: identifier "__hdiv" is undefined

### ISSUE THREAD

**Issue by twmht** [NVIDIA/caffe#489]
OS: Ubuntu 16.04
CUDA: 8.0
cudnn: 7.0

```
cd caffe
make -j4
```

outputs

```
./include/caffe/util/gpu_math_functions.cuh(32): error: identifier "__hdiv" is undefined

1 error detected in the compilation of "/tmp/tmpxft_0000720b_00000000-13_adagrad_solver.compute_61.cpp1.ii".
Makefile:623: recipe for target '.build_release/cuda/src/caffe/solvers/adagrad_solver.o' failed
make: *** [.build_release/cuda/src/caffe/solvers/adagrad_solver.o] Error 1
make: *** Waiting for unfinished jobs....
./include/caffe/util/gpu_math_functions.cuh(32): error: identifier "__hdiv" is undefined

1 error detected in the compilation of "/tmp/tmpxft_0000722f_00000000-13_nesterov_solver.compute_61.cpp1.ii".
Makefile:623: recipe for target '.build_release/cuda/src/caffe/solvers/nesterov_solver.o' failed
make: *** [.build_release/cuda/src/caffe/solvers/nesterov_solver.o] Error 1
```

Any advise?

Thank you

**Comment by zhoujustin** [comment]
I also meet it last weekend. 
I removed the cmake/Cuda.cmake Caffe_known_gpu_archs which defined greater then 53 such as 60 61 70.
I compiler the caffe completely but when I trainning with GPU，I got some errors 8 seems like caused by GPU_ARCH. Any IDEA?

**Comment by twmht** [comment]
@zhoujustin 

How did you know you have to remove the arch to make the compilation pass?

**Comment by zhoujustin** [comment]
@twmht There was a MICRO which defined GPU_ARCH >=530 use __hdiv().  Means not use 60&61 to avoid using _hdiv().

**Comment by ghimiredhikura** [comment]
I also got the same error, any idea?

NVCC src/caffe/solvers/nesterov_solver.cu
./include/caffe/util/gpu_math_functions.cuh(32): error: identifier "__hdiv" is undefined

1 error detected in the compilation of "/tmp/tmpxft_00004e86_00000000-13_nesterov_solver.compute_61.cpp1.ii".
Makefile:623: recipe for target '.build_release/cuda/src/caffe/solvers/nesterov_solver.o' failed
make: *** [.build_release/cuda/src/caffe/solvers/nesterov_solver.o] Error 1

**Comment by drnikolaev** [comment]
Hi all, thanks for reporting. While I'm fixing this, please try CUDA 9.

**Comment by drnikolaev** [comment]
@twmht @zhoujustin @ghimiredhikura thanks again. Reproduced and fixed.

**Comment by vuonglq-vn** [comment]
I got this issue and below is my fixing for using CUDA8.0:
Modify file './include/caffe/util/gpu_math_functions.cuh' line 32 from '__hdiv' to 'hdiv'

Because in CUDA8.0, file 'cuda_fp16.h' have function 'hdiv' instead of '__hdiv' (maybe CUDA9.0)

You can check in CUDA Math API document:
- 9.0: https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH____HALF__ARITHMETIC.html
- 8.0: http://lutgw1.lunet.edu/cuda/html/cuda-math-api/group__CUDA__MATH____HALF__ARITHMETIC.html#group__CUDA__MATH____HALF__ARITHMETIC
