### ISSUE TITLE
SSD Accuracy is lower when performing consecutive forwards

### ISSUE THREAD

**Issue by ezetl** [NVIDIA/caffe#494]
Hello, I was testing the [SSD](https://github.com/NVIDIA/caffe/pull/446) feature and I noted that the accuracy for [AFW test set](https://www.ics.uci.edu/~xzhu/face/) (face detection) dropped while using NVIDIA Caffe 0.17 (commit 1044c5e6).

The original [SSD](https://github.com/weiliu89/caffe) version of Caffe gives 99.85% accuracy on AFW whereas Nvidia Caffe 0.17 gives 94.01%.

I noticed that for most of the images (there are 205 on the test set) the difference in the output blobs is negligible. However for 45 images, the output shape is different since the amount of faces detected is different (from 1 to 10 extra faces).

I noted that when reloading the network *before* each forward(), the results are the same for both Caffe implementations (Nvidia 0.17 and the original SSD).  Could there be some cache or values that are not being properly reset after each forward pass? does anyone have any idea which layer could cause this?

### I am doing the following:
I am calling [this](https://github.com/bonseyes/SFD/blob/master/sfd_test_code/test.py) script to perform the test on [AFW test set](https://www.ics.uci.edu/~xzhu/face/). The SFD_DETECTOR called there is implemented [here](https://github.com/bonseyes/SFD/blob/master/sfd_test_code/sfd_detector.py).

The same scripts achieves 99.85 using the original SSD implementation.

## Model:
[prototxt](https://github.com/bonseyes/SFD/blob/master/models/Original/deploy.prototxt)
[caffemodel](https://drive.google.com/open?id=1CboBIsjcDQ-FC1rMES6IjTl6sYQDoD6u)
(The model was originally trained using the SSD Caffe version and loaded into Nvidia Caffe 0.17)

## Dataset:
[AFW test set](https://www.ics.uci.edu/~xzhu/face/)

I can also provide how to evaluate the results and obtain the accuracies if needed, though that requires using another project.

**Comment by drnikolaev** [comment]
Hi @ezetl , thank you. Did you take the code before or after #493 ? Are you running fp32 or 16?

**Comment by ezetl** [comment]
Hi @drnikolaev, Im running fp32. I did not modify the `prototxt` (i.e. no `forward_type` and `forward_type` were added) and I think the default precision is fp32 right? I tested this yesterday with the changes of #493 already merged.

**Comment by ezetl** [comment]
I also tested the same script on the fork [caffe-jacinto](https://github.com/tidsp/caffe-jacinto) and it works Ok, these are the accuracies i got so far using AFW:

 Caffe version     |   AFW 
-------------|-------
 [SSD](https://github.com/weiliu89/caffe)         | 99.85 
 NVIDIA 0.17 | 94.01 
[JACINTO](https://github.com/tidsp/caffe-jacinto)     | 99.85 

Jacinto is a fork of this repo, so maybe we could find something by checking their code

**Comment by drnikolaev** [comment]
Hi @ezetl I ran your test.py and generated `sfd_afw_dets.txt`. Could you post a script computing the accuracy?

**Comment by ezetl** [comment]
Great! Thanks for your response. To compute the accuracies you can download this [repo](https://bitbucket.org/marcopede/face-eval), copy the `sfd_afw_dets.txt` inside the folder `detections/AFW` and run `python2.7 plot_AP.py --dataset AFW`. A matplotlib plot should appear on your screen, the values corresponding to the generated file should be under the label `sfd afw dets`.

I'll happily compute the accuracy for you if you don't have time, just let me know and share the file with me.
Thanks!

**Comment by drnikolaev** [comment]
@ezetl I got 94.01% too, fixing...

**Comment by drnikolaev** [comment]
@ezetl 
_I noted that when reloading the network before each forward(), the results are the same for both Caffe implementations _
how exactly did you do that?

**Comment by ezetl** [comment]
I just reloaded the model by putting `net = SFD_NET(device=device)` inside the main loop, for example in line 26 of `test.py`. It will reload the whole network and create the transformer again for each image.

**Comment by drnikolaev** [comment]
@ezetl still working on this but there is a workaround. Could you try this:
```
layer {
  name: "conv7_2"
  type: "Convolution"
  bottom: "conv7_1"
  top: "conv7_2"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  convolution_param {

####### 
  engine: CAFFE
#######
```
This particular layer should be processed by non-cuDNN implementation. Still checking why...

**Comment by ezetl** [comment]
Hi, In case it sill helps, I added the line `engine: CAFFE` to conv7_2 but still got the same results. I am using cudnn 7.0 with Cuda 9

**Comment by drnikolaev** [comment]
hi @ezetl it's finally fixed but I got few more. I plan to shoot a new release with all fixes. No ETA yet, sorry.

**Comment by ezetl** [comment]
You are awesome @drnikolaev !  I'll check the commits later. Thank you very much

**Comment by drnikolaev** [comment]
@ezetl  could you verify https://github.com/drnikolaev/caffe/tree/caffe-0.17 release candidate?

**Comment by drnikolaev** [comment]
@ezetl  Please verify https://github.com/NVIDIA/caffe/tree/v0.17.1 release and reopen the issue if needed.

**Comment by ezetl** [comment]
Hi @drnikolaev, I can confirm that with the same models I originally posted and with the latest release this issue is fixed. I could obtain 99.85 of accuracy on AFW. Thank you very much for the hard work!
