### ISSUE TITLE
Could NOT find JPEGTurbo (missing: JPEGTurbo_LIBRARIES)

### ISSUE THREAD

**Issue by mjjdick** [NVIDIA/caffe#500]
Hi，I met this cmake error， could anyone help me？
my environment:
ubuntu 14.04
cuda 8.0
cuDNN 6.0
gcc 4.9

the cmake error is : 
```
  Could NOT find JPEGTurbo (missing: JPEGTurbo_LIBRARIES)
  cmake/Modules/FindJPEGTurbo.cmake:18 (find_package_handle_standard_args)
  cmake/Dependencies.cmake:54 (find_package)
  CMakeLists.txt:65 (include)
```

**Comment by drnikolaev** [comment]
hi @mjjdick did you do this?
```
sudo apt-get install libturbojpeg
sudo ln -s /usr/lib/x86_64-linux-gnu/libturbojpeg.so.0.1.0 /usr/lib/x86_64-linux-gnu/libturbojpeg.so
```

**Comment by mjjdick** [comment]
```
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-turbojpeg.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
```

Hi, I followed your instruction, there is no cmake error, but when I make,another error appeared!

**Comment by mjjdick** [comment]
Hi , thx very much , I have found out the reason. 
yes, when I follow your instruction ,the problem solved!
but in the directory of /usr/lib/x86_64-linux-gnu/ , my libturbojpeg is libturbojpeg.so.0.0.0 , so after I relink ,the compile work right! thx again!

**Comment by drnikolaev** [comment]
Excellent!
