### ISSUE TITLE
Slow compile time

### ISSUE THREAD

**Issue by dashesy** [NVIDIA/caffe#502]
The compile time of NVIDIA/caffe (Cuda9 and CUDNN 7) is much slower than BVLC/caffe. In both cases I compile with "All" architectures because I do not know which one may be running on the target cluster.
Is this expected because of new architectures?

**Comment by drnikolaev** [comment]
Hi @dashesy , it takes about 1m45s to build it on my box. Yes, it is slower to build than BVLC because of fp16 support - you actually build both versions, fp32 and fp16.

**Comment by dashesy** [comment]
Is there a way to only compile for float32?

**Comment by drnikolaev** [comment]
Not at this moment, sorry
