### ISSUE TITLE
Example to use with MPI

### ISSUE THREAD

**Issue by dashesy** [NVIDIA/caffe#505]
Is there any example to use NVIDIA/caffe with MPI? Using NCCL2, it should be possible I guess but it was not stated if MPI is supported. There is also https://github.com/Caffe-MPI/Caffe-MPI.github.io but I do not see why NVIDIA/caffe itself could not be used with MPI (and OpenIB)

---
Update: checking the code, MPI support is not implemented for NVIDIA/caffe, but comparign to Caffe-MPI, adding the support is not too difficult.

**Comment by drnikolaev** [comment]
@dashesy  could you verify https://github.com/drnikolaev/caffe/tree/caffe-0.17 release candidate?
It's different implementation though (closing your PR, thank you).

**Comment by drnikolaev** [comment]
@dashesy  Please verify https://github.com/NVIDIA/caffe/tree/v0.17.1 release and reopen the issue if needed.
