### ISSUE TITLE
Steps to install caffe in 18.04 Ubuntu version

### ISSUE THREAD

**Issue by Isaamarod** [NVIDIA/caffe#507]
To install 18.04 ubuntu version, I followed steps since:

http://caffe.berkeleyvision.org/install_apt.html 

`sudo apt install caffe-cuda`

After, I can't find caffe in my system and I can't found more installation steps.

Thanks,
Isabel

**Comment by drnikolaev** [comment]
@Isaamarod you might find some help on BVLC page
