### ISSUE TITLE
[cudnn_conv_layer.cu:55] Check failed: error == cudaSuccess (77 vs. 0)  an illegal memory access was encountered

### ISSUE THREAD

**Issue by HaoLiuHust** [NVIDIA/caffe#515]
when running two models in multi-thread, this error will happened if compiled nvcaffe with cudnn7.

**Comment by HaoLiuHust** [comment]
if I run them in two seperate process, it will be ok

**Comment by drnikolaev** [comment]
Reproduced and fixed, see new release soon

**Comment by HaoLiuHust** [comment]
@drnikolaev what about the fix progress?

**Comment by HaoLiuHust** [comment]
@drnikolaev where can I find the fix?
