### ISSUE TITLE
can't reproduce testing accuracy in the log file

### ISSUE THREAD

**Issue by lixincn2015** [NVIDIA/caffe#516]
Hi, I've tested the trained caffemodel, and the accuracy is consistently ~0.5% lower than that claimed in the log file.
What could possibly be wrong?

**Comment by drnikolaev** [comment]
Hi @lixincn2015 let's start with logs, please upload them here

**Comment by 1duo** [comment]
Hi @drnikolaev, I observed same issue here. Basically during train/val (`caffe train -solver ...`), when it does validation, output includes both validation accuracy and at the meantime, a snapshot, using `SnapshotWithScores()`, with accuracy score in filename (https://github.com/aNVIDIA/caffe/blob/caffe-0.17/src/caffe/solver.cpp#L393), such as `resnet50_score1_score2_score3.caffemodel`. Later after finished training, if you use `caffe test -model ... -weights ...` to test same `resnet50_score1_score2_score3.caffemodel`. It's a bit lower accuracy then reported during train/val.

**Comment by drnikolaev** [comment]
@1duo could you post your prototxt file and log please?
