### ISSUE TITLE
Training loss is  nan as compared to bvlc caffe 

### ISSUE THREAD

**Issue by twmht** [NVIDIA/caffe#520]
Hi,

Environment: nvcaffe 0.17 + cuda9.2 + cudnn7 + Ubuntu 16.04 + Pascal 1080 Ti

I am training face identification  and found the training loss became nan it a few iterations. But everything is fine when in bvlc-caffe.

Here is the training prototxt (https://github.com/ydwen/caffe-face/blob/caffe-face/face_example/face_train_test.prototxt)

Here is the training log
[train.log](https://github.com/NVIDIA/caffe/files/2169388/train.log)

any idea?

**Comment by drnikolaev** [comment]
@twmht  could you verify https://github.com/drnikolaev/caffe/tree/caffe-0.17 release candidate?

**Comment by drnikolaev** [comment]
@twmht  Please verify https://github.com/NVIDIA/caffe/tree/v0.17.1 release and reopen the issue if needed.

**Comment by twmht** [comment]
@drnikolaev 

thank you. I have not verified yet.

But what is the cause for this issue? What changes did you made to solve this issue? (https://github.com/NVIDIA/caffe/pull/528)
