### ISSUE TITLE
0.17.0 can't compile without opencv on centos

### ISSUE THREAD

**Issue by lsp0701** [NVIDIA/caffe#521]
https://github.com/NVIDIA/caffe/blob/caffe-0.17/docs/installation.md#prerequisites

As the instruction above, nvcaffe-0.17.0 can be built without opencv.

And I compile it by setting "USE_OPENCV := 0" in Makefile.config

However, it doesn't work, Makefile search the opencv include path and library path anyway and it can't be compiled normally

`src/caffe/util/im_transforms.cpp:1:39: fatal error: opencv2/highgui/highgui.hpp: No such file or directory
 #include <opencv2/highgui/highgui.hpp>
                                       ^
compilation terminated.
make: *** [.build_release/src/caffe/util/im_transforms.o] Error 1
make: *** Waiting for unfinished jobs....`

**Comment by drnikolaev** [comment]
Hi @henry19922 OpenCV is now mandatory and USE_OPENCV is no longer used. We'll remove it in the next release

**Comment by lsp0701** [comment]
thank you @drnikolaev for the answer, which exact version is since USE_OPENCV is no longer used ?

**Comment by drnikolaev** [comment]
v0.17.0
