### ISSUE TITLE
I strongly hope you to  support cuda 8.0 verson in your newest version

### ISSUE THREAD

**Issue by gittigxuy** [NVIDIA/caffe#522]
as you know ,there are many users use ubuntu14.04 and they can not use cuda 9.0,so please support cuda 8.0.Thank you.Waiting for your soon change.

**Comment by drnikolaev** [comment]
@gittigxuy  could you verify https://github.com/drnikolaev/caffe/tree/caffe-0.17 release candidate?

**Comment by drnikolaev** [comment]
@gittigxuy  Please verify https://github.com/NVIDIA/caffe/tree/v0.17.1 release and reopen the issue if needed.
