### ISSUE TITLE
I  think there are two bugs in this version.

### ISSUE THREAD

**Issue by ghost** [NVIDIA/caffe#523]
Recenlty I train https://github.com/fwang91/residual-attention-network with this nv caffe version, but the loss  stay  around 8.0, and don't descrease.  After a few debuging.  now the loss can decrease,  so I think there are two bugs.

the first is(eltwise,sum):
  if (op_ == EltwiseParameter_EltwiseOp_SUM && no_coeffs_) {
    for (int i = 0; i < bottom.size(); ++i) {
      bottom[i]->ShareDiff(*top[0]);
    }
    top[0]->ShareData(*bottom[0]);
  }
It should not be shared, if does, network such as resnet may not work.

and second the  split layer,  
 bottom[0]->ShareDiff(*top[0]);
diff should not shared for the same reason.

**Comment by drnikolaev** [comment]
@zhuwnq this is fixed in new release, coming soon...

**Comment by drnikolaev** [comment]
@zhuwnq could you verify https://github.com/drnikolaev/caffe/tree/caffe-0.17 release candidate?

**Comment by drnikolaev** [comment]
@zhuwnq Please verify https://github.com/NVIDIA/caffe/tree/v0.17.1 release and reopen the issue if needed.
