### ISSUE TITLE
ERROR: Detected NVIDIA Tesla K80 GPU, which is not supported by this container

### ISSUE THREAD

**Issue by rotorliu** [NVIDIA/caffe#525]
Hi,
I'm trying to run Nvidia Caffe 18.07-py2 using the container from NGC on a server with Tesla K80 GPU, but without success.

This is the error I get in the console:

ERROR: Detected NVIDIA Tesla K80 GPU, which is not supported by this container
ERROR: No NVIDIA supported GPU(s) detected to run this container

Which GPUs are supported for Nvidia Caffe 18.07 ?

Thanks

**Comment by rotorliu** [comment]
GeForce GTX 970 is OK

**Comment by cliffwoolley** [comment]
@rotorliu Thanks for inquiring.  NGC containers are officially supported via the [NVIDIA Devtalk forums]( https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/); this issue board is for the NVIDIA Caffe project as you might build from source yourself, as opposed to the one we build for you on NGC.

That said, NGC DL Framework containers are presently built for Pascal and Volta GPUs per the [NGC FAQ](https://www.nvidia.com/en-us/gpu-cloud/deep-learning-containers/#faq), which says:

> What are the supported platforms for the deep learning containers?
> The GPU-accelerated deep learning containers are tuned, tested, and certified by NVIDIA to run on NVIDIA TITAN V, TITAN Xp, TITAN X (Pascal), NVIDIA Quadro GV100, GP100 and P6000, NVIDIA DGX Systems​, and on supported NVIDIA GPUs on Amazon EC2, Google Cloud Platform, and Oracle Cloud Infrastructure.

The error message you are seeing is letting you know up front that support for Kepler GPUs was not included in those builds.  If you'd like, you can build it yourself from the source code in this repository.

Hope this helps,
Cliff
