### ISSUE TITLE
Compile Error 0.17

### ISSUE THREAD

**Issue by rotorliu** [NVIDIA/caffe#527]
When compile nvcaffe 0.17, I get errors as follows:

CXX/LD -o .build_release/tools/caffe.bin
.build_release/tools/caffe.o: In function `train()':
caffe.cpp:(.text+0x4ab8): undefined reference to `caffe::P2PManager::P2PManager(boost::shared_ptr<caffe::Solver>, int, caffe::SolverParameter const&)'
.build_release/tools/caffe.o: In function `time()':
caffe.cpp:(.text+0x5d2f): undefined reference to `caffe::Timer::Timer()'
caffe.cpp:(.text+0x5d44): undefined reference to `caffe::Timer::Timer()'
caffe.cpp:(.text+0x5d59): undefined reference to `caffe::Timer::Timer()'
caffe.cpp:(.text+0x5f87): undefined reference to `caffe::Timer::Timer()'
caffe.cpp:(.text+0x5f9f): undefined reference to `caffe::Timer::Timer()'
.build_release/tools/caffe.o:caffe.cpp:(.text+0x6099): more undefined references to `caffe::Timer::Timer()' follow
collect2: error: ld returned 1 exit status
Makefile:654: recipe for target '.build_release/tools/caffe.bin' failed
make: *** [.build_release/tools/caffe.bin] Error 1

**Comment by drnikolaev** [comment]
@rotorliu thank you. Please paste the command you invoke.

**Comment by rotorliu** [comment]
cd caffe
make

**Comment by rotorliu** [comment]
The environment is ngc container.
There is a caffe in it.

**Comment by drnikolaev** [comment]
What version of the container do you run? And why do you need to build caffe? It's built already.

**Comment by rotorliu** [comment]
The version of the container is NVCaffe 18.07-py2
I want to add Focal Loss support。
So I need rebuild caffe。

**Comment by rotorliu** [comment]
I fixed this！
I remove the old lib and remake. It's OK

**Comment by drnikolaev** [comment]
Thank you for confirming
