### ISSUE TITLE
color_mode bug in Decode() function in io.cpp

### ISSUE THREAD

**Issue by soyebn** [NVIDIA/caffe#529]
Looks like color_mode is ignore in the flow when Turbo JPEG decoder is used. Observed while training coco dataset which contains gray images.
See below,
https://github.com/NVIDIA/caffe/blob/caffe-0.17/src/caffe/util/io.cpp#L152
Inserting the following lines fixes the issue.
    if(cv_img->channels()<3 && color_mode>0) {
    	cv::cvtColor(*cv_img, *cv_img, cv::COLOR_GRAY2BGR);
    }

**Comment by drnikolaev** [comment]
@soyebn Good catch, thank you. Fixed in https://github.com/drnikolaev/caffe/tree/caffe-0.17
