### ISSUE TITLE
Question about caffe

### ISSUE THREAD

**Issue by 437432655** [NVIDIA/caffe#533]
Hello, I have some questions when using caffe, and hope you can help me.
First I use v0.15.9 and make successfully. But when I import caffe.model_libs , there is an error that no module named model_libs.
I don't know why. Then I use v0.17.1, but when make all -j4 , there is another error that 
sudo make all -j4
LD -o .build_release/lib/libcaffe-nv.so.0.17.1
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-turbojpeg.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a: error adding symbols: 错误的值
collect2: error: ld returned 1 exit status
make: *** [.build_release/lib/libcaffe-nv.so.0.17.1] 错误 1
Can you help me ? Thank you very much.

**Comment by drnikolaev** [comment]
@437432655 please look at https://github.com/NVIDIA/caffe/blob/caffe-0.17/README.md
scroll to the very bottom

**Comment by 437432655** [comment]
very appreciate for your response.
I have executed these code early.
sudo apt-get install libturbojpeg
sudo ln -s /usr/lib/x86_64-linux-gnu/libturbojpeg.so.0.1.0 /usr/lib/x86_64-linux-gnu/libturbojpeg.so
