### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by louis-u** [NVIDIA/caffe#535]
I'm trying to make NVcaffe on my host . It reports logs as follow
`louis@louis-HP-280-G1-MT:~/caffe-caffe-0.15$ make all -j8
LD -o .build_release/lib/libcaffe-nv.so.0.15.14
/usr/bin/ld: /usr/local/lib/libleveldb.a(db_impl.cc.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libleveldb.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:573: recipe for target '.build_release/lib/libcaffe-nv.so.0.15.14' failed
make: *** [.build_release/lib/libcaffe-nv.so.0.15.14] Error 1
`
any help would be much appreciated

**Comment by drnikolaev** [comment]
@louis-u you need to link with libleveldb.so

**Comment by NEWPLAN** [comment]
> @louis-u you need to link with libleveldb.so

Hi, I have fix two compile errors while enabling multi-threads and linking with the latest cuda (higher than 9).
Could you please kindly give a check on my submissions and merge it into the caffe branch?

Best.
