### ISSUE TITLE
How does NVCaffe MultiGPU Solver Works?

### ISSUE THREAD

**Issue by linnanwang** [NVIDIA/caffe#54]
Hello,

I saw each GPU is assigned a solver; however, I 'm not sure how do you average the gradients from multiGPUs. Is it at each iterations, every GPU fetch the images of batch/GPUs and compute the gradient. Then the root solver retrieve the rest of gradients and average together. Then it goes to the next iteration. Is it correct? Thank you

**Comment by lukeyeager** [comment]
I'll point you to the original Multi-GPU pull request, which has a large discussion about implementation:
https://github.com/BVLC/caffe/pull/2114

Note that some changes were made before it was finally merged into BVLC (and later, then this fork):
https://github.com/BVLC/caffe/pull/2903
