### ISSUE TITLE
libcaffe-nv.so: undefined reference to `tjDestroy'

### ISSUE THREAD

**Issue by changgongcheng** [NVIDIA/caffe#544]
.build_release/lib/libcaffe-nv.so: undefined reference to `tjDestroy'
.build_release/lib/libcaffe-nv.so: undefined reference to `tjInitDecompress'
.build_release/lib/libcaffe-nv.so: undefined reference to `tjDecompressHeader2'
.build_release/lib/libcaffe-nv.so: undefined reference to `tjDecompress2'

 anyone who can help me

**Comment by drnikolaev** [comment]
@changgongcheng please check this out:
https://github.com/NVIDIA/caffe#useful-notes
