### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by ESQ900ST** [NVIDIA/caffe#549]
Im using ubuntu desktop 16.04, have installed all the required dependancies (official caffe runs ok).

The thing is I have problem running multi-gpu on the official caffe so wanted to try the nvcaffe.

But there's this error during the make compilation:

LD -o .build_release/lib/libcaffe-nv.so.0.17.2
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-turbojpeg.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a: error adding symbols: bad value
collect2: error: ld returned 1 exit status
Makefile:600: recipe for target '.build_release/lib/libcaffe-nv.so.0.17.2' failed

Could anyone possibly show me how exactly do I solve the error? Appreciated.

**Comment by drnikolaev** [comment]
Hi @ESQ900ST  please try https://github.com/NVIDIA/caffe#useful-notes
