### ISSUE TITLE
faster rcnn support error

### ISSUE THREAD

**Issue by guoqiang0148666** [NVIDIA/caffe#553]
Hello, l want to use nvidia caffe to support faster rcnn, but l meet a error as following:

F0121 16:54:30.924830 13972 blob.hpp:593] Check failed: current_type == new_type (3 vs. 1) Attempt to change TBlob native data type from INT to FLOAT
*** Check failure stack trace: ***
    @     0x7f3420fa75cd  google::LogMessage::Fail()
    @     0x7f3420fa9433  google::LogMessage::SendToLog()
    @     0x7f3420fa715b  google::LogMessage::Flush()
    @     0x7f3420fa9e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f3421f18b9d  caffe::ROIPoolingLayer<>::Forward_gpu()
    @     0x7f3422f0e382  caffe::Layer<>::Forward()
    @     0x7f3421cdd7f3  caffe::Net::ForwardFromTo()
    @     0x7f3421cdd957  caffe::Net::Forward()
    @     0x7f3421ce2345  caffe::Net::ForwardBackward()
    @     0x7f3421cf8eab  caffe::Solver::Step()
    @     0x7f3422ef141d  caffe::Solver_StepNoGIL()
    @     0x7f3422f0d304  boost::python::objects::caller_py_function_impl<>::operator()()
    @     0x7f34206d95cd  boost::python::objects::function::call()
    @     0x7f34206d97c8  (unknown)
    @     0x7f34206e1613  boost::python::handle_exception_impl()
    @     0x7f34206d6999  (unknown)
    @           0x4c166d  PyEval_EvalFrameEx
    @           0x4c141f  PyEval_EvalFrameEx
    @           0x4b9b66  PyEval_EvalCodeEx
    @           0x4c17c6  PyEval_EvalFrameEx
    @           0x4b9b66  PyEval_EvalCodeEx
    @           0x4eb69f  (unknown)
    @           0x4e58f2  PyRun_FileExFlags
    @           0x4e41a6  PyRun_SimpleFileExFlags
    @           0x4938ce  Py_Main
    @     0x7f345859a830  __libc_start_main
    @           0x493299  _start
    @              (nil)  (unknown)
Aborted (core dumped)

Any suggestions are welcome, thank you

**Comment by drnikolaev** [comment]
@guoqiang0148666 what is ROIPoolingLayer?

**Comment by guoqiang0148666** [comment]
ROIPoolingLayer comes from faster rcnn (https://github.com/rbgirshick/py-faster-rcnn)

**Comment by whria78** [comment]
1)
ROIPooling Layer was supported by Microsoft version of Caffe (2015).

```
:~/caffe/second/py-faster-rcnn/caffe-fast-rcnn$ git log
commit 0dcd397b29507b8314e252e850518c5695efbb83
Author: Ross Girshick <ross.girshick@gmail.com>
Date:   Sun Aug 9 13:41:39 2015 -0700

    Fast and Faster R-CNN change set
     - smooth l1 loss
     - roi pooling
     - expose phase in pycaffe
     - dropout scaling at test time (needed for MSRA-trained ZF network)

```

```
src/caffe/proto/caffe.proto
optional ROIPoolingParameter roi_pooling_param = 8266711;

```

2) py-faster-rcnn works well on Ubuntu 16.04 (https://github.com/rbgirshick/py-faster-rcnn).
However, if we want to use it with the lastest cuDNN on Ubuntu 18.04, please check this post (https://gist.github.com/acmiyaguchi/bc535ba23eabd3564edd73e491763d50)

**Comment by drnikolaev** [comment]
This is about BVLC Caffe, closing
