### ISSUE TITLE
error occur while compilation

### ISSUE THREAD

**Issue by WangWangPoint** [NVIDIA/caffe#560]
Hi,
    While compiling am getting the following error:
    command used : make 

     NVCC src/caffe/quantized_layer.cu
    ./3rdparty/half_float/half.hpp(1659): warning: calling a __host__ function("half_float::detail::round_half<( ::std::float_round_style)1> ") from a __host__ __device__ function("half_float::detail::functions::rint") is not allowed

     Kindly share your comments to fix it. Thanks.

**Comment by drnikolaev** [comment]
@WangWangPoint The file you refer to is not a part of NVCaffe source code:
https://github.com/NVIDIA/caffe/tree/caffe-0.17/src/caffe
