### ISSUE TITLE
Ubuntu 18.04 - Unable to compile caffe

### ISSUE THREAD

**Issue by ghost** [NVIDIA/caffe#561]
cmake Output:

-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
--   regex
--   chrono
--   date_time
--   atomic
-- Found GFlags: /usr/include
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found Glog: /usr/include
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.0.0")
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- HDF5: Using hdf5 compiler wrapper to determine CXX configuration
-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_cpp.so;/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr//x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.10.0.1") foundmponents:  HL
-- Found LMDB: /usr/include
-- Found lmdb    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/liblmdb.so)
-- Found LevelDB: /usr/include
-- Found LevelDB (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libleveldb.so)
-- Found Snappy: /usr/include
-- Found Snappy  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libsnappy.so)
-- Found JPEGTurbo: /usr/include
-- Found JPEGTurbo  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libturbojpeg.so.0)
-- CUDA detected: 10.1
-- Found CUDNN: /usr/local/cuda/lib64/libcudnn.so (found version "7.5")
-- Added CUDA NVCC flags for: sm_75
-- Found OpenCV: /usr (found version "3.2.0") found components:  core imgcodecs highgui imgproc videoio
-- Found OpenCV 3.x: /usr/share/OpenCV
-- Found OpenBLAS libraries: /usr/lib/x86_64-linux-gnu/libopenblas.so
-- Found OpenBLAS include: /usr/include/x86_64-linux-gnu
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.15", minimum required is "2")
-- Found Boost Python Library /usr/lib/x86_64-linux-gnu/libboost_python-py27.so
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.15rc1", minimum required is "2")
-- Found NumPy: /home/dsteger/.local/lib/python2.7/site-packages/numpy/core/include (found suitable version "1.14.5", minimum required is "1.7.1")
-- NumPy ver. 1.14.5 found (include: /home/dsteger/.local/lib/python2.7/site-packages/numpy/core/include)
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components:  doxygen dot
-- Found NCCL: /usr/include
-- Found NCCL (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libnccl.so)
-- Found NVML: /usr/local/cuda/include
-- Found NVML (include: /usr/local/cuda/include, library: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so)
-- Detected Doxygen OUTPUT_DIRECTORY: ./doxygen/
-- Found Git: /usr/bin/git (found version "2.17.1")
--
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   0.17.2
--   Git               :   v0.17.2-6-g22fd204a
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -std=c++11 -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -DDEBUG -fPIC -Wall -std=c++11 -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
--
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   USE_LEVELDB       :   ON
--   USE_LMDB          :   ON
--   TEST_FP16         :   OFF
--
-- Dependencies:
--   BLAS              :   Yes (Open)
--   Boost             :   Yes (ver. 1.65)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 3.0.0)
--   lmdb              :   Yes (ver. 0.9.21)
--   LevelDB           :   Yes (ver. 1.20)
--   Snappy            :   Yes (ver. ..)
--   OpenCV            :   Yes (ver. 3.2.0)
--   JPEGTurbo         :   Yes
--   CUDA              :   Yes (ver. 10.1)
--
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_75
--   cuDNN             :   Yes (ver. 7.5)
--   NCCL              :   Yes (ver. 2.4.2)
--   USE_MPI           :   OFF
--   NVML              :   /usr/lib/x86_64-linux-gnu/libnvidia-ml.so
--
-- Python:
--   Interpreter       :   /usr/bin/python2 (ver. 2.7.15)
--   Libraries         :   /usr/lib/x86_64-linux-gnu/libpython2.7.so (ver 2.7.15rc1)
--   NumPy             :   /home/dsteger/.local/lib/python2.7/site-packages/numpy/core/include (ver 1.14.5)
--
-- Documentaion:
--   Doxygen           :   /usr/bin/doxygen (1.8.13)
--   config_file       :   /scratch/caffe/.Doxyfile
--
-- Install:
--   Install path      :   /scratch/caffe/build/install
--
-- Configuring done
-- Generating done
-- Build files have been written to: /scratch/caffe/build

**Error:**

make[2]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_cudnn_conv_layer.cu.o] Error 1
/scratch/caffe/include/caffe/layer.hpp: In member function ‘virtual float caffe::Layer<Ftype, Btype>::Forward(const std::vector<caffe::Blob*>&, const std::vector<fe::Blob*>&)’:
/scratch/caffe/include/caffe/layer.hpp:565:16: error: ‘loss’ cannot be used as a function
         if (this->loss(top_id) == 0.F) { continue; }
                ^
/scratch/caffe/include/caffe/layer.hpp:575:16: error: ‘loss’ cannot be used as a function
         if (this->loss(top_id) == 0.F) { continue; }
                ^
CMake Error at cuda_compile_1_generated_detectnet_transform_layer.cu.o.Release.cmake:275 (message):
  Error generating file
  /scratch/caffe/build/src/caffe/CMakeFiles/cuda_compile_1.dir/layers/./cuda_compile_1_generated_detectnet_transform_layer.cu.o

src/caffe/CMakeFiles/caffe.dir/build.make:245: recipe for target 'src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_detectnet_transform_layeu.o' failed
make[2]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_detectnet_transform_layer.cu.o] Error 1
/scratch/caffe/include/caffe/layer.hpp: In member function ‘virtual float caffe::Layer<Ftype, Btype>::Forward(const std::vector<caffe::Blob*>&, const std::vector<fe::Blob*>&)’:
/scratch/caffe/include/caffe/layer.hpp:565:16: error: ‘loss’ cannot be used as a function
         if (this->loss(top_id) == 0.F) { continue; }
                ^
/scratch/caffe/include/caffe/layer.hpp:575:16: error: ‘loss’ cannot be used as a function
         if (this->loss(top_id) == 0.F) { continue; }

**Comment by ghost** [comment]
Building with clang:

/usr/include/boost/thread/detail/nullary_function.hpp(99): error: class "boost::detail::thread_move_t<boost::detail::nullary_function<void ()>>" has no member "impl"

/usr/include/boost/thread/detail/nullary_function.hpp(118): error: class "boost::detail::thread_move_t<boost::detail::nullary_function<void ()>>" has no member "impl"

/usr/include/boost/thread/detail/nullary_function.hpp(198): error: class "boost::detail::thread_move_t<boost::detail::nullary_function<size_t ()>>" has no member "impl"
          detected during instantiation of "boost::detail::nullary_function<R ()>::nullary_function(boost::detail::thread_move_t<boost::detail::nullary_function<R ()>>) [with R=size_t]"
/usr/include/boost/thread/barrier.hpp(203): here

3 errors detected in the compilation of "/tmp/tmpxft_000051ca_00000000-6_math_functions2.cpp1.ii".
CMake Error at cuda_compile_1_generated_math_functions2.cu.o.Release.cmake:275 (message):
  Error generating file
  /scratch/caffe/build/src/caffe/CMakeFiles/cuda_compile_1.dir/util/./cuda_compile_1_generated_math_functions2.cu.o


src/caffe/CMakeFiles/caffe.dir/build.make:595: recipe for target 'src/caffe/CMakeFiles/cuda_compile_1.dir/util/cuda_compile_1_generated_math_functions2.cu.o' failed
make[2]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/util/cuda_compile_1_generated_math_functions2.cu.o] Error 1
CMakeFiles/Makefile2:235: recipe for target 'src/caffe/CMakeFiles/caffe.dir/all' failed
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ghost** [comment]
Update:

I upgraded cmake to 3.13.4 and used the caffe-0.15 branch. I was able to build caffe. 

I would like to get the 0.17 caffe building. Help needed. =)

Thank You,
Daniel

**Comment by drnikolaev** [comment]
Hi @dstegs Please check v0.17.3
