### ISSUE TITLE
Error when building with make all

### ISSUE THREAD

**Issue by ilyasmg** [NVIDIA/caffe#562]
I'm installing caffe following this tutorial: https://github.com/PeteHeine/fcn8_ros
When I run make all I have the following error:
LD -o .build_release/lib/libcaffe-nv.so.0.17.2
/usr/bin/ld: cannot find -lopenblas
collect2: error: ld returned 1 exit status
Makefile:603: recipe for target '.build_release/lib/libcaffe-nv.so.0.17.2' failed
make: *** [.build_release/lib/libcaffe-nv.so.0.17.2] Error 1

I looked online for this missing "-lopenblas" but I didn't find anything
I'm using Ubuntu 16, CUDA 9, CUDNN 7

**Comment by qq199716598** [comment]
use atlas
