### ISSUE TITLE
Unable to Compile Caffe - GPU Nvidia Tesla v100 32GB

### ISSUE THREAD

**Issue by l0s3rr** [NVIDIA/caffe#563]
Good Morning, are you okay?

I'm trying to compile Caffe, when I ran the cmake command .. in Caffe's build directory, it even introduced me that it could not detect the GPU.

After that, I ran the make -j "$ (nproc)" command and got the following error:

nvcc fatal: Unsupported gpu architecture 'compute_20'

Could someone give me a hand?

I researched, but I did not find much related to my version of Cuda.

I'm using Cuda 10.1

**Comment by Lukanite** [comment]
I also ran into a similar issue on my RTX 2070.
I found that replacing CUDA_ARCH in Makefile.config allowed me to build it, but then it failed at runtime with "Check failed: error == cudaSuccess (48 vs. 0)  no kernel image is available for execution on the device"

Here's the modification I made to Makefile.config:
```
CUDA_ARCH := -gencode arch=compute_50,code=sm_50 \
                -gencode arch=compute_52,code=sm_52 \
                -gencode arch=compute_60,code=sm_60 \
                -gencode arch=compute_61,code=sm_61 \
                -gencode arch=compute_70,code=sm_70 \
                -gencode arch=compute_75,code=sm_75 \
                -gencode arch=compute_75,code=compute_75
```

**Comment by drnikolaev** [comment]
Please check v0.17.3
