### ISSUE TITLE
No overlapping of convolution groups

### ISSUE THREAD

**Issue by flx42** [NVIDIA/caffe#57]
In BVLC/caffe, multiple cudnn handles are created for each convolution group and each handle is tied to a different CUDA stream:
https://github.com/BVLC/caffe/blob/master/src/caffe/layers/cudnn_conv_layer.cpp#L51-L56

When calling the forward pass, the convolution groups are launched in parallel by using different cudnn handles and thus different streams:
https://github.com/BVLC/caffe/blob/master/src/caffe/layers/cudnn_conv_layer.cu#L18-L21

In NVIDIA/caffe, branch caffe-0.14, it looks like this is no longer working, and thus this is negatively impacting performance. We are always using the same cudnn handle, so I don't see how we could have parallel kernel launches:
https://github.com/NVIDIA/caffe/blob/caffe-0.14/src/caffe/layers/cudnn_conv_layer.cu#L44

This also means that the following code is no-op and bad for performance:
https://github.com/NVIDIA/caffe/blob/caffe-0.14/src/caffe/layers/cudnn_conv_layer.cu#L72-L75
Also, the comment is obviously false.

**Comment by jdemouth** [comment]
You can have concurrent launches from cuDNN with a single cuDNN handle. You just need to set the stream properly. 

Foreach g in groups:
  cudnnSetStream(handle, stream[g]) 
  cudnnConv(handle, ...)

**Comment by flx42** [comment]
I didn't know you could replace the stream dynamically. It should be easier to fix this issue then, if you want to.

**Comment by drnikolaev** [comment]
fixed in 0.16
