### ISSUE TITLE
Comiling simple c++ program

### ISSUE THREAD

**Issue by MaximumProgrammer** [NVIDIA/caffe#571]
I am trying to compiling the simple mnist aka classification file but it don't know how to handle this kind of error

/home/mgruber/Filestorage/software_development/project_ssp/ssp_blob_classification_caffe/main.cpp:48:14: error: ‘caffe::Net’ is not a template
   shared_ptr<Net<float> > net_;
              ^~~
/home/mgruber/Filestorage/software_development/project_ssp/ssp_blob_classification_caffe/main.cpp: In constructor ‘Classifier::Classifier(const string&, const string&, const string&, const string&)’:
/home/mgruber/Filestorage/software_development/project_ssp/ssp_blob_classification_caffe/main.cpp:66:18: error: ‘caffe::Net’ is not a template
   net_.reset(new Net<float>(model_file, TEST));
                  ^~~
/home/mgruber/Filestorage/software_development/project_ssp/ssp_blob_classification_caffe/main.cpp:72:3: error: ‘caffe::Blob’ is not a template
   Blob<float>* input_layer = net_->input_blobs()[0];
   ^~~~
/home/mgruber/Filestorage/software_development/project_ssp/ssp_blob_classification_caffe/main.cpp:88:3: error: ‘caffe::Blob’ is not a template
   Blob<float>* output_layer = net_->output_blobs()[0];
   ^~~~
/home/mgruber/Filestorage/software_development/project_ssp/ssp_blob_classification_caffe/main.cpp: In member function ‘void Classifier::SetMean(const string&)’:
/home/mgruber/Filestorage/software_development/project_ssp/ssp_blob_classification_caffe/main.cpp:132:3: error: ‘caffe::Blob’ is not a template
   Blob<float> mean_blob;
   ^~~~
/home/mgruber/Filestorage/software_development/project_ssp/ssp_blob_classification_caffe/main.cpp:132:15: error: no matching function for call to ‘caffe::Blob::Blob()’
   Blob<float> mean_blob;
               ^~~~~~~~~
In file included from /home/mgruber/git/nvcaffe/include/caffe/caffe.hpp:7:0,
                 from /home/mgruber/Filestorage/software_development/project_ssp/ssp_blob_classification_caffe/main.cpp:1:
/home/mgruber/git/nvcaffe/include/caffe/blob.hpp:54:12: note: candidate: caffe::Blob::Blob(caffe::Type)
   explicit Blob(Type dtype)
            ^~~~
/home/mgruber/git/nvcaffe/include/caffe/blob.hpp:54:12: note:   candidate expects 1 argument, 0 provided
/home/mgruber/git/nvcaffe/include/caffe/blob.hpp:48:3: note: candidate: caffe::Blob::Blob(caffe::Type, caffe::Type)
   Blob(Type data_type, Type diff_type)
   ^~~~
/home/mgruber/git/nvcaffe/include/caffe/blob.hpp:48:3: note:   candidate expects 2 arguments, 0 provided
/home/mgruber/Filestorage/software_development/project_ssp/ssp_blob_classification_caffe/main.cpp:139:44: error: no matching function for call to ‘caffe::Blob::mutable_cpu_data()’
   float* data = mean_blob.mutable_cpu_data();
                                            ^
In file included from /home/mgruber/git/nvcaffe/include/caffe/caffe.hpp:7:0,
                 from /home/mgruber/Filestorage/software_development/project_ssp/ssp_blob_classification_caffe/main.cpp:1:
/home/mgruber/git/nvcaffe/include/caffe/blob.hpp:338:10: note: candidate: template<class Dtype> Dtype* caffe::Blob::mutable_cpu_data()
   Dtype* mutable_cpu_data() {  // Keeping PyCaffe intact
          ^~~~~~~~~~~~~~~~
/home/mgruber/git/nvcaffe/include/caffe/blob.hpp:338:10: note:   template argument deduction/substitution failed:
/home/mgruber/Filestorage/software_development/project_ssp/ssp_blob_classification_caffe/main.cpp:139:44: note:   couldn't deduce template parameter ‘Dtype’
   float* data = mean_blob.mutable_cpu_data();
                                            ^
/home/mgruber/Filestorage/software_development/project_ssp/ssp_blob_classification_caffe/main.cpp: In member function ‘std::vector<float> Classifier::Predict(const cv::Mat&)’:
/home/mgruber/Filestorage/software_development/project_ssp/ssp_blob_classification_caffe/main.cpp:158:3: error: ‘caffe::Blob’ is not a template
   Blob<float>* input_layer = net_->input_blobs()[0];
   ^~~~
/home/mgruber/Filestorage/software_development/project_ssp/ssp_blob_classification_caffe/main.cpp:172:3: error: ‘caffe::Blob’ is not a template
   Blob<float>* output_layer = net_->output_blobs()[0];
   ^~~~
/home/mgruber/Filestorage/software_development/project_ssp/ssp_blob_classification_caffe/main.cpp:173:47: error: no matching function for call to ‘caffe::Blob::cpu_data()’
   const float* begin = output_layer->cpu_data();
                                               ^
In file included from /home/mgruber/git/nvcaffe/include/caffe/caffe.hpp:7:0,
                 from /home/mgruber/Filestorage/software_development/project_ssp/ssp_blob_classification_caffe/main.cpp:1:
/home/mgruber/git/nvcaffe/include/caffe/blob.hpp:320:16: note: candidate: template<class Dtype> const Dtype* caffe::Blob::cpu_data() const
   const Dtype* cpu_data() const {
                ^~~~~~~~
/home/mgruber/git/nvcaffe/include/caffe/blob.hpp:320:16: note:   template argument deduction/substitution failed:
/home/mgruber/Filestorage/software_development/project_ssp/ssp_blob_classification_caffe/main.cpp:173:47: note:   couldn't deduce template parameter ‘Dtype’
   const float* begin = output_layer->cpu_data();
                                               ^
/home/mgruber/Filestorage/software_development/project_ssp/ssp_blob_classification_caffe/main.cpp: In member function ‘void Classifier::WrapInputLayer(std::vector<cv::Mat>*)’:
/home/mgruber/Filestorage/software_development/project_ssp/ssp_blob_classification_caffe/main.cpp:184:3: error: ‘caffe::Blob’ is not a template
   Blob<float>* input_layer = net_->input_blobs()[0];
   ^~~~
/home/mgruber/Filestorage/software_development/project_ssp/ssp_blob_classification_caffe/main.cpp:188:53: error: no matching function for call to ‘caffe::Blob::mutable_cpu_data()’
   float* input_data = input_layer->mutable_cpu_data();
                                                     ^
In file included from /home/mgruber/git/nvcaffe/include/caffe/caffe.hpp:7:0,
                 from /home/mgruber/Filestorage/software_development/project_ssp/ssp_blob_classification_caffe/main.cpp:1:
/home/mgruber/git/nvcaffe/include/caffe/blob.hpp:338:10: note: candidate: template<class Dtype> Dtype* caffe::Blob::mutable_cpu_data()
   Dtype* mutable_cpu_data() {  // Keeping PyCaffe intact
          ^~~~~~~~~~~~~~~~
/home/mgruber/git/nvcaffe/include/caffe/blob.hpp:338:10: note:   template argument deduction/substitution failed:
/home/mgruber/Filestorage/software_development/project_ssp/ssp_blob_classification_caffe/main.cpp:188:53: note:   couldn't deduce template parameter ‘Dtype’
   float* input_data = input_layer->mutable_cpu_data();
                                                     ^
In file included from /home/mgruber/git/nvcaffe/include/caffe/common.hpp:5:0,
                 from /home/mgruber/git/nvcaffe/include/caffe/blob.hpp:11,
                 from /home/mgruber/git/nvcaffe/include/caffe/caffe.hpp:7,
                 from /home/mgruber/Filestorage/software_development/project_ssp/ssp_blob_classification_caffe/main.cpp:1:
/home/mgruber/Filestorage/software_development/project_ssp/ssp_blob_classification_caffe/main.cpp: In member function ‘void Classifier::Preprocess(const cv::Mat&, std::vector<cv::Mat>*)’:
/home/mgruber/Filestorage/software_development/project_ssp/ssp_blob_classification_caffe/main.cpp:232:45: error: no matching function for call to ‘caffe::Blob::cpu_data()’
         == net_->input_blobs()[0]->cpu_data())
                                             ^
In file included from /home/mgruber/git/nvcaffe/include/caffe/caffe.hpp:7:0,
                 from /home/mgruber/Filestorage/software_development/project_ssp/ssp_blob_classification_caffe/main.cpp:1:
/home/mgruber/git/nvcaffe/include/caffe/blob.hpp:320:16: note: candidate: template<class Dtype> const Dtype* caffe::Blob::cpu_data() const
   const Dtype* cpu_data() const {
                ^~~~~~~~
/home/mgruber/git/nvcaffe/include/caffe/blob.hpp:320:16: note:   template argument deduction/substitution failed:
In file included from /home/mgruber/git/nvcaffe/include/caffe/common.hpp:5:0,
                 from /home/mgruber/git/nvcaffe/include/caffe/blob.hpp:11,
                 from /home/mgruber/git/nvcaffe/include/caffe/caffe.hpp:7,
                 from /home/mgruber/Filestorage/software_development/project_ssp/ssp_blob_classification_caffe/main.cpp:1:
/home/mgruber/Filestorage/software_development/project_ssp/ssp_blob_classification_caffe/main.cpp:232:45: note:   couldn't deduce template parameter ‘Dtype’
         == net_->input_blobs()[0]->cpu_data())

**Comment by MaximumProgrammer** [comment]
My CmakeFile looks like this 

cmake_minimum_required(VERSION 3.0.0)
set(CMAKE_VERBOSE_MAKEFILE ON)

project(ssp_blob_classification_caffe VERSION 0.1.0)

include(CTest)
enable_testing()

file(GLOB SOURCES
    *.h
    *.cpp
)

add_executable(ssp_blob_classification_caffe main.cpp)

find_package(Boost 1.65 REQUIRED COMPONENTS system filesystem regex)
include_directories(${Boost_INCLUDE_DIRS})

find_package(OpenCV REQUIRED )
include_directories(${OpenCV_INCLUDE_DIRS} )

find_package(Caffe REQUIRED)
include_directories(${Caffe_INCLUDE_DIRS})

set(Caffe_DEFINITIONS " -DUSE_OPENCV -DUSE_LMDB -DUSE_LEVELDB ")
set( CMAKE_CXX_FLAGS ${Caffe_DEFINITIONS})

find_package(OpenBLAS REQUIRED)
include_directories(${OpenBLAS_INCLUDE_DIRS})

set(CPACK_PROJECT_NAME ${PROJECT_NAME})
set(CPACK_PROJECT_VERSION ${PROJECT_VERSION})
include(CPack)

#   Caffe_INCLUDE_DIRS - Caffe include directories
#   Caffe_LIBRARIES    - libraries to link against
#   Caffe_DEFINITIONS  - a list of definitions to pass to compiler

target_link_libraries(ssp_blob_classification_caffe ${OpenCV_LIBS} ${Boost_LIBRARIES} ${Caffe_LIBRARIES} ${OpenBLAS_LIB})

and my main.cpp file looks like this 

#include <caffe/caffe.hpp>

#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>

#include <algorithm>
#include <iosfwd>
#include <memory>
#include <string>
#include <utility>
#include <vector>

using namespace caffe;  // NOLINT(build/namespaces)
using std::string;
//using caffe::Net;
//using caffe::Blob;
//using caffe::Caffe;
//using caffe::Datum;
//using caffe::Net;
//using caffe::shared_ptr;
//using caffe::vector;
//using caffe::MemoryDataLayer;

/* Pair (label, confidence) representing a prediction. */
typedef std::pair<string, float> Prediction;

class Classifier {
 public:
  Classifier(const string& model_file,
             const string& trained_file,
             const string& mean_file,
             const string& label_file);

  std::vector<Prediction> Classify(const cv::Mat& img, int N = 5);

 private:
  void SetMean(const string& mean_file);

  std::vector<float> Predict(const cv::Mat& img);

  void WrapInputLayer(std::vector<cv::Mat>* input_channels);

  void Preprocess(const cv::Mat& img,
                  std::vector<cv::Mat>* input_channels);

 private:
  shared_ptr<Net<float> > net_;
  cv::Size input_geometry_;
  int num_channels_;
  cv::Mat mean_;
  std::vector<string> labels_;
};

Classifier::Classifier(const string& model_file,
                       const string& trained_file,
                       const string& mean_file,
                       const string& label_file) {
#ifdef CPU_ONLY
  Caffe::set_mode(Caffe::CPU);
#else
  Caffe::set_mode(Caffe::GPU);
#endif

  /* Load the network. */
  net_.reset(new Net<float>(model_file, TEST));
  net_->CopyTrainedLayersFrom(trained_file);

  CHECK_EQ(net_->num_inputs(), 1) << "Network should have exactly one input.";
  CHECK_EQ(net_->num_outputs(), 1) << "Network should have exactly one output.";

  Blob<float>* input_layer = net_->input_blobs()[0];
  num_channels_ = input_layer->channels();
  CHECK(num_channels_ == 3 || num_channels_ == 1)
    << "Input layer should have 1 or 3 channels.";
  input_geometry_ = cv::Size(input_layer->width(), input_layer->height());

  /* Load the binaryproto mean file. */
  SetMean(mean_file);

  /* Load labels. */
  std::ifstream labels(label_file.c_str());
  CHECK(labels) << "Unable to open labels file " << label_file;
  string line;
  while (std::getline(labels, line))
    labels_.push_back(string(line));

  Blob<float>* output_layer = net_->output_blobs()[0];
  CHECK_EQ(labels_.size(), output_layer->channels())
    << "Number of labels is different from the output layer dimension.";
}

static bool PairCompare(const std::pair<float, int>& lhs,
                        const std::pair<float, int>& rhs) {
  return lhs.first > rhs.first;
}

/* Return the indices of the top N values of vector v. */
static std::vector<int> Argmax(const std::vector<float>& v, int N) {
  std::vector<std::pair<float, int> > pairs;
  for (size_t i = 0; i < v.size(); ++i)
    pairs.push_back(std::make_pair(v[i], i));
  std::partial_sort(pairs.begin(), pairs.begin() + N, pairs.end(), PairCompare);

  std::vector<int> result;
  for (int i = 0; i < N; ++i)
    result.push_back(pairs[i].second);
  return result;
}

/* Return the top N predictions. */
std::vector<Prediction> Classifier::Classify(const cv::Mat& img, int N) {
  std::vector<float> output = Predict(img);

  N = std::min<int>(labels_.size(), N);
  std::vector<int> maxN = Argmax(output, N);
  std::vector<Prediction> predictions;
  for (int i = 0; i < N; ++i) {
    int idx = maxN[i];
    predictions.push_back(std::make_pair(labels_[idx], output[idx]));
  }

  return predictions;
}

/* Load the mean file in binaryproto format. */
void Classifier::SetMean(const string& mean_file) {
  BlobProto blob_proto;
  ReadProtoFromBinaryFileOrDie(mean_file.c_str(), &blob_proto);

  /* Convert from BlobProto to Blob<float> */
  Blob<float> mean_blob;
  mean_blob.FromProto(blob_proto);
  CHECK_EQ(mean_blob.channels(), num_channels_)
    << "Number of channels of mean file doesn't match input layer.";

  /* The format of the mean file is planar 32-bit float BGR or grayscale. */
  std::vector<cv::Mat> channels;
  float* data = mean_blob.mutable_cpu_data();
  for (int i = 0; i < num_channels_; ++i) {
    /* Extract an individual channel. */
    cv::Mat channel(mean_blob.height(), mean_blob.width(), CV_32FC1, data);
    channels.push_back(channel);
    data += mean_blob.height() * mean_blob.width();
  }

  /* Merge the separate channels into a single image. */
  cv::Mat mean;
  cv::merge(channels, mean);

  /* Compute the global mean pixel value and create a mean image
   * filled with this value. */
  cv::Scalar channel_mean = cv::mean(mean);
  mean_ = cv::Mat(input_geometry_, mean.type(), channel_mean);
}

std::vector<float> Classifier::Predict(const cv::Mat& img) {
  Blob<float>* input_layer = net_->input_blobs()[0];
  input_layer->Reshape(1, num_channels_,
                       input_geometry_.height, input_geometry_.width);
  /* Forward dimension change to all layers. */
  net_->Reshape();

  std::vector<cv::Mat> input_channels;
  WrapInputLayer(&input_channels);

  Preprocess(img, &input_channels);

  net_->Forward();

  /* Copy the output layer to a std::vector */
  Blob<float>* output_layer = net_->output_blobs()[0];
  const float* begin = output_layer->cpu_data();
  const float* end = begin + output_layer->channels();
  return std::vector<float>(begin, end);
}

/* Wrap the input layer of the network in separate cv::Mat objects
 * (one per channel). This way we save one memcpy operation and we
 * don't need to rely on cudaMemcpy2D. The last preprocessing
 * operation will write the separate channels directly to the input
 * layer. */
void Classifier::WrapInputLayer(std::vector<cv::Mat>* input_channels) {
  Blob<float>* input_layer = net_->input_blobs()[0];

  int width = input_layer->width();
  int height = input_layer->height();
  float* input_data = input_layer->mutable_cpu_data();
  for (int i = 0; i < input_layer->channels(); ++i) {
    cv::Mat channel(height, width, CV_32FC1, input_data);
    input_channels->push_back(channel);
    input_data += width * height;
  }
}

void Classifier::Preprocess(const cv::Mat& img,
                            std::vector<cv::Mat>* input_channels) {
  /* Convert the input image to the input image format of the network. */
  cv::Mat sample;
  if (img.channels() == 3 && num_channels_ == 1)
    cv::cvtColor(img, sample, cv::COLOR_BGR2GRAY);
  else if (img.channels() == 4 && num_channels_ == 1)
    cv::cvtColor(img, sample, cv::COLOR_BGRA2GRAY);
  else if (img.channels() == 4 && num_channels_ == 3)
    cv::cvtColor(img, sample, cv::COLOR_BGRA2BGR);
  else if (img.channels() == 1 && num_channels_ == 3)
    cv::cvtColor(img, sample, cv::COLOR_GRAY2BGR);
  else
    sample = img;

  cv::Mat sample_resized;
  if (sample.size() != input_geometry_)
    cv::resize(sample, sample_resized, input_geometry_);
  else
    sample_resized = sample;

  cv::Mat sample_float;
  if (num_channels_ == 3)
    sample_resized.convertTo(sample_float, CV_32FC3);
  else
    sample_resized.convertTo(sample_float, CV_32FC1);

  cv::Mat sample_normalized;
  cv::subtract(sample_float, mean_, sample_normalized);

  /* This operation will write the separate BGR planes directly to the
   * input layer of the network because it is wrapped by the cv::Mat
   * objects in input_channels. */
  cv::split(sample_normalized, *input_channels);

  CHECK(reinterpret_cast<float*>(input_channels->at(0).data)
        == net_->input_blobs()[0]->cpu_data())
    << "Input channels are not wrapping the input layer of the network.";
}

int main(int argc, char** argv) {
  if (argc != 6) {
    std::cerr << "Usage: " << argv[0]
              << " deploy.prototxt network.caffemodel"
              << " mean.binaryproto labels.txt img.jpg" << std::endl;
    return 1;
  }

  ::google::InitGoogleLogging(argv[0]);

  string model_file   = argv[1];
  string trained_file = argv[2];
  string mean_file    = argv[3];
  string label_file   = argv[4];
  Classifier classifier(model_file, trained_file, mean_file, label_file);

  string file = argv[5];

  std::cout << "---------- Prediction for "
            << file << " ----------" << std::endl;

  cv::Mat img = cv::imread(file, -1);
  CHECK(!img.empty()) << "Unable to decode image " << file;
  std::vector<Prediction> predictions = classifier.Classify(img);

  /* Print the top N predictions. */
  for (size_t i = 0; i < predictions.size(); ++i) {
    Prediction p = predictions[i];
    std::cout << std::fixed << std::setprecision(4) << p.second << " - \""
              << p.first << "\"" << std::endl;
  }
}
// USE_OPENCV

**Comment by drnikolaev** [comment]
@ZeroCool11000 yes, in nvCaffe Blob is not template:
https://github.com/NVIDIA/caffe/blob/caffe-0.17/include/caffe/blob.hpp#L35
but in BVLC it is
https://github.com/BVLC/caffe/blob/master/include/caffe/blob.hpp#L23-L24

Your code is written for BVLC Caffe
