### ISSUE TITLE
Benchmarking mode does not initialize CNMEM

### ISSUE THREAD

**Issue by flx42** [NVIDIA/caffe#58]
If you use branch caffe-0.14 and enable cuDNN, CNMEM will be enabled automatically. If you want to train a model using "caffe.bin train" then CNMEM will be initialized and allocation calls should virtually have zero cost. CNMEM is initialized here:
https://github.com/NVIDIA/caffe/blob/caffe-0.14/tools/caffe.cpp#L200

Unfortunately, if you want to benchmark this version of caffe using "caffe.bin time", CNMEM will not be initialized, it should be done here:
https://github.com/NVIDIA/caffe/blob/caffe-0.14/tools/caffe.cpp#L316-L317
Since the memory pool is not initialized, any allocation call will fallback to cudaMalloc:
https://github.com/NVIDIA/caffe/blob/caffe-0.14/src/caffe/util/gpu_memory.cpp#L65-L66

The problem is that the new convolution calls attempts to do many allocations/deallocations:
https://github.com/NVIDIA/caffe/blob/caffe-0.14/src/caffe/layers/cudnn_conv_layer.cu#L34
If we hit the cudaMalloc fallback, we do 1 cudaMalloc and 1 cudaFree **for each group and each convolution layer, for each forward pass.**

The original caffe code will be faster using "caffe.bin time" because it allocates the workspace only once:
https://github.com/BVLC/caffe/blob/master/src/caffe/layers/cudnn_conv_layer.cpp#L200

**Comment by thatguymike** [comment]
Thanks Felix.  Actually, this bug is a little more complex than this.  The initial allocation should ONLY occur in GPU mode.  I think that explains another bug we have had for awhile.  Darn rebase/cross merge...

**Comment by borisfom** [comment]
The arena class is smart agout gpu mode : if you pass an empty array of gpus to the contructor (case or runtime cpu-only switch)  it won't try to allocate any GPU memory.  
So it's perfectly safe to just have one arena instance in main() per program (remember we have 3 main's though  : caffe.cpp, caffe_fp16.cpp, caffe_test_main.cpp.

**Comment by thatguymike** [comment]
Yes, for the fp16 branch.  Need to clean this one up for release and then make sure we do the same fixes in parallel on the fp16 sub-branch.  Looks you had already fixed this one there.

**Comment by flx42** [comment]
Ok, so we clearly have too many branches, and bug fixes like that should be cherry-picked into the master branch ASAP. This is easy if one commit is a single feature. Otherwise we duplicate debugging efforts.

**Comment by thatguymike** [comment]
Should be addressed now in caffe-0.14
