### ISSUE TITLE
ERROR：Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by huanglidongTX2** [NVIDIA/caffe#584]
when i import caffe, error comes:
nvidia@jetson-1422719019466:~/caffe/build$ python
Python 2.7.12 (default, Oct  8 2019, 14:14:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import caffe
Segmentation fault (core dumped)

my device is jetson TX2， ubuntu16.04, jetpack3.2,
I have triid 5 times ,all failed,please help me,thank you very much

**Comment by drnikolaev** [comment]
v0.17.4
