### ISSUE TITLE
What is this queue for?

### ISSUE THREAD

**Issue by linnanwang** [NVIDIA/caffe#60]
Hello,

Can anyone kindly explain what is this queue_ for? I'm implementing a new solver for this multiGPU caffe. Please help, thank you.
BlockingQueue<\P2PSync<Dtype>*> queue_;

**Comment by thatguymike** [comment]
Communication of the gradient updates.

**Comment by linnanwang** [comment]
Can you please kindly elaborate it a little bit? What's the purpose of this queue?

**Comment by thatguymike** [comment]
Each thread needs to know when the RDMAs and partial gradient updates have completed up the reduction tree and when the updated model can be communicated back down as to not overwrite an active model.  Basically it is a communication syncronization mechanism.
