### ISSUE TITLE
CUDA driver error bug with SLI only remedied by running CUDA Samples deviceQuery?

### ISSUE THREAD

**Issue by alfredox10** [NVIDIA/caffe#61]
I am consistently getting this error when trying to run a caffe detection from a cold boot:

```
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1101 13:01:53.909546  4274 common.cpp:156] Check failed: error == cudaSuccess (30 vs. 0)  unknown error
*** Check failure stack trace: ***
Aborted (core dumped)
```

Previously I spend almost 3 days debugging this issue and thought it was something with my drivers, however everything is configured correctly, and even caffe runtest passes all tests. My configuration is
Caffe 0.13
CUDA 7.5
Video Card Driver: 355.11
Ubuntu 14.04
CuDNN v3

This issue however gets resolved by simply running the CUDA samples device query once and having it pass all tests. I simply navigate to:
NVIDIA_CUDA-7.5_Samples/1_Utilities/deviceQuery/
and run
sudo ./deviceQuery

Another thing to note is the caffe device_query and make runtest don't work if I don't run the CUDA samples devieQuery at least once. This is weird, and I keep having to rerun it everytime I run my code, does anyone have any idea why or is this a bug?

**Comment by smichalowski** [comment]
please read this:

https://devtalk.nvidia.com/default/topic/749939/cuda-is-not-active-unless-i-run-it-with-sudo-privillages-/

**Comment by flx42** [comment]
Instead of running deviceQuery as root, try to run this command as a normal user:
```sh
$ nvidia-modprobe -u -c=0
```

**Comment by alfredox10** [comment]
Thanks, I got this error:
nvidia-modprobe: command not found

Also smichalowski, I was not able to see what the specific solution was in that article. I read it, and I already performed all the actions listed on there, so I am not sure what was the specific part relevant to my problem, all i know is it didn't fix it.

**Comment by smichalowski** [comment]
try installing nvidia-modprobe as proposed by @flx42.

use synaptic. http://packages.ubuntu.com/search?keywords=nvidia-modprobe

**Comment by alfredox10** [comment]
I went ahead and installed that, and it looks it may have fixed it. Thanks!
