### ISSUE TITLE
MultiGPU Bug?

### ISSUE THREAD

**Issue by linnanwang** [NVIDIA/caffe#63]
Hello,

It comes to my attention that multiGPU caffe of this branch stuck into a deadlock after a few hundreds of iteration. The sign of starting deadlock is that 
"Waiting for Data" & "Data Layer prefect queue empty"

I believe GPUs are much faster than data fetching on my machine, therefore leading this issue. But it shouldn't be deadlock. 

Anyone good suggestions to solve this issue ? Thank you

**Comment by lukeyeager** [comment]
Can you try v0.14 and see if the issue is resolved?
