### ISSUE TITLE
CMake build issue with v0.14.0-rc.1

### ISSUE THREAD

**Issue by pclove1** [NVIDIA/caffe#72]
Hi,

I faced an issue while building `v0.14.0-rc.1` using CMake with the following error messages:
```
[ 77%] Linking CXX shared library ../../lib/libcaffe-nv.so
/usr/bin/ld: cannot find -lcnmem
collect2: ld returned 1 exit status
make[2]: *** [lib/libcaffe-nv.so.0.14.0-rc.1] Error 1
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2
```

Note: I was passing the following options to cmake command based on [this instruction](https://github.com/NVIDIA/DIGITS/blob/master/docs/InstallCaffe.md):
```
-DUSE_CNMEM=True -DCNMEM_INCLUDE=$CNMEM_HOME/include -DCNMEM_LIBRARY=$CNMEM_HOME/build/libcnmem.so
```

The workaround that I used to avoid this issue was to remove `-lcnmem` from this [line](https://github.com/NVIDIA/caffe/blob/v0.14.0-rc.1/CMakeLists.txt#L46).
i.e.
Before:
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DUSE_CNMEM -lcnmem")
```

After:
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DUSE_CNMEM")
```

**Comment by lukeyeager** [comment]
So you ended up building with CNMeM support and not linking to `libcnmem.so`? How does that work? Does your build end up utilizing CNMeM or not?

I haven't updated the DIGITS installation instructions for NVcaffe 0.14 yet, but I don't think I'll be recommending CNMeM anymore since we added the CUB allocator in https://github.com/NVIDIA/caffe/pull/62.

/cc @borisfom

**Comment by pclove1** [comment]
Yeah, I couldn't have a chance to try CUB allocator yet.

I thought cmake build used to be given an explicit path for `libcnmem.so` instead of `-lcnmem`.
I see this when I enable the verbose logs from make e.g. `VERBOSE=1 make`.

**Comment by borisfom** [comment]
As of now (and I believe it;s consistent with previous Digits release, it's up to you to make sure CNMEM library is found via LIBRARY_PATH/LD_LIBRARY_PATH environment (and readers found via INCLUDE env var).

Best,
-Boris.

**Comment by lukeyeager** [comment]
CUB was added to the `caffe-0.14` branch in https://github.com/NVIDIA/caffe/pull/62 and CNMeM was removed in https://github.com/NVIDIA/caffe/pull/82.

So I think this issue is no longer relevant.
