### ISSUE TITLE
Build nvidia caffe error on centOS 7

### ISSUE THREAD

**Issue by 201power** [NVIDIA/caffe#77]
Hello, 

I am trying to install Nvidia caffe 0.13 on centOS 7, However, I meet the following error when doing make all 

/bin/ld: cannot find -lcblas
/bin/ld: cannot find -latlas
collect2: error: ld returned 1 exit status

In the Makefile.config,I've changed to

BLAS:=atlas
BLAS_INCLUDE:=/usr/include/atlas
BLAS_LIB:=/usr/lib64/atlas

and I check atlas related file exist (package atlas-devel-3.10.1-7.el7.x86_64)

Any suggestion?

Thanks!

**Comment by lukeyeager** [comment]
Also filed at https://groups.google.com/d/msg/digits-users/lLXDonHir6Q/g72CF1yiAwAJ

**Comment by borisfom** [comment]
I would suggest doing cmake to set it all correctly. Makefile path may be made obsolete soon.

**Comment by lukeyeager** [comment]
Have you looked at the `BLAS` instructions on this page?

http://caffe.berkeleyvision.org/install_yum.html

**Comment by 201power** [comment]
Yes, I used instruction on http://caffe.berkeleyvision.org/install_yum.html to install ATLAS.

I tried to use cmake, it has some issues that's why I use makefile

**Comment by lukeyeager** [comment]
Seems like a popular issue. Without a CentOS machine to play with, all I can do is Google for you.

Duplicate issues:
https://github.com/BVLC/caffe/issues/3041
https://groups.google.com/d/msg/caffe-users/hIdauVM-hWs/AaYLMpdvEwAJ

Probably related:
https://groups.google.com/d/msg/caffe-users/Pyfp9eQoIMQ/PN5tx0oDh-UJ

Solved by reverting to an old version of the code:
https://groups.google.com/d/msg/caffe-users/3yKFC-ybJDg/_1vI26KnTjEJ

Here's somebody's config for CentOS 6.6:
https://groups.google.com/d/msg/caffe-users/5k45oLFAq3k/4XzMOjDo3BMJ

Looks like this guy is using OpenBLAS and has got it working:
https://groups.google.com/d/msg/caffe-users/tfw9y_DDwfY/5fmqAHwfBgAJ

I'm going to close this issue. Feel free to follow up with questions on whichever thread seems most promising to you. And please update this issue when you figure it out. Good luck, sorry I can't be more help!
