### ISSUE TITLE
Check failed: proto.SerializeToOstream(&output) 

### ISSUE THREAD

**Issue by kjw218** [NVIDIA/caffe#9]
Hello, I'm newbie of vision area
I'd like to Image training on Caffe (using my data)
but when I try to run make_imagenet_mean.sh file
I got an error
would you help me kindly?
 

this is the error message
------------------------------------------------------------------------------------------------------------------
F0703 09:53:03.039291  3732 io.cpp:67] Check failed: proto.SerializeToOstream(&output) 
*** Check failure stack trace: ***
    @     0x7f114c9a6daa  (unknown)
    @     0x7f114c9a6ce4  (unknown)
    @     0x7f114c9a66e6  (unknown)
    @     0x7f114c9a9687  (unknown)
    @     0x7f114cd1248c  caffe::WriteProtoToBinaryFile()
    @           0x402088  main
    @     0x7f114bbb6ec5  (unknown)
    @           0x40240a  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)
Done.
------------------------------------------------------------------------------------------------------------------------

I refer to this.
https://github.com/BVLC/caffe/tree/master/examples/imagenet

and I modify ~/cafe/data/ilsvrc12/train.txt, val.txt, 
like this.. 

train.txt
---------------------------------
n01440764/HYIcicleM.jpg 0
n01440764/HYIcicleM1.jpg 0
n01440764/HYIcicleM2.jpg 0
n01440764/HYIcicleM3.jpg 0
n01440764/HYIcicleM4.jpg 0
n01440764/HYIcicleM5.jpg 0
...
----------------------------------------------------

val.txt
-----------------------------------------------------------
HYIcicleM.jpg 0
HYIcicleM1.jpg 0
HY4OclockB.jpg 1
HY4OclockB1.jpg 1
HY4OclockB2.jpg 1
HY4OclockB(copy)9.jpg 2
HY4OclockB(copy)10.jpg 2
...
----------------------------------------------------------

thank you!

**Comment by lukeyeager** [comment]
See discussion at https://github.com/NVIDIA/DIGITS/issues/84 for more information.

Can you please bump this thread with any new information you can provide:
https://groups.google.com/forum/#!topic/caffe-users/KGF3s1Ztn88

**Comment by lukeyeager** [comment]
Does the discussion at https://github.com/BVLC/caffe/issues/387 solve your problem?

> I had this error because one of the variables set in make_image_mean.sh was set to a non-existent path.

**Comment by lukeyeager** [comment]
> I'm closing this since I can't reproduce it. If anyone else runs into this issue, let me know and I'll pass it along to the Caffe developers.
https://github.com/NVIDIA/DIGITS/issues/84#issuecomment-110453751

Closing this, too.
