### ISSUE TITLE
caffe 0.13 will not compile with CuDNN v3 and CUDA 7

### ISSUE THREAD

**Issue by alfredox10** [NVIDIA/caffe#95]
I have been having this problem for about a week now and tried everything I did before to install caffe on other systems and nothing has worked thus far. The issue is caffe will compile without CuDNN, but it will not compile with it enabled.

I have already performed these steps, and still no change:
1. copy CuDNN files to cuda folders
libcudnn.so.7.0.64 and libcudnn_static.a to /usr/local/cuda/lib64
cudnn.h to /usr/local/cuda/include
2. uncommented USE_CUDNN := 1 in caffe makefile config

Here is the full dialog: http://pastebin.com/y68HnhR4

CXX .build_release/src/caffe/proto/caffe.pb.cc
AR -o .build_release/lib/libcaffe-nv.a
LD -o .build_release/lib/libcaffe-nv.so.0.13.2
/usr/bin/ld: cannot find -lcudnn
collect2: error: ld returned 1 exit status
make: *** [.build_release/lib/libcaffe-nv.so.0.13.2] Error 1

I keep getting that same error over and over, and unable to fix it.

Final note, I have verified all the files are found in the paths stated. I also disabled cudnn in makefile config and compiled successfully. I also used caffe with a trained file without cudnn and everything works, even import caffe works from python.

**Comment by lukeyeager** [comment]
You probably also need these symlinks:
```
.
├── libcudnn.so -> libcudnn.so.7.0
├── libcudnn.so.7.0 -> libcudnn.so.7.0.64
├── libcudnn.so.7.0.64
└── libcudnn_static.a
```
Aren't they included in the cuDNN v3 installer?

**Comment by lukeyeager** [comment]
Also, why not upgrade to v0.14? Here are the instructions to download cuDNN v4 and build the latest version of NVcaffe:

https://github.com/NVIDIA/DIGITS/blob/digits-3.0/docs/BuildCaffe.md

**Comment by alfredox10** [comment]
No there is no symlinks in the folder. These are the full contents of the folder:
/include/cudnn.h
/lib64/libcudnn.so
/lib64/libcudnn.so.7.0
/lib64/libcudnn.so.7.0.64
/lib64/libcudnn_static.a

That was a good suggestion though, I went back and found out that the symlinks where missing because i transfered the files over my NAS uncompressed. So I went back and got the original files, put the symlinks and all with: 
sudo cp lib64/* /usr/local/cuda/lib64/

I went to the cuda lib64 folder and verified all the contents are there, however the symlinks aren't symlinks anymore but actual files. I recompiled, and still same error.

I am currently using 0.13 and v3 on all other machines so I wanted to just get things working to do testing in a cluster setup with multiple machines. But I will probably give that a shot if I can't get this one to work, good suggestion.

**Comment by alfredox10** [comment]
All right I am following the instructions on https://github.com/NVIDIA/DIGITS/blob/digits-3.0/docs/BuildCaffe.md but it doesn't say how to enable CuDNN.
I ask because it seems this way builds the program differently. Should I change this line
set(Caffe_HAVE_CUDNN FALSE)
to TRUE in the caffe/build/CaffeConfig.cmake file? Or should I uncomment this line
# USE_CUDNN := 1
like I always have in the Makefile.config?

**Comment by lukeyeager** [comment]
If you use CMake, cuDNN should be detected automatically.
```
$ cmake ..

...

-- Found cuDNN (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)

...

-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_35
--   cuDNN             :   Yes
```

**Comment by alfredox10** [comment]
Don't see that on mine, this is my cmake .. output: http://pastebin.com/76J6qghs

**Comment by alfredox10** [comment]
I found in the CMakeCache.txt this line:
//Toolkit location.
CUDA_TOOLKIT_ROOT_DIR:PATH=/usr/local/cuda

That's where my cuda's installed, it's looking in the right place.

**Comment by lukeyeager** [comment]
You can't even find CUDA? How did you install it? You are on Ubuntu 14.04,
right?

**Comment by alfredox10** [comment]
make can find CUDA, this cmake can't for some reason. I installed it with the deb package using this guide: https://github.com/BVLC/caffe/wiki/Install-Caffe-on-EC2-from-scratch-(Ubuntu,-CUDA-7,-cuDNN)
with cuda_7.0.28_linux.run

However I reinstalled it with apt-get using the link you gave me.

All the files are there in /user/local/cuda

**Comment by alfredox10** [comment]
Ok I was able to compile with CuDNN and CUDA being detected. I had to completely delete the CUDA folder and reinstall it.
However now I get this error:
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1217 17:28:46.858932  4889 common.cpp:162] Check failed: error == cudaSuccess (10 vs. 0)  invalid device ordinal
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by alfredox10** [comment]
All right fixed everything up, the error was due to incorrect set_device() number. I have 1 GPU in this system, and I was trying to set it to GPU #1, which would mean a 2nd GPU in the system.

Also of note, it may be that with this install method it does not pickup versions of CUDA not installed through the apt-get repo provided in your link, just a thought.

This can be closed, 
Thanks!
