### ISSUE TITLE
make runtest failure (0.14.0-rc.3 and CuDNN 4)

### ISSUE THREAD

**Issue by mfernezir** [NVIDIA/caffe#98]
```
[  FAILED  ] 1 test, listed below:
[  FAILED  ] CuDNNBatchNormLayerTest/0.TestGradient, where TypeParam = float
```

I've done make all, make test, make pycaffe and make distribute and there were no errors reported.  Caffe also imports fine under Python. However, make runtest has one test failure.

**Comment by lukeyeager** [comment]
NVcaffe v0.14 and cuDNN v4 are now publicly released. Can you try rebuilding with the latest versions to make sure that this issue is resolved?

**Comment by mfernezir** [comment]
Tests pass with the current version. :)
